### ISSUE TITLE
Inconsistent results depending on the data-entry format

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#100]
Validating the variant description NC_000018.9:g.12195773T>G results in the error message "Please ensure the requested chromosome version relates to a supported genome build. Supported genome builds are: GRCh37, GRCh38". This suggests that NC_000018.9 is neither GRCh37 nor 38.

Instead, if I validate the description chr18:g.12195773T>G, selecting genome build GRCh37, the validation completes successfully and produces the output descrition NC_000018.9:g.12195773T>G which failed to validate when entered directly.

**Comment by PeteCausey-Freeman** [comment]
Not quite.  If you enter NC_000018.9:g.12195773T>G and GRCh37, it validates just fine. If you did not specify a genome build VV auto selects GRCh38 and so validation fails. This will only happen in intergenic regions and was not anticipated. Will need to see how the code works for intergenic regions if the wrong genome build is entered. 

Relatively low priority, but certainly worth checking. Thanks for the report

**Comment by PeteCausey-Freeman** [comment]
Perhaps the simplest fix would be to warn that NC_000018.9 is not supported in the context of GRCh38?

**Comment by leicray** [comment]
I think that it is slightly higher priority than "low" as it's very confusing.

If I try to validate NC_000017.10:g.48275363C>A (which is intragenic) without specifying the genome build, then VV figures things out automagically, so it's confusing when it fails to do the same with an intergenic variant such as NC_000018.9:g.12195773T>G when the genome build is, likewise, not specified.

It would certainly be good to display a warning message of some sort along with some simple guidance to the user on how to remedy the problem.

**Comment by PeteCausey-Freeman** [comment]
At a guess, I think the only thing that can be done is an improved warning. VV does not figure anything out regarding genome builds. If no build is provided it defaults to GRCh38. 

The current warning will become 
"Please ensure the requested chromosome version relates to a supported genome build. Supported genome builds are: GRCh37, GRCh38, hg19 and hg38" (Remember, the current live site will become obsolete), but is not helpful. 

How about

The requested chromosome version is not valid in the context of genome build <selected build>. Please select an alternate genome build. Supported genome builds are: GRCh37, GRCh38, hg19 and hg38".

Note, these changes will not be applied until the new website and API are deployed.

**Comment by leicray** [comment]
How about:

"Validation of genomic variant descriptions in the context of a chromosome reference sequence defaults to GRCh38 (hg38, build 38). For variants in intergenic regions, validation will fail if the chromosome reference sequence corresponds to GRCh37 (hg19, build 19), but no genome build was selected. In such cases, please resubmit the variant description and select GRCh37".

Wordy, but precise.

**Comment by PeteCausey-Freeman** [comment]
But not accurate I'm afraid. Defaulting to GRCh38 is a consequence of not stating a genome build and is not a related issue. Actually, cookies the new site puts on the system will change this behavior as build will most likely always be selected 

I have changed this to 
"Validation will fail if the selected chromosome reference sequence does not corresponds to selected genome build. Please re-submit your query and select an alternate genome build. Note, if you did not specify a genome build, VariantValidator defaults to GRCh38"

**Comment by PeteCausey-Freeman** [comment]
Closed here https://github.com/openvar/variantValidator/issues/100
