### ISSUE TITLE
Persistant MySQL connections are leaky and are causing servers to fall over

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#109]
The Py3 version of VV creates a MySQL connection at setup. After a lot of reading and asking expert data scientists, it has become apparent that persistent connections are leaky and cause problems. The suspicion is that these leaky connections are causing the VV REST API to fall over, both in docker and on a server. The key element we were missing is high-traffic levels, hence we could not re-produce the problem. Uploading VV Py3 to LAMP 188 and plugging in replicated the issue first noted by DB.

This needs to be corrected before we roll out the new vvWEB and REST API.

**Comment by PeteCausey-Freeman** [comment]
Having thought about this over night, if I remember correctly, the connection pool can be left open. The pool recycles its connections every x number of seconds. However, if a connection to a pooled connection is established, it cannot be recycled until closed. It would be worth checking the py2 version of vv.

**Comment by TeriForey** [comment]
I'm going to try to look over this later today, maybe try to add a connection check before we query the database, which if fails will recreate the connection. Hopefully that should do the trick.

**Comment by i3hsInnovation** [comment]
Forgot to say. The current development branch is develop_v3. Think we need a clean up.

p.s. Logged in as an alternate user!

**Comment by PeteCausey-Freeman** [comment]
Seems to be resolved as of your last commit. Merged in 
https://github.com/openvar/variantValidator/pull/111
