### ISSUE TITLE
Correction of typos in variant descriptions

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#112]
According to the preprint of the manuscript describing [VarHarmonizer](https://arxiv.org/abs/1911.08408) the two most common typos in variant descriptions are use of a comma instead of a full-stop in c. descriptions and a full-stop instead of greater-than in nucleotide substitutions, e.g.

NM_000088.3:c,589G>T should be corrected to NM_000088.3:c.589G>T

and

NM_000088.3:c.589G.T should also be corrected to NM_000088.3:c.589G>T

The manuscript also suggests that NM_000088.3:c.589G)T is a common error, but it is difficult to understand how this might arise.

**Comment by PeteCausey-Freeman** [comment]
In approximately 4 years of capturing user errors errors whilst developing VV, these so called common mistakes never once came up. I can log on to the gmail account we used during development and see whether this ever arose once I stopped monitoring on a daily basis. I assume this pre-print has not been reviewed yet? Hopefully the reviewers are astute as they ought to be.

Anyway, since we now have a use-case we can look into come of these.

I am not sure about "NM_000088.3:c.589G.T should also be corrected to NM_000088.3:c.589G>T". I can also see that a user might have been trying to (incorrectly) describe two possible alternates and has forgotten to provide the reference base e.g. NM_000088.3:c.589N>G,T. This is equally plausible and IS IN FACT a common mistake. What do you think?

"NM_000088.3:c,589G>T should be corrected to NM_000088.3:c.589G>T" Fair enough

"The manuscript also suggests that NM_000088.3:c.589G)T is a common error". I struggle to believe this. Why would we ever see a close bracket without an open bracket. I want to see the evidence. Again, do we want to correct this. I never once saw it in 4 years of monitoring and we have processed millions upon millions of variants.

**Comment by PeteCausey-Freeman** [comment]
So, I looked at the current response for NM_000088.3:c,589G>T. I think the warning is very accurate indeed, but I will auto-correct to NM_000088.3:c.589G>T

```json
{
    "flag": "warning",
    "metadata": {
        "seqrepo_db": "2018-08-21",
        "uta_schema": "uta_20180821",
        "variantvalidator_hgvs_version": "1.2.5.vv1",
        "variantvalidator_version": "1.0.1.dev48+g1493b58"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "submitted_variant": "NM_000088.3:c,589G>T",
        "transcript_description": "",
        "validation_warnings": [
            "Variant description NM_000088.3:c,589G>T lacks the . character between <type> and <position> in the expected pattern <accession>:<type>.<position>"
        ]
    }
}
```

**Comment by PeteCausey-Freeman** [comment]
Updated to (I'm not saying corrected!)

```json
{
    "NM_000088.3:c.589G>T": {
        "alt_genomic_loci": [],
        "gene_ids": {
            "ensembl_gene_id": "ENSG00000108821",
            "entrez_gene_id": "1277",
            "hgnc_id": "HGNC:2197",
            "omim_id": [
                "120150"
            ],
            "ucsc_id": "uc002iqm.4"
        },
        "gene_symbol": "COL1A1",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "LRG_1t1:c.589G>T",
        "hgvs_lrg_variant": "LRG_1:g.8638G>T",
        "hgvs_predicted_protein_consequence": {
            "slr": "NP_000079.2:p.(G197C)",
            "tlr": "NP_000079.2(LRG_1p1):p.(Gly197Cys)"
        },
        "hgvs_refseqgene_variant": "NG_007400.1:g.8638G>T",
        "hgvs_transcript_variant": "NM_000088.3:c.589G>T",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000017.10:g.48275363C>A",
                "vcf": {
                    "alt": "A",
                    "chr": "17",
                    "pos": "48275363",
                    "ref": "C"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000017.11:g.50198002C>A",
                "vcf": {
                    "alt": "A",
                    "chr": "17",
                    "pos": "50198002",
                    "ref": "C"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000017.10:g.48275363C>A",
                "vcf": {
                    "alt": "A",
                    "chr": "chr17",
                    "pos": "48275363",
                    "ref": "C"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000017.11:g.50198002C>A",
                "vcf": {
                    "alt": "A",
                    "chr": "chr17",
                    "pos": "50198002",
                    "ref": "C"
                }
            }
        },
        "reference_sequence_records": {
            "lrg": "http://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_1.xml",
            "protein": "https://www.ncbi.nlm.nih.gov/nuccore/NP_000079.2",
            "refseqgene": "https://www.ncbi.nlm.nih.gov/nuccore/NG_007400.1",
            "transcript": "https://www.ncbi.nlm.nih.gov/nuccore/NM_000088.3"
        },
        "refseqgene_context_intronic_sequence": "",
        "submitted_variant": "NM_000088.3:c,589G>T",
        "transcript_description": "Homo sapiens collagen type I alpha 1 chain (COL1A1), mRNA",
        "validation_warnings": [
            "Variant description NM_000088.3:c,589G>T contained the , character between <type> and <position> in the expected pattern <accession>:<type>.<position> and has been auto-corrected"
        ]
    },
    "flag": "gene_variant",
    "metadata": {
        "seqrepo_db": "2018-08-21",
        "uta_schema": "uta_20180821",
        "variantvalidator_hgvs_version": "1.2.5.vv1",
        "variantvalidator_version": "1.0.1.dev48+g1493b58"
    }
}
```

**Comment by leicray** [comment]
I agree that it is best not to correct NM_000088.3:c.589G.T for the reasons that you have given.

I presume that the "correction" code for "c," will also "auto-correct" "n," and "g,".

I too am struggling to see why anybody might mistype a variant description as "NM_000088.3:c.589G)T". I can understand why somebody might mistype NM_000088.3:c.589G>T as NM_000088.3:c.589G.T as the ">" and "." symbols share the same physical key on standard UK and US keyboards, and also on some other non-English keyboards. As far I can see, the ">" and ")" symbols do not share the same physical key on any keyboard for which I have been able to find a layout chart.

**Comment by PeteCausey-Freeman** [comment]
Running the variant with the ) did identify a bug which has been squashed.

Here is the output

```json
>>> print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
{
    "flag": "warning",
    "metadata": {
        "seqrepo_db": "2018-08-21",
        "uta_schema": "uta_20180821",
        "variantvalidator_hgvs_version": "1.2.5.vv1",
        "variantvalidator_version": "1.0.1.dev48+g1493b58"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "submitted_variant": "NM_000088.3:c.589G)T",
        "transcript_description": "",
        "validation_warnings": [
            "NM_000088.3:c.589G)T: char 18: expected one of =, or >"
        ]
    }
}
>>> 
```

To be brutally honest, I feel the user should intervene here. Missing the . in c. is a simple mistake, but using ) rather than > is pretty terrible and is a point of education. I'm inclined to leave it????

**Comment by leicray** [comment]
>  I'm inclined to leave it????

I agree.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/1b3bf7b494b5d48830a74424984148c301b8e54e closes this issue. We can re-open if necessary
