### ISSUE TITLE
Inconsistency in API arguments for selecting transcripts

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#125]
The `variantvalidator` API method requires "all" for returning all transcripts, while the `variantformatter` API method requires "None" there for the same functionality. I would suggest adding "all" there too, but still allow for "None" for backwards compatibility.

**Comment by PeteCausey-Freeman** [comment]
all is permitted by the API for VariantFormatter. It is listed as ab option in the swagger documentation (although I forgot to close the bracket). Have I missed something?

**Comment by ifokkema** [comment]
This is about the transcripts to select. Filling in `all`, gets me:
```json
      "hgvs_t_and_p": {
        "all": {
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": null,
          "p_hgvs_tlc": null,
          "t_hgvs": null,
          "transcript_variant_error": "No alignment data available for transcript all and chromosome NC_000017.10"
        }
      },
```

whereas, filling in `None` gets me:
```json
      "hgvs_t_and_p": {
        "NM_000088.3": {
          "gap_statement": null,
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_000079.2:p.(G197C)",
          "p_hgvs_tlc": "NP_000079.2:p.(Gly197Cys)",
          "t_hgvs": "NM_000088.3:c.589G>T",
          "transcript_variant_error": null
        }
      },
```

Relevant URLs are:
- `https://rest.variantvalidator.org/VariantFormatter/variantformatter/GRCh37/NC_000017.10%3Ag.48275363C%3EA/refseq/all/False?content-type=application%2Fjson` and 
- `https://rest.variantvalidator.org/VariantFormatter/variantformatter/GRCh37/NC_000017.10%3Ag.48275363C%3EA/refseq/None/False?content-type=application%2Fjson`.

**Comment by PeteCausey-Freeman** [comment]
Thanks for the URLs. Will look at it.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantFormatter/commit/6d314c3b0258aec8a60e5edb9fc17b7a3f24ceb2 fixes the bug

https://github.com/openvar/rest_variantValidator/issues/24 Reminds me to update the swagger docs :)
