### ISSUE TITLE
Inconsistency in API arguments for selecting genome builds

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#126]
The `variantvalidator` API method supports GRCh37, GRCh38, hg19, hg38. The `variantformatter` API method allows for only GRCh37 and GRCh38.

- I assume that GRCh37 and hg19 are aliases and GRCh38 and hg38 as well, although GRCh37 and hg19 are apparently different in the MT sequence (according to the UCSC).
  - If they are not aliases, this should be documented, perhaps?
  - If they are aliases, fully treating them as such might speed up the application?
- It would be more logical to also allow for hg19/hg38 input in the `variantformatter` method as well.

**Comment by PeteCausey-Freeman** [comment]
We can likely sort this as discussed in https://github.com/openvar/variantFormatter/issues/9.

**Comment by PeteCausey-Freeman** [comment]
This is now resolved. https://github.com/openvar/variantFormatter/commit/7382c77fae52d4360d4210c9c4d891e532bfb6c2

Getting there :)

**Comment by ifokkema** [comment]
Excellent, you're on fire! :fire::fire::fire:

**Comment by PeteCausey-Freeman** [comment]
Couple more issues to resolve then on to making the LOVD endpoint for your approval sir!
