### ISSUE TITLE
Inconsistency in API output for protein prediction for non-coding transcripts

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#127]
Non-coding transcripts have some odd values in the protein prediction fields, and inconsistency. The `p_hgvs_slc` and `p_hgvs_tlc` fields in the `variantformatter` API method output read "non-coding", but the `slr` and `tlr` fields in the variantvalidator output read "Non-coding :n.", while I expect the same value there. And probably, a value like False would make more sense than a string which users will need to parse to see if the transcript is coding or not.
Finally, perhaps using the same field names between the two methods would add to consistency between the two methods (but this will break existing user's implementations so API versioning would be required).

**Comment by PeteCausey-Freeman** [comment]
Nice spot. Thanks

**Comment by PeteCausey-Freeman** [comment]
Logging my working

VV editing
***

The Non-coding :n. format was for practical reasons. it's a "fake" hgvs like parseable string. 

This has now been updated to None

Updated VVweb to handle in interactive mode

Code updated for batch mode also. Needs testing but ought to work

VF editing
***

Updated non-coding to None

**Comment by PeteCausey-Freeman** [comment]
Agreed r.e. the consistency, but until we can implement the versioning as suggested, let's re-visit at a later date.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantFormatter/commit/aa3f4593cc747de35f73b743382c58ca9fe8410d Closes wrt VariantFormatter
https://github.com/openvar/variantValidator/commit/4ff5b25e463543094fb9cbefdaacc0d32638ae82 closes for VV

**Comment by PeteCausey-Freeman** [comment]
Closes for VV with https://github.com/openvar/variantValidator/commit/4ff5b25e463543094fb9cbefdaacc0d32638ae82
