### ISSUE TITLE
NP IDs sometimes represented as MD5 sums

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#129]
I've seen NP's represented as MD5 sums. See:
https://rest.variantvalidator.org:443/variantvalidator/hg19/NC_000015.9%3Ag.40699840C%3ET/all

> "tlr": "MD5_95f54b375a45d5207c4449383a55b005:p.(Arg53Cys)"

**Comment by PeteCausey-Freeman** [comment]
I think this might be a UTA error. We will look into it during the re-design

**Comment by ifokkema** [comment]
Tested on Dev server; this still happens; MD5 hash found instead of NP ID:
https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/hg19/NC_000015.9%3Ag.40699840C%3ET/NM_001354597.1?content-type=application%2Fjson

However, output indicates:
```json
  "uta_schema": "uta_20180821",
```

Shouldn't that be something newer now?

**Comment by PeteCausey-Freeman** [comment]
Also yes, the seqrepo will be updated.

**Comment by PeteCausey-Freeman** [comment]
Corrected in VVTA
