### ISSUE TITLE
Add genomic start and end in gene2transcripts

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#130]
Currently, the `gene2transcripts` API method returns the gene and transcript information, and per transcript also the coding start and coding stop. It would be useful to also have the genomic start and genomic stop of the transcript.

**Comment by PeteCausey-Freeman** [comment]
To clarify, do you mean the absolute boundaries of the transcript in genomic context, i.e. where in the genome is the 1st base of the transcript and where is the last?

**Comment by ifokkema** [comment]
Yes, exactly! We use that internally in LOVD to calculate the distance between transcripts and variants, so we can predict if there is a mapping, before calling any APIs. We also use that for knowing the (approximate) position of the gene, which we don't store at the gene table but rather take from the transcript table.

**Comment by PeteCausey-Freeman** [comment]
OK, I have had a bash at mocking this up.
Typically the question is more difficult than it might have been because we have multiple genomic and gene alignments. Sigh!

Here is a mock up of the JSON output

```json
{
    "current_name": "collagen type I alpha 1 chain",
    "current_symbol": "COL1A1",
    "previous_name": "collagen, type I, alpha 1",
    "previous_symbol": "COL1A1",
    "transcripts": [
        {
            "coding_end": 4521,
            "coding_start": 128,
            "description": "Homo sapiens collagen type I alpha 1 chain (COL1A1), mRNA",
            "genomic_spans": {
                "NC_000017.10": {
                    "span_end": 48279000,
                    "span_start": 48261457
                },
                "NC_000017.11": {
                    "span_end": 50201639,
                    "span_start": 50184096
                },
                "NC_018928.2": {
                    "span_end": 48343284,
                    "span_start": 48325754
                },
                "NG_007400.1": {
                    "span_end": 22544,
                    "span_start": 5001
                }
            },
            "reference": "NM_000088.3"
        },
        {
            "coding_end": 4521,
            "coding_start": 128,
            "description": "Homo sapiens collagen type I alpha 1 chain (COL1A1), mRNA",
            "genomic_spans": {
                "LRG_1": {
                    "span_end": 22544,
                    "span_start": 5001
                },
                "NG_007400.1": {
                    "span_end": 22544,
                    "span_start": 5001
                }
            },
            "reference": "LRG_1t1"
        }
    ]
}
```

Need to test some more genes before committing but comments please

**Comment by ifokkema** [comment]
It looks great, thanks!

- In principle I'm OK with the term `span_start` and `span_end`; I checked other API calls to check consistency and found that `hgvs2reference` uses `start_position` and `end_position` for variants. They are not very compatible, but I think I prefer *_start and *_end over start_* and end_*. Also, using "span" makes sense over "position". So long story short, I think the span_* fields are correctly named, but I wanted to mention the slight inconsistency compared to other calls.

- All positions are 1-based, correct?

Out of my own curiosity, how many genes map to different chromosomes, when comparing between hg19/hg38?

**Comment by PeteCausey-Freeman** [comment]
This is useful information because we haven't had to consider it before so happy to have guidance. Given that it would be easier to change the new tool at this point over this, perhaps we ought to use start_position end_position. I also prefer span_start because it does what it says on the tin, but thinking about other resources outside this project, perhaps start_position and end_position make more sense????

Positions are 1 based. I checked them against the COL1A1 RefSeqGene. Will check a few more before committing.

No idea about differential mapping of genes question. Could write something to parse the database, but fun things sometimes need to wait :). Interesting idea though

**Comment by PeteCausey-Freeman** [comment]
I am aware theGRCh38 lacks some genes in GRCh37, but no one has yet been able to answer a simple question. How many of these are re-named genes and not missing genes?

**Comment by PeteCausey-Freeman** [comment]
Note to self. Remember to tag before merging any of these changes into develop

**Comment by ifokkema** [comment]
> (...) perhaps we ought to use start_position end_position. I also prefer span_start because it does what it says on the tin, but thinking about other resources outside this project, perhaps start_position and end_position make more sense????

It's consistent with the `hgvs2reference` API, so sounds good :)


> No idea about differential mapping of genes question. Could write something to parse the database, but fun things sometimes need to wait :). Interesting idea though

No worries, I was just wondering if you happened to know! I still need to fully plan my database changes for supporting multiple builds in LOVD3.


> I am aware the GRCh38 lacks some genes in GRCh37, but no one has yet been able to answer a simple question. How many of these are re-named genes and not missing genes?

Exact numbers I also don't have. But I do know it's a combination; sometimes we need to keep a gene's old symbol to get hg19 mappings and need the new name for hg38 mappings, sometimes a gene just doesn't have hg19 mappings for transcripts, and we need to wait to go to hg38 to be able to support it.

**Comment by PeteCausey-Freeman** [comment]
Closed with https://github.com/openvar/variantValidator/commit/4ff5b25e463543094fb9cbefdaacc0d32638ae82
