### ISSUE TITLE
Website: Sign in using third party accounts don't work

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#133]
When trying to log in here:
https://variantvalidator.org/accounts/login/

Using any of the third-party accounts, fail with a `redirect_uri_mismatch`.

**Comment by PeteCausey-Freeman** [comment]
Yep. aware of this one :)
Thanks for adding the issue though

**Comment by PeteCausey-Freeman** [comment]
Think this now works. I have tested ORCID. Raymond, have you tested google or git?

**Comment by ifokkema** [comment]
Great!
Google works for me!

**Comment by ifokkema** [comment]
... although even after verifying my email it keeps saying my profile is only half complete. Personal information has a checkmark, email address verification not. Not sure if this is related to the type of account?

**Comment by PeteCausey-Freeman** [comment]
We need users to verify email addresses because batch services require an email address to return results. It's also a spam filter. We also ask for a few details from the user so we can show the universitiees that we are relevant and get them to keep funding us :)

Can you fill in and let me know if there are any errors. Thanks for testing git for me

**Comment by ifokkema** [comment]
> We need users to verify email addresses because batch services require an email address to return results. It's also a spam filter. We also ask for a few details from the user so we can show the universitiees that we are relevant and get them to keep funding us :)

I understand, and I'm letting you know that it _doesn't work_ :wink:
I already verified my email, it even says so, but my account is still marked incomplete.

**Comment by PeteCausey-Freeman** [comment]
Ah. :)

**Comment by PeteCausey-Freeman** [comment]
Looks like it is isolated to GitHub accounts.

**Comment by PeteCausey-Freeman** [comment]
Seems that GitHub sign-ups are failing to set the account expiry date. Looking at the code

**Comment by ifokkema** [comment]
Note that I used Google, but maybe they're having the exact same issue... In case a screenshot helps:


![Screenshot_2020-02-11_10-52-01](https://user-images.githubusercontent.com/11665018/74234878-28d14a00-4cce-11ea-9672-0cae2c987a8c.png)


Reloading the page doesn't make the warning go away.

**Comment by PeteCausey-Freeman** [comment]
Thats useful. Thanks. Probably not the expiry then

**Comment by PeteCausey-Freeman** [comment]
Hi @ifokkema . Think @TeriForey has managed to figure out what the issues is. Still working on the solution.

For some reason, the User Profiles are not being updated when the email address is verified. This is why we are not able to get 100% completion. This is happening for your google account and my github. I'm going to check configurations. For some users it has worked but not for others.

**Comment by PeteCausey-Freeman** [comment]
Just tested this with a normal account creation rather than social. Worked fine.

**Comment by PeteCausey-Freeman** [comment]
In the GitHub created account, if I click profile verify email address, I get a green verified. However, in admin and on the profile page. This does not seem to be the case. 

If I re-verify, this does not update admin. Still shows as verified in profile, but not via admin hence profile only 50%.

@ifokkema I have manually added your email address as verified.

**Comment by ifokkema** [comment]
Thank you!

**Comment by PeteCausey-Freeman** [comment]
I just checked, and re-sending the verification email does not update the admin database either. 

However, if I add a new email and then verify the new email, I am able to complete. Why is the original email provided via Social accounts not added as verified in the admin database?

**Comment by ifokkema** [comment]
Just to update you; my profile is still 50% complete, even though my profile information has been entered, and my email address has been verified. Probably not very important, but just to let you know (I'm going through all of my issues, LOL). :laughing:

**Comment by PeteCausey-Freeman** [comment]
Still haven't figured out how to fix this.

As for issues, if it's a UTA issue, it will not be fixed yet :)

**Comment by PeteCausey-Freeman** [comment]
Removed. Too complicated and annoying
