### ISSUE TITLE
Add input genome build to the output of VV and VF

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#138]
Required due to liftover issues

**Comment by PeteCausey-Freeman** [comment]
selected_build flag of https://github.com/openvar/variantFormatter/commit/7382c77fae52d4360d4210c9c4d891e532bfb6c2 closes for VariantFormatter

**Comment by VariantValidator** [comment]
https://github.com/openvar/variantValidator/commit/58eef315610e2d57bbf95670c69deb0054546623 closes for VariantValidator
