### ISSUE TITLE
Add NP IDs to gene2transcripts output

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#139]
The gene2transcripts service allows for listing all available transcripts for a certain gene. The NM (or NR) IDs are given, but to get to the NP IDs, I actually need to submit a variant and take it off the protein prediction. Could the NP IDs be added to the gene2transcripts output as well?

**Comment by PeteCausey-Freeman** [comment]
I think this should be doable. Planning on getting on with some coding next week.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/ce0715ae8a69d17cc5ba8315f557bbbda5e0595a

closes

**Comment by ifokkema** [comment]
Thank you! Could you update the development site, so I can test my code? :grimacing: 
Thanks! :smile: :+1:

**Comment by PeteCausey-Freeman** [comment]
Maintenance day. Will get it done tomorrow

**Comment by PeteCausey-Freeman** [comment]
Hi @ifokkema . Now live on dev server

**Comment by ifokkema** [comment]
Excellent, thank you! It works like a charm!
I see some older transcripts don't always provide a value (e.g. IVD's NM_001354597.1 while NM_001354597.2 does return NP_001341526.1), but that will be due to the underlying database, I reckon.

**Comment by PeteCausey-Freeman** [comment]
Absolutely. Please can you record transcripts where this happens. We can add them to the database where possible otherwise just remove them as incomplete records

**Comment by ifokkema** [comment]
Oh, I'd rather not have these removed, I'm quite happy with the legacy transcript mappings. We can use this to update LOVDs, perhaps even build an automated "upgrade my transcript" feature. New transcripts have the NPs, so that is the most important part :wink:

**Comment by PeteCausey-Freeman** [comment]
OK, then we can look into the issue and update the missing records. They really need to be there if er have the transcript data. 

Please can tou send me as many examples as you find and I'll send it across to John for analysis

**Comment by ifokkema** [comment]
For IVD, it's `NM_001354597.1`, `NM_001354598.1`, `NM_001354599.1`, `NM_001354600.1`, `NM_001354601.1`. I can write a script to loop a bunch of genes to detect a longer list if you need, but I suppose a query in the database will also find them all?
