### ISSUE TITLE
Indicate strand in gene2transcripts output or switch position fields

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#140]
Related to #130; the gene2transcripts API now returns genomic locations, which is excellent. However, for genes on the reverse strand, the `start_position` is lower than the `end_position`, which means the end of the gene is at the `start_position` and the start of the gene is at the `end_position`. I suggest to switch them for genes on the reverse strand, or otherwise indicate the strand that the gene is on, so I could switch these fields myself. Thanks! :smile:

**Comment by PeteCausey-Freeman** [comment]
Thanks for spotting that. Will correct it

**Comment by PeteCausey-Freeman** [comment]
Fixed.

**Comment by PeteCausey-Freeman** [comment]
Also added orientation. We use 1 for + and -1 for -

**Comment by ifokkema** [comment]
Excellent, thank you! I will go and test! (probably tomorrow).

**Comment by ifokkema** [comment]
Works perfectly, thank you! :smile:
