### ISSUE TITLE
Some issues and requests with gene2transcripts transcript positions

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#141]
I've been testing the `gene2transcripts` service, and I ran into some issues. Also, I have some requests that would make the service more useful (for me, but I think also for others).

Examples are from the [IVD gene](https://rest.variantvalidator.org/VariantValidator/tools/gene2transcripts/IVD?content-type=application%2Fjson).

- It seems the `coding_start` fields are off by one. Example, NM_002225.3 has a 5' UTR of 334, yet the `coding_start` field says 336. This should be 335. Confirmed with NM_002225.4.
- For NRs, the `coding_start` and `coding_end` fields are set to "non-coding". I suggest to add `NULL` there, or another value that represents an empty value.

----

- A request; would it be possible to add a value for the length of the transcript, on the transcript level? Like, `transcript_length` or so? This would allow me to calculate which c.* position would run off the end of the transcript. For instance, NM_002225.3 should have a `coding_start` of 335, a `coding_end` of 1615, and a `transcript_length` of 4665. This allows me to know that c.-334 is the first base of the transcript, and c.*3050 is the last.

**Comment by PeteCausey-Freeman** [comment]
I predict that this is linked to antisense genes?????

Will got is sorted ASAP. Transcript length should not be a problem either

**Comment by ifokkema** [comment]
> I predict that this is linked to antisense genes?????

IVD (my example) is sense, but I checked with DMD (reverse strand), and for NM_004006.2 the returned values are `{"coding_start": 246, "coding_end": 11302}`. Correct would be a start of 245. So sense/antisense doesn't matter in this case.

> Will got is sorted ASAP. Transcript length should not be a problem either

Thank you!!

**Comment by PeteCausey-Freeman** [comment]
I checked with COL1A1. Also 1base out. Thanks for this. On it

**Comment by PeteCausey-Freeman** [comment]
Resolved the cds start being out by 1

**Comment by PeteCausey-Freeman** [comment]
Added transcript length and orientation to the output. Will close when committed.

**Comment by ifokkema** [comment]
Excellent, thank you! I will go and test! (probably tomorrow).

**Comment by ifokkema** [comment]
Works perfectly, thank you! :+1:
