### ISSUE TITLE
Variants outside of chromosome range/boundaries don't return proper error message

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#146]
The LOVD endpoint and VariantFormatter return an HTTP500 for a variant outside of the boundaries of the chromosome;
https://www35.lamp.le.ac.uk/LOVD/lovd/hg19/NC_000002.11%3Ag.1671370494A%3EC/all/all/tx/primary?content-type=application%2Fjson

The VariantValidator returns output, but provides as a warning: "NC_000002.11:g.1671370494A>C: Variant reference (A) does not agree with reference sequence ()". Probably that warning could be improved, perhaps something like "Position 1671370494 is out of range for chromosome 2" or "Position 1671370494 is outside of NC_000002.11 boundaries".
https://rest.variantvalidator.org/VariantValidator/variantvalidator/hg19/NC_000002.11%3Ag.1671370494A%3EC/all?content-type=application%2Fjson

Thank you!

**Comment by PeteCausey-Freeman** [comment]
Thats weird. Thanks. I'll look into it

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commits/features closes for VV
```json
        "validation_warnings": [
            "The specified coordinate is outside the boundaries of reference sequence NC_000002.11"
```

**Comment by PeteCausey-Freeman** [comment]
Closes for VF
https://github.com/openvar/variantFormatter/commit/22c2aa30793926d2435f6d4ffee68fa0943f5b2e

```json
             "genomic_variant_error": "The specified coordinate is outside the boundaries of reference sequence NC_000002.11",
```

**Comment by PeteCausey-Freeman** [comment]
@ifokkema . Let me know when I can update the server. Thanks

**Comment by ifokkema** [comment]
Excellent, thanks! I've interrupted my testing for a bit so you can deploy :+1:

**Comment by PeteCausey-Freeman** [comment]
Should be live
