### ISSUE TITLE
VV API has `selected_assembly` set to `False` when variant is not 100% HGVS compliant.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#147]
I ran into the situation where `selected_assembly` was set to `False` when the HGVS description was not 100% correct, but understandable, for a certain variant that I sent through the VV API endpoint.

[NM_000088.3:c.589del](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/hg19/NM_000088.3%3Ac.589del/all?content-type=application%2Fjson) shows (selection of returned JSON):
```json
{
  "NM_000088.3:c.590del": {
    "hgvs_transcript_variant": "NM_000088.3:c.590del",
    "selected_assembly": false,
    "submitted_variant": "NM_000088.3:c.589del",
    "validation_warnings": [
      "NM_000088.3:c.589del automapped to NM_000088.3:c.590delG"
    ]
  }
}
```
[Correcting the variant](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/hg19/NM_000088.3%3Ac.590del/all?content-type=application%2Fjson) gives:

```json
{
  "NM_000088.3:c.590del": {
    "hgvs_transcript_variant": "NM_000088.3:c.590del",
    "selected_assembly": "hg19",
    "submitted_variant": "NM_000088.3:c.590del",
    "validation_warnings": []
  }
}
```
Since the variant is handled, just corrected, I suppose this field should be filled in normally. Especially because it's just a matter of taking the input. Correcting [ins to dup](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/hg19/NM_000088.3%3Ac.589_590insG/all?content-type=application%2Fjson) leaves the field set to `False` as well. But when I trigger a fatal warning, (like sending [delC](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/hg19/NM_000088.3%3Ac.589delC/all?content-type=application%2Fjson) instead of delG), it is correctly filled in.

Note that I don't need this field, so it's not directly relevant to me, but I do think this is a bug you'd probably want to look at at a certain point.

**Comment by PeteCausey-Freeman** [comment]
Thanks. It's defiantly a bug. I'll track it down and squash it.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/c80150a821b5f54a46a8b18cf9634d5f026a3999 closes
