### ISSUE TITLE
LOVD endpoint doesn't show a warning when delC deletes a G, instead.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#148]
The LOVD endpoint silently accepts a "delC" to delete a G, for instance in [NC_000017.10:g.1069645delC](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000017.10%3Ag.1069645delC/all/all/True/False?content-type=application%2Fjson). However, the VariantValidator endpoint _does_ complain in this case, like [NM_000088.3:c.589delC](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/hg19/NM_000088.3%3Ac.589delC/all?content-type=application%2Fjson). It would be more correct to have these endpoints behave the same way. Preferably, the LOVD endpoint would throw a similar error.

**Comment by PeteCausey-Freeman** [comment]
Agreed. It really should. I will update

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantFormatter/commit/4362fadc34b44fa7756edf817846869797b63747 closes
