### ISSUE TITLE
LOVD endpoint: return mitochondrial variants as with a m prefix instead of a g prefix.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#150]
As a reminder (see [recent comment](https://github.com/openvar/variantValidator/issues/134#issuecomment-610886758)), the LOVD endpoint returns mitochondrial variants with a g prefix instead of an m prefix, even if they're submitted with an m prefix. This only applies to the LOVD endpoint, the VV endpoint correctly uses the m prefix even if the g prefix was used as input.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantFormatter/commit/aba82c9030043dadf56ecfebbf59a405eb162ca6 closes
