### ISSUE TITLE
LOVD and VF endpoints: Internal Server Error upon sending transcript-based variant.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#153]
The [LOVD](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NM_002225.3%3Ac.100del/all/all/False/False?content-type=application%2Fjson) and [VF](https://www35.lamp.le.ac.uk/VariantFormatter/variantformatter/GRCh37/NM_002225.3%3Ac.100del/all/all/False?content-type=application%2Fjson) endpoints are meant for genomic variants. Sending transcript-based variants results in an Internal Server Error. Of course, this was invalid input, but returning a proper error, in this case, is better than failing hard leaving the user perhaps a bit clueless as to what happened.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantFormatter/commit/ecb3a3406ed43f6b1510fbc7b9e08ec480dd7280
closes
