### ISSUE TITLE
Add support for conversions

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#161]
Here's a challenge for you :wink: 

The following variant is HGVS compliant but currently is not supported by VV.
[NC_000017.10:g.41199848_41203626con41207680_41207915](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000017.10%3Ag.41199848_41203626con41207680_41207915/all/all/True/False?content-type=application%2Fjson). The delins equivalent also doesn't work.

Mutalyzer only handles the variant as a [delins](https://mutalyzer.nl/name-checker?description=NC_000017.10%3Ag.41199848_41203626delins41207680_41207915) and also doesn't support the `con` type. They do take quite long to complete the process.

Source: [LOVD](http://LOVD.nl/BRCA1_006085)

**Comment by PeteCausey-Freeman** [comment]
ooo fun. Thanks. Ill take a look

**Comment by PeteCausey-Freeman** [comment]
Hi @ifokkema 
I'm not entirely sure NC_000017.10:g.41199848_41203626delins41207680_41207915 is HGVS compliant.

I have a feeling it is in fact a conversion. ["a sequence change where, compared to a reference sequence, a range of nucleotides are replaced by a sequence from elsewhere in the genome"](http://varnomen.hgvs.org/recommendations/DNA/variant/conversion/)

I have started developing support for conversions etc, so I'm going to loop in Raymond before continuing so we can discuss.

**Comment by leicray** [comment]
I have to agree that his does look like a conversion rather than a deletion/insertion as it fully meets the definition of a conversion.

**Comment by ifokkema** [comment]
Hmmm.... But that's a replacement... As in, a deletion-insertion, right? I'm talking about an insertion... or is the [HGVS varnomen page](http://varnomen.hgvs.org/recommendations/DNA/variant/insertion/) out of date? Because it does mention this type of insertions.

**Comment by PeteCausey-Freeman** [comment]
The example provided is a delins though. 

Insertions sure, they can be handled this way. However the syntax is NC_000002.11:g.47643464_47643465ins[NC_000022.10:35788169_35788352]. 

delins such as the provided example ought to be a conversion I believe.

**Comment by PeteCausey-Freeman** [comment]
Although not clear I think NC_000002.11:g.47643464_47643465ins[35788169_35788352] is also correct and assumes the same reference sequence.

**Comment by ifokkema** [comment]
> The example provided is a delins though.

Sigh... sorry guys, I've been looking at strange variants all day the last few days and I'm starting to mix them. Yes, you're right of course. I'll update that variant into a conversion; this issue can be kept as a reminder for the insertion nomenclature.

> Although not clear I think NC_000002.11:g.47643464_47643465ins[35788169_35788352] is also correct and assumes the same reference sequence.

If the square brackets are mandatory, I suppose the HGVS nomenclature website is out of date?

**Comment by PeteCausey-Freeman** [comment]
Hi @ifokkema 

I'm going to open a support conversion issue too and reference here. Much of the code is developed, we just switched it off because it required more thought..

I'm not sure if the square brackets are required or not. I generally go by what is on the website. The example came from the website which you linked so I assume they are mandatory but I can't see why!!!

**Comment by leicray** [comment]
Square brackets are defined as having a specific meaning, as you might hope: [https://varnomen.hgvs.org/recommendations/general/](url).

The basic definition, slightly edited for clarity, is 

> square brackets are used for alleles which includes multiple inserted sequences at one position and insertions from a second reference sequence

However neither of these situations seems to apply here as the insertion/conversion is a **single** sequence that is derived from the **same** reference sequence. I would tentatively suggest that the square brackets are not required in this instance.

**Comment by ifokkema** [comment]
> I'm going to open a support conversion issue too and reference here. Much of the code is developed, we just switched it off because it required more thought..

Thanks! That's something I will run into anyway when I write the code to automatically correct that delins above.


> I'm not sure if the square brackets are required or not. I generally go by what is on the website. The example came from the website which you linked so I assume they are mandatory but I can't see why because they are not when specify conversions and also removing them would prevent confusion with Allele nomenclature. One for the working group I think.

It seems like the brackets are only used with there is an NC reference sequence included or when sequences of events are inserted. I only see your example there with an NC reference included; without it, the brackets seem to disappear (see other examples).

**Comment by PeteCausey-Freeman** [comment]
I don't see any need for them at all for insertions. My worry is that we will end up with situations where they are used for ins, not used for con and worst of all used deferentially in ins depending on where the bases are derived from. Total shambolic mess I'm afraid and difficult to support. My suggestion would be that the square brackets are completely redundant.

**Comment by PeteCausey-Freeman** [comment]
> It seems like the brackets are only used with there is an NC reference sequence included or when sequences of events are inserted. I only see your example there with an NC reference included; without it, the brackets seem to disappear (see other examples).

Which is my fear. Too many unnecessary rules. Thanks for the clarification here

**Comment by leicray** [comment]
For what it's worth, ponder the following.

It might be worth going back to first principles and considering way is meant by "gene conversion". Most commonly, it's "allelic gene conversion" that people immediately think of, but "non-allelic" or "ectopic" gene conversion can also occur. In the case of allelic gene conversion, the ALT allele would be expected to be the same length as the REF allele, but that that would not necessarily be the case for non-allelic or ectopic gene conversion.

In the example presented at the start of this issue, the deletion span is 41199848_41203626 (3779 nucleotides) and the insertion spans is 41207680_41207915 (236 nucleotides). Clearly this is not allelic gene conversion.

**Comment by ifokkema** [comment]
Upon some further investigation, it appears it gets more confusing considering the square brackets. [Converions never use square brackets](http://varnomen.hgvs.org/recommendations/DNA/variant/conversion/), even if the inserted sequence is indicated with a reference sequence.

This is going to be quite ugly code...

**Comment by PeteCausey-Freeman** [comment]
I think it's going to be quite ugly figuring out what the code ought to output and accept as well. Think we need some HGVS working group guidance.

**Comment by ifokkema** [comment]
Note, that the HGVS is considering dropping the `con` variant type in favor of te `delins`. See [SVD-WG009](http://varnomen.hgvs.org/bg-material/consultation/svd-wg009/).

**Comment by leicray** [comment]
I do not know of anybody in the nomenclature working group who thought that that might be a bad idea. It is now out for community consultation and I do not anticipate there being any objections.

Dropping the `con` variant type makes sense as the nomenclature is intended to support "report what you see" and not to speculate about the underlying mechanism that has produced the outcome.

**Comment by PeteCausey-Freeman** [comment]
I agree. It's a bit of an unnecessary over complication when delins will do. We shoudd use delins more to simplify the nomenclature

**Comment by PeteCausey-Freeman** [comment]
Thankfully, I already have most of the code written but switched off under con! ;P Luckily this is quite easy to handle, unlike other aspects of the nomenclature!!! Some of which I fear!!!!

**Comment by PeteCausey-Freeman** [comment]
Conversions now deprecated from the HGVS SVN,.

**Comment by ifokkema** [comment]
Sure, but the delins didn't work either;

> Then the issue becomes supporting the delins nomenclature for the insertion of ranges, like [NC_000017.10:g.41199848_41203626delins41207680_41207915](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000017.10%3Ag.41199848_41203626delins41207680_41207915/all/all/True/False?content-type=application%2Fjson) :sweat_smile:

And that's 100% HGVS though :wink:

Currently returning:
`NC_000017.10:g.41199848_41203626delins41207680_41207915: char 39: expected EOF`

**Comment by i3hsInnovation** [comment]
That's a different issue. Needs bringing up in the lovd alignment issues! 😂

**Comment by ifokkema** [comment]
Alright! I see it's not listed in the tested variants now; I'm also fixing some bugs on our side and will add a few more variants. When I'm done, I'll let you know!
