### ISSUE TITLE
VV returns Internal Server Error for special cases using the new NC_000017.10(NM_007294.3) format.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#168]
VV returns Internal Server Error for [NC_000017.10(NM_007294.3):c.(-20+1_-19-1)_4590del](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000017.10(NM_007294.3)%3Ac.(-20%2B1_-19-1)_4590del/all?content-type=application%2Fjson), while I expect a syntax error. If the [NC reference sequence is left out](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_007294.3%3Ac.(-20%2B1_-19-1)_4590del/all?content-type=application%2Fjson), I do get a syntax error, but with a very strange message, it contains an incomplete variant description.

An excerpt:
```json
{
  "validation_warning_1": {
    "submitted_variant": "NM_007294.3:c.(-20+1_-19-1)_4590del",
    "validation_warnings": [
      "NM_007294.3:c._4590del: char 14: expected one of (, *, or a digit"
    ]
  }
}
```

**Comment by PeteCausey-Freeman** [comment]
Currently uncertain positions are not supported because we have never been entirely sure what to do with them.

The error is a result of processing the description so I'm nit surprised it's odd.

Want to brain storm?

**Comment by PeteCausey-Freeman** [comment]
My feeling is that we can only really check syntax. There is little we can do about mapping between genome and transcript if provided with (? uncertainty.

However, in the given example, I wonder if we could create a genomic description at least. Should be doable.

**Comment by PeteCausey-Freeman** [comment]
@ifokkema can you deposit examples of uncertain positions in this issue please?

**Comment by ifokkema** [comment]
To be honest, I'm really just interested in getting rid of the total failure; a syntax error is, as I reported, expected output for me. There shouldn't be a difference in sending the NC or not; now I only get a syntax error when I send the NM without the NC; getting the same syntax error when sending the NC closes this issue for me :wink: 

Right now, a syntax error tells me the variant is unsupported. An internal server error confuses my poor code :grimacing:

**Comment by PeteCausey-Freeman** [comment]
For now then I might put in a generic uncertain positions are not supported error for you. Clean things up a bit.

**Comment by ifokkema** [comment]
Got another one; [NC_000017.10(NM_007294.3):c.?](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000017.10(NM_007294.3)%3Ac.%3F/all?content-type=application%2Fjson) versus [NM_007294.3:c.?](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_007294.3%3Ac.%3F/all?content-type=application%2Fjson). Internal Server Error in the first case, a useful syntax error in the latter case.

**Comment by ifokkema** [comment]
I have another one; [NC_000017.10(NM_007294.3):c.1911T](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000017.10(NM_007294.3)%3Ac.1911T/all?content-type=application%2Fjson), should also generate a syntax error rather than an internal server error.

**Comment by ifokkema** [comment]
Thank you, works like a charm! :+1:
