### ISSUE TITLE
merging adjacent variant descriptions

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#17]
The HGVS nomenclature allows variants at adjacent nucleotides to be merged into a single variant description. For example, the variant description NM_000492.3:c.[1075C>A;1076A>G] could be resolved into the more parsimonious description NM_000492.3:c.1075_1076delinsAG

Could this be implemented as an **additional** output?

**Comment by PeteCausey-Freeman** [comment]
Closing as this has been updated with https://github.com/openvar/variantValidator/issues/76
