### ISSUE TITLE
Internal Server Error in VV for variants located on NM_000059.3:c.7397

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#176]
There seems to be a very local issue with NM_000059.3:c.7397 (BRCA2).

Variants _before_ this location [work fine](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000013.10(NM_000059.3)%3Ac.7396del/all?content-type=application%2Fjson); variants _on exactly_ this position all fail [del](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000013.10(NM_000059.3)%3Ac.7397del/all?content-type=application%2Fjson), [sub](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000013.10(NM_000059.3)%3Ac.7397C%3ET/all?content-type=application%2Fjson), [dup](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000013.10(NM_000059.3)%3Ac.7397dup/all?content-type=application%2Fjson)) with an internal server error, variants _after_ it [work just fine](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000013.10(NM_000059.3)%3Ac.7398del/all?content-type=application%2Fjson), too.

Any thoughts?

**Comment by PeteCausey-Freeman** [comment]
Can you provide some examples. I'll check it out. Wierd one!

**Comment by ifokkema** [comment]
Examples are all already provided, see the links in my initial report :wink:

**Comment by PeteCausey-Freeman** [comment]
Ah, I see. Thanks.

Trouble shooting something annoying then on it

**Comment by ifokkema** [comment]
I just realized this error only occurs when the NC is passed, like `NC_000013.10(NM_000059.3):c.7397C>T`. When leaving out the NC and only sending the variant like `NM_000059.3:c.7397C>T`, VV returns normal output. Perhaps this helps?

**Comment by ifokkema** [comment]
OK, I think I see the pattern now. [NC_000023.10(NM_004006.2):c.8810A>G](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000023.10(NM_004006.2)%3Ac.8810A%3EG/all?content-type=application%2Fjson) has the same problem. **In both cases, the transcript and the NC differ in their sequence at this position.**

**Comment by PeteCausey-Freeman** [comment]
OOO, this sounds like an interesting issue. I'll take a look. Cheers

**Comment by PeteCausey-Freeman** [comment]
Looking at this now because it is more fun :)

**Comment by PeteCausey-Freeman** [comment]
Closing this. The next push will add the code corrections automatically. Thanks for the detailed investigation Ivo. Made my life easy

**Comment by ifokkema** [comment]
Excellent! I'm glad it helped! :smile:
