### ISSUE TITLE
Variant reference warnings come in trios when using the NC(NM) format in the VV endpoint.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#177]
Variant reference warnings are normally [given using a single warning](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_007294.3%3Ac.1911C%3EA/all?content-type=application%2Fjson):
```json
{
  "flag": "warning",
  "validation_warning_1": {
    "submitted_variant": "NM_007294.3:c.1911C>A",
    "validation_warnings": [
      "NM_007294.3:c.1911C>A: Variant reference (C) does not agree with reference sequence (T)"
    ]
  }
}
```

But when using the new NC(NM) format in the VV endpoint, [we suddenly get three warnings](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000017.10(NM_007294.3)%3Ac.1911C%3EA/all?content-type=application%2Fjson):

```json
{
  "flag": "warning",
  "validation_warning_1": {
    "submitted_variant": "NC_000017.10(NM_007294.3):c.1911C>A",
    "validation_warnings": [
      "Required information for NM_007294.3 is missing from the Universal Transcript Archive",
      "Query gene2transcripts with search term NM_007294 for available transcripts",
      "NM_007294.3:c.1911C>A: Variant reference (C) does not agree with reference sequence (T)"
    ]
  }
}
```

I think the first two warnings are misleading, and I'd like to skip them. I can do this on my end for LOVD, but I think you might want to get rid of them as well? :grimacing:

**Comment by PeteCausey-Freeman** [comment]
Closing. Code changes will be linked at next push

**Comment by ifokkema** [comment]
Thank you! :smile:
