### ISSUE TITLE
New "Length implied by coordinates must equal sequence deletion length" error triggered falsely.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#185]
I'm afraid something went wrong in today's update.

While investigating the limits of VV (because `NC_000023.10(NM_004006.2):c.6615-650_7660+528del` was failing), I tried making the variant smaller and tried [`NC_000023.10(NM_004006.2):c.6615_7660del`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000023.10(NM_004006.2)%3Ac.6615_7660del/all?content-type=application%2Fjson). This strangely triggered the new "Length implied by coordinates must equal sequence deletion length" error;

```json
{
  "flag": "warning",
  "validation_warning_1": {
    "submitted_variant": "NC_000023.10(NM_004006.2):c.6615_7660del",
    "validation_warnings": [
      "This coding sequence variant description spans at least one intron",
      "Use of the corresponding genomic sequence variant descriptions may be invalid. Please refer to http://variantvalidator.org/recommendations/",
      "Length implied by coordinates must equal sequence deletion length"
    ]
  }
}
```
It also triggered one or two other warnings that I don't understand.

On a related note; it seems warnings are sometimes split when the line gets too long, but this makes the JSON seem to return multiple warnings. I'm not even sure if the above JSON contains 2 or 3 warnings. Is there a reason for this?

**Comment by PeteCausey-Freeman** [comment]
It's something else triggering it. Looking into it now. Wierd one

**Comment by PeteCausey-Freeman** [comment]
Note
> NC_000023.10(NM_004006.2):c.6615-650_7660+528del

Fails due to the size as predicted. Cross referencing with https://github.com/openvar/variantValidator/issues/151 as a use-case for additional speed improvements. Still in progress.

**Comment by PeteCausey-Freeman** [comment]
OK sorted the issue, will close at next push in the knowledge that I'm still working on speed boosts for large structural variants

**Comment by ifokkema** [comment]
Thanks!

Can you tell me what the other two warnings (or is it one warning?) mean?
```json
{
  "validation_warnings": [
    "This coding sequence variant description spans at least one intron",
    "Use of the corresponding genomic sequence variant descriptions may be invalid. Please refer to http://variantvalidator.org/recommendations/"
  ]
}
```

That link is broken, but it seems that statement should maybe not apply since I passed the variant with an NC?

Also, you seem to have left in some [debugging statements](https://github.com/openvar/variantValidator/commit/f52f613db1707c0693aa9a3f1a47a70a9cfd20b6#diff-8f2fdd70e94ca7d08c9c2514f31b928f) in that commit :wink:

**Comment by PeteCausey-Freeman** [comment]
Damn it. Thought I had removed those lol!!!

Ah well. 

This coding sequence variant description spans at least one intron is just a warning that the variant spans introns as stated. I will remove the other I think. Don't see the need for it since we removed the recommendations page
