### ISSUE TITLE
Difference in protein prediction between NC and NC(NM) based variants.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#187]
Sending NC variants into the LOVD endpoint provides a sometimes different protein prediction than sending its NC(NM) counterpart into the VV endpoint. Examples are [`NC_000023.10:g.31837231_31910999delinsGGG`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000023.10%3Ag.31837231_31910999delinsGGG/all/NM_004006.2/False/False?content-type=application%2Fjson), which provides `p.?` as protein prediction, versus [`NC_000023.10(NM_004006.2):c.6913-17508_7309+861delinsCC`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000023.10(NM_004006.2)%3Ac.6913-17508_7309%2B861delinsCC/all?content-type=application%2Fjson), which provides `p.(?)` protein prediction. These have different meanings, and I argue `p.?` should be returned here.

> p.?
used to indicate that an effect on the protein level is expected but that it is not possible to give a reliable prediction of the consequences

> p.(?)
used to indicate that no changes on the protein level are expected other than those simply derived from the change at the DNA level. Alternatively the predicted consequence at the protein level can be described, e.g. p.(Arg2371Ser)

**Comment by PeteCausey-Freeman** [comment]
We are limited on options here. I recently updated VV to be always (?) but forgot to do this for LOVD and VF. Both can always return one or the other. I really don't have a preference so would you prefer ? rather than (?) ?

**Comment by ifokkema** [comment]
They have different meanings, so they're not exchangeable. What do you mean with "always return one or the other"? In which cases? Since `p.(?)` is an alternative for things like `p.Gln2418_Ile2434del)`, I don't really see why users would prefer `p.(?)` over an actual prediction. But `p.?` can not be replaced by anything else, it means "we're not sure what's going to happen".

**Comment by PeteCausey-Freeman** [comment]
I have had users argue counter to you :)

I agree with your statements but we can really only support one or the other. My preference was always p.? but again other users have complained. I think p.? makes the most sense

**Comment by ifokkema** [comment]
What is the use case for `p.(?)`, in which situations can it be used, and what is the meaning that these users give to this value?

**Comment by PeteCausey-Freeman** [comment]
I assume preference, as I said, I argued for p.? because to me we predict we don't know what's going on makes no sense. why predict that we don't know whats going on :).

I'll revert

**Comment by ifokkema** [comment]
Thanks :grin: 

Also since `p.(?)` doesn't even mean that we predict that we don't know what's going on (hence my earlier question - what do they think it means?), it's indeed better to revert :sweat_smile:

**Comment by PeteCausey-Freeman** [comment]
Done, Closing

**Comment by ifokkema** [comment]
Thank you! :smile: 

(and if somebody ever complains about it, feel free to refer them to me :laughing: )

**Comment by PeteCausey-Freeman** [comment]
I will hold you to that :P
