### ISSUE TITLE
"base start position must be <= end position" error on variant mismatching with the NC.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#193]
I've got another interesting case for you; the ABO gene contains a frameshift mismatch between the NC and the NM. VV handles this only NC to NM, but not the other way around.

[`NC_000009.11:g.136132908_136132909=`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000009.11%3Ag.136132908_136132909%3D/all/all/False/primary?content-type=application%2Fjson) is handled beautifully (kudos!) by the LOVD endpoint and results in `NM_020469.2:c.261del`, with a good warning included. However, when sending [`NC_000009.11(NM_020469.2):c.261del`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000009.11(NM_020469.2)%3Ac.261del/all?content-type=application%2Fjson) back into the VV endpoint, I get a "base start position must be <= end position" validation warning.

I'm thinking it's probably a quick fix...?

**Comment by PeteCausey-Freeman** [comment]
Developing this code has been a nightmare, but hopefully this can be a quick fix. I'll look. Thanks for the heads up.

What's nice about the way I developed this code is that even of the alignment changes, the code scans for gaps and tries to deal with them, so pre-knowledge of where the gap is is not required

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/1878e916ad86afaea7c733ff00424aab10c5b265
closes
