### ISSUE TITLE
Uncertain DNA changes with certain positions currently not supported.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#194]
Uncertain DNA changes with certain positions are currently not supported, but they could quite easily be processed.

See, for instance, the first Q&A on this page of the [HGVS nomenclature site](http://varnomen.hgvs.org/recommendations/DNA/variant/substitution/), mentioning `c.(76A>G)` as valid syntax. It's also used to indicate variants mapped from animal models.

However, sending [NC_000015.10(NM_002225.3):c.(1222_1278del)](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000015.10(NM_002225.3)%3Ac.(1222_1278del)/all?content-type=application%2Fjson) to the VV endpoint results in `Uncertain positions are not currently supported`, which is not a correct error message; the positions are not uncertain.

**Comment by PeteCausey-Freeman** [comment]
The nomenclature is a total mess :). AAAARGH, Ok, thanks for the heads up. I'll sort it :)

**Comment by PeteCausey-Freeman** [comment]
Coding again this week

**Comment by ifokkema** [comment]
This still applies - but please don't stress over it! :wink:

**Comment by PeteCausey-Freeman** [comment]
moved to https://github.com/openvar/variantValidator/issues/328
