### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#200]
https://github.com/openvar/rest_variantValidator/issues/30#issuecomment-641895447

**Comment by AnotherSimon** [comment]
another variant to add to the list:
`11:32456388:GA:TC`
(GRCh37)

Hope you have the means and the motivation to keep perfecting this tool. The utility is beyond question and I hope the grant bodies realize this.

**Comment by PeteCausey-Freeman** [comment]
Perfect, thanks mate. Really appreciate these. Also thanks for the comments. Yep, we are actively developing at the moment and grant applications are coming up. Might get you to provide a quote 

Thanks

**Comment by PeteCausey-Freeman** [comment]
I'll admit it's a bit slow currently though due to teaching commitments, but I'm on it :)

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon 

Gonna tackle these today. Sorry for the delay.

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon So there are multiple issues here. The one above requires an extended Alphabet. The gene translates from a CTG codon not ATG.
see 
https://github.com/openvar/variantValidator/commit/e16a73d7fa709bf43caea79f32f587570b44dbae

**Comment by PeteCausey-Freeman** [comment]
Now looking at datum issue
