### ISSUE TITLE
Variants shifted into the intron don't have a correct protein prediction.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#203]
Variants shifted into the intron because of the 3' aligning rule, like [`NC_000003.11(NM_198056.2):c.4435_4437del`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000003.11(NM_198056.2)%3Ac.4435_4437del/all?content-type=application%2Fjson), get protein predictions as if they're still in the exon. In this case, this variant is normalized to `NC_000003.11(NM_198056.2):c.4436_4437+1del`, but still has `NP_932173.1(LRG_289p1):p.(Lys1479del)` as a protein prediction. Resubmitting the variant it normalizes to, [changes the protein prediction to `p.?`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000003.11(NM_198056.2)%3Ac.4436_4437%2B1del/all?content-type=application%2Fjson).

**Comment by ifokkema** [comment]
Note, this is the VV endpoint, not the LOVD endpoint.

Another example from the same gene: [`NC_000003.11(NM_198056.2):c.3666del`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000003.11(NM_198056.2)%3Ac.3666del/all?content-type=application%2Fjson).

**Comment by PeteCausey-Freeman** [comment]
Aware of this one. It's already on the to-do list, but thanks for adding the issue.

**Comment by ifokkema** [comment]
Hi Pete, did you update the test instance? My examples still return the wrong protein descriptions.

**Comment by PeteCausey-Freeman** [comment]
I will admit that I forgot! oops. Doing it now, sorry :)

**Comment by PeteCausey-Freeman** [comment]
Today is a service day, I'll update later when the servers are up again. Sorry

**Comment by ifokkema** [comment]
> Today is a service day, I'll update later when the servers are up again. Sorry

No problem whatsoever! I'm super busy anyway, just now and then I check the status of all the issues that I opened :sweat_smile: 
Cheers!

**Comment by PeteCausey-Freeman** [comment]
Yeah, a bit slow currently due to grants and teaching. Roll on Summer! :)
