### ISSUE TITLE
Sending transcripts (select_transcripts variable) can slow down mapping a lot.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#204]
Perhaps related to #155; I'm hitting strange timeouts in some requests, depending on what transcripts I'm sending through.

----

_In short, an example request takes ~25 seconds when *not* sending any transcripts, and it returns six transcripts. When sending six transcripts that VV can *not* map on, the time of the request *increases* to one minute. Sending more will make VV fail._

----

When using the LOVD endpoint to check, map, and liftover a genomic variant, VV often returns various transcripts that the variant maps on. In an effort to speed things up, LOVD sends only the transcripts that it already stores on the variant, assuming this number is smaller than the number of transcripts that VV would otherwise return. Sometimes the opposite is true; LOVD contains many mappings from Mutalyzer that VV doesn't make as the position lays outside the transcript boundaries. LOVD can not know the difference before the request, so I can't fully fix this on my side.

There's a [~1M region on chromosome 5](https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chr5%3A140119629-140936771) where many different transcripts overlap, and where LOVD stores many mappings because of Mutalyzer's mapping. Currently, LOVD calls to VV for this entire region fail because of these delays.

#### Examples, all using `NC_000005.9:g.140166772A>G`

- [`Not sending any transcripts`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/all/False/primary?content-type=application%2Fjson) takes some ~25 seconds. VV returns 6 transcripts.
- [`Sending six transcript, that VV does NOT map on`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/NM_018901.2%7CNM_018902.3%7CNM_018903.2%7CNM_018904.2%7CNM_018905.2%7CNM_018906.2/False/primary?content-type=application%2Fjson) takes some ~1 minute. VV returns 6 failures.
- [`Sending all I have on this variant (15 transcripts)`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/NM_018898.3%7CNM_018899.5%7CNM_018900.2%7CNM_018901.2%7CNM_018902.3%7CNM_018903.2%7CNM_018904.2%7CNM_018905.2%7CNM_018906.2%7CNM_018907.2%7CNM_018908.2%7CNM_018909.2%7CNM_018910.2%7CNM_018911.2%7CNM_031857.1/False/primary?content-type=application%2Fjson) fails with a timeout.

Perhaps there's a way to speed up handling the transcripts that don't map. Somehow it slows down the mapping more than a transcript that *does* map. Or perhaps VV first handles all transcripts, and only *then* starts selecting. I think I might disable the feature that sends transcripts over if I have more than 5 or so, because then the chance that one or more of these won't work is much higher.

**Comment by ifokkema** [comment]
This also still applies, although it's a bit faster now (20 seconds / 40 seconds / fail).

**Comment by PeteCausey-Freeman** [comment]
Wonder if this helped https://github.com/openvar/variantValidator/issues/372

**Comment by ifokkema** [comment]
> Wonder if this helped #372

Let's see!

> This also still applies, although it's a bit faster now (20 seconds / 40 seconds / fail).

Now down to 16 sec, 32 sec, and failure after one minute. So things are a bit faster, but the root of the problem (something internally) hasn't been fixed.

**Comment by PeteCausey-Freeman** [comment]
Can you send the tests you use. Will take a look Thanks. Glad its improving

**Comment by ifokkema** [comment]
They're in the original post. I just changed the server to rest.variantvalidator.org. I'll repeat them here;

#### Examples, all using `NC_000005.9:g.140166772A>G`

* [`Not sending any transcripts`](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/all/False/primary?content-type=application%2Fjson) takes some ~16 seconds. VV returns 6 transcripts.

* [`Sending six transcript, that VV does NOT map on`](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/NM_018901.2%7CNM_018902.3%7CNM_018903.2%7CNM_018904.2%7CNM_018905.2%7CNM_018906.2/False/primary?content-type=application%2Fjson) takes some ~32 seconds. VV returns 6 failures.

* [`Sending all I have on this variant (15 transcripts)`](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/NM_018898.3%7CNM_018899.5%7CNM_018900.2%7CNM_018901.2%7CNM_018902.3%7CNM_018903.2%7CNM_018904.2%7CNM_018905.2%7CNM_018906.2%7CNM_018907.2%7CNM_018908.2%7CNM_018909.2%7CNM_018910.2%7CNM_018911.2%7CNM_031857.1/False/primary?content-type=application%2Fjson) fails with a timeout.

**Comment by PeteCausey-Freeman** [comment]
OK @ifokkema Try AGAIN now pls. Should be quicker

I think https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/NM_018901.2%7CNM_018902.3%7CNM_018903.2%7CNM_018904.2%7CNM_018905.2%7CNM_018906.2/False/primary?content-type=application%2Fjson is not 5 to 10 sec

**Comment by ifokkema** [comment]
Thanks Pete!
Additionally, I just discovered that the query changes from 6 seconds to 0.3 seconds if the Ensembl transcripts are removed. I couldn't narrow it down to one specific Ensembl transcript, they're all just very slow. They also return an error: `TranscriptMapper(tx_ac=ENST00000378133.3, alt_ac=NC_000005.9, alt_aln_method=splign): No transcript exons`. Perhaps this causes the slowness as it falls back to PyLiftover. Turning off the liftover speeds up the request to 0.3 sec. Not sure if you want to do something with that error, but I'm fine working with RefSeq only.

- [All transcripts, 6 seconds](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/all/False/primary?content-type=application%2Fjson)
- [Only RefSeq transcripts, 0.3 seconds](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/refseq/all/False/primary?content-type=application%2Fjson)
- [Just one Ensembl transcript, 5.8 seconds](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/ENST00000378133.3/False/primary?content-type=application%2Fjson)
- [Just one Ensembl transcript, turned off liftover, 0.3 seconds](https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000005.9%3Ag.140166772A%3EG/all/ENST00000378133.3/False/False?content-type=application%2Fjson)

**Comment by PeteCausey-Freeman** [comment]
Ah, I forgot about this. 

As of the last database build etc, you need to now state refseq. I forgot we now had Ensembl data in the correct format so it will attempt to process, but is not currently correctly plugged in.


I will open this as a to-do.

**Comment by PeteCausey-Freeman** [comment]
Closing for now but we can re-open
