### ISSUE TITLE
Inversions that don't change the protein description return `p.=`.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#207]
Inversions that don't change the protein description return `p.=`, but since this is a protein prediction, there should be parentheses. A better option would be `p.(=)`, or a more specific description like otherwise given (`p.(Ala394=)`).

Example: [`NC_000002.11:g.179659709_179659712inv`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000002.11%3Ag.179659709_179659712inv/all/NM_003319.4/False/False?content-type=application%2Fjson) returns (cleaned JSON):

```json
{
  "NC_000002.11:g.179659709_179659712inv": {
    "NC_000002.11:g.179659709_179659712inv": {
      "g_hgvs": "NC_000002.11:g.179659709_179659712inv",
      "hgvs_t_and_p": {
        "NM_003319.4": {
          "p_hgvs_slc": "NP_003310.4:p.=",
          "p_hgvs_tlc": "NP_003310.4:p.=",
          "t_hgvs": "NM_003319.4:c.1182_1185inv",
        }
      }
    }
  }
}
```

When I enforce the protein not to be changed by submitting [a WT allele](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000002.11%3Ag.179659709_179659712%3D/all/NM_003319.4/False/False?content-type=application%2Fjson), VV returns `p.(Ala394=)`.

```json
{
  "NC_000002.11:g.179659709_179659712=": {
    "NC_000002.11:g.179659709_179659712=": {
      "g_hgvs": "NC_000002.11:g.179659709_179659712=",
      "hgvs_t_and_p": {
        "NM_003319.4": {
          "p_hgvs_slc": "NP_003310.4:p.(A394=)",
          "p_hgvs_tlc": "NP_003310.4:p.(Ala394=)",
          "t_hgvs": "NM_003319.4:c.1182_1185=",
        }
      }
    }
  }
}
```

**Comment by ifokkema** [comment]
Another example is `NC_000001.10:g.26140612_26140626delinsT`. Not an inversion, so I don't know what's causing this.

**Comment by PeteCausey-Freeman** [comment]
Just so I'm clear. In all these examples should p.= be correct but amended to p.(=)?

Is there a use case you can think of where p.= would be correct. Personally I don't because even UTR variants might cause a protein effect. Cheers @ifokkema

**Comment by PeteCausey-Freeman** [comment]
Also, is p.(Ala394=) OK or were you thinking it should be p.Ala394= in that example? Cheers

**Comment by ifokkema** [comment]
The inversion's VCF fields GGCA:TGCC and the cDNA positions (c.1182_1185) indicate only the two codon's wobble bases are affected, so without looking at the protein translation tables, I'll believe that's a `p.(=)`, or `p.(Ala394=)` if you will.

The `delinsT` is probably a whole different story, so maybe I should have created a separate issue, sorry. It does return a `p.=` so I included it here, but it's also a delins on the transcript level, removing 14 bases in total so it should cause a frameshift. If you want, I can report it separately.

**Comment by ifokkema** [comment]
> Is there a use case you can think of where p.= would be correct.

Nah, all of this is a prediction. Only when RNA has been verified, can one claim `p.=`.

> Also, is p.(Ala394=) OK or were you thinking it should be p.Ala394= in that example?

`p.(Ala394=)` is more in line with your other predictions than `p.(=)` - I don't actually think you're using `p.(=)` anywhere, are you? And also here, we need the parentheses because it's a prediction.

**Comment by PeteCausey-Freeman** [comment]
Thanks @ifokkema . The hgvs package for Protein descriptions has required a lot of extending. I'll sort this issue to ease my brain back into programming when I finally get the chance :)

I intend to always use ( ) for p. descrions then because I see no reason not to!

**Comment by ifokkema** [comment]
Perfect, thanks!

**Comment by PeteCausey-Freeman** [comment]
OK, on my dev system, NC_000002.11:g.179659709_179659712inv now returns p.(=). Gonna see if I can figure out returning (A394=). Inversions are not well handled by hgvs so this is my code I think.

**Comment by PeteCausey-Freeman** [comment]
OK,

So, I've updated the code but I have a query

```json
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "slr": "",
            "tlr": "NP_597681.4:p.(Ala394Ala395=)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "NM_133437.4:c.1182_1185inv",
```
Note, the position of the inversion covers 2 amino acids. My tendancy for p.= would be to query the range under the entire c. edit range. 

So I'm gonna commit this. If not happy let me know @ifokkema

**Comment by PeteCausey-Freeman** [comment]
On the upside, Mutalyzer gives NM_133437.4(TTN_i001):p.(=) which is a total mess

**Comment by PeteCausey-Freeman** [comment]
Running tests and updating with an example. I suspect we may have a failure or 2 that need to be edited

**Comment by PeteCausey-Freeman** [comment]
OOPs forgot the _ on it!

```json
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "slr": "NP_597681.3:p.(A394_A395=)",
            "tlr": "NP_597681.3:p.(Ala394_Ala395=)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "NM_133437.3:c.1182_1185inv",
```

**Comment by PeteCausey-Freeman** [comment]
Closed with
https://github.com/openvar/variantValidator/commit/a50e2ce2bc957f437dc9c1e4c26801e677bdd7b6

**Comment by ifokkema** [comment]
> Note, the position of the inversion covers 2 amino acids. My tendancy for p.= would be to query the range under the entire c. edit range.

I think it's a great idea to show which area is affected (or actually, not affected), so it looks great!


> On the upside, Mutalyzer gives NM_133437.4(TTN_i001):p.(=) which is a total mess

It usually is :sweat_smile: 

Thank you!!!
