### ISSUE TITLE
Expanding covered terms. 

### ISSUE THREAD

**Issue by peq123** [openvar/variantValidator#213]
Hi @PeteCausey-Freeman,

NM_007294.3:c.5552_5553AC[1] isn't recognised by variant validator. Could you please include it if possible along with the merging adjacent variants into single descriptions as described here https://github.com/openvar/variantValidator/issues/76 

peq123

**Comment by PeteCausey-Freeman** [comment]
The only reason I'm not covering this as yet is that this nomenclature is currently under review by the HGVS SVD. I'll keep this open though for when they reach a decision

**Comment by PeteCausey-Freeman** [comment]
lifts to https://github.com/openvar/variantValidator/issues/328
