### ISSUE TITLE
Inconsistency in protein predictions which insert a Ter.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#214]
There is some inconsistency in protein predictions that insert a Ter. When a new sequence on the DNA level introduces additional amino acids on the protein level that include a Ter, the software can make a choice on how to describe this on the protein level. If the inserted Ter is considered the protein's end, the variant could be described as a large deletion on the protein level. Mutalyzer does this always, VV does this sometimes. However, that's not [what the HGVS recommends](http://varnomen.hgvs.org/recommendations/protein/variant/insertion/).

Examples where VV does it right:
- [`NC_000001.10:g.39549918_39549919insAGTGAGCGGTCATGTCGG`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000001.10%3Ag.39549918_39549919insAGTGAGCGGTCATGTCGG/all/NM_012090.5/False/False?content-type=application%2Fjson).
Result on cDNA: `NM_012090.5:c.28_29insAGTGAGCGGTCATGTCGG`.
Mutalyzer: `p.(Ser10_Arg5430delinsLys)` :red_circle: 
VV: `p.(Ser10delinsLysTerAlaValMetSerGly)` :green_circle: 

- [`NC_000012.11:g.110765502_110765503insCAGCTT`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000012.11%3Ag.110765502_110765503insCAGCTT/all/NM_170665.3/False/False?content-type=application%2Fjson).
Result on cDNA: `NM_170665.3:c.775_776insCAGCTT`
Mutalyzer: `p.(Gln259_Ser1042delinsProAla)` :red_circle: 
VV: `p.(Gln259delinsProAlaTer)` :green_circle: 

But then, VV suddenly decides to join Mutalyzer:
- [`NC_000016.9:g.3900957delinsCAGCTCATGATGA`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000016.9%3Ag.3900957delinsCAGCTCATGATGA/all/NM_004380.2/False/False?content-type=application%2Fjson).
Result on cDNA: `NM_004380.2:c.139delinsTCATCATGAGCTG`
Mutalyzer: `p.(Asn47_Leu2442delinsSerSer)` :red_circle: 
VV: `p.(Asn47_Leu2442delinsSerSer)` :red_circle: 

It looks like some logic is skipped in some cases, perhaps it's the `delins` vs `ins`?

**Comment by PeteCausey-Freeman** [comment]
Thanks. Told you that the p. stuff could be a work in progress! :)
On it ASAP. Bad one this!

**Comment by PeteCausey-Freeman** [comment]
> p.(Asn47_Leu2442delinsSerSer)

If this is incorrect, what is correct? I would assume that this is the shortest result from NM_004380.2:c.139delinsTCATCATGAGCTG but I will look closer

**Comment by ifokkema** [comment]
> > p.(Asn47_Leu2442delinsSerSer)
> 
> If this is incorrect, what is correct? I would assume that this is the shortest result from NM_004380.2:c.139delinsTCATCATGAGCTG but I will look closer

Manually trying to build the protein description, I get to "p.(Asn47delinsSerSerTerAlaAsp)".

Oh, yours is the shortest one indeed, but deleting the whole protein while you're in-frame inserting a Ter is not the correct description. [The HGVS recommendations](http://varnomen.hgvs.org/recommendations/protein/variant/insertion/) say:

> p.(Met3_His4insGlyTer)
> the predicted consequence at the protein level of an insertion at the DNA level (c.9_10insGGGTAG) is the insertion of GlyTer (alternatively Gly*)
> **NOTE: this is not described as p.(Met3_Ile3418delinsGly), a deletion-insertion replacing the entire C-terminal protein coding sequence downstream of Met3 with a Gly)**

**Comment by PeteCausey-Freeman** [comment]
So, to clarify, I think p.(Asn47_Leu2442delinsSerSer) is right and Mutayzer would agree. I see no reason to add the Ter necessarily but no objection. What do you think.

I'll sort out p.(Ser10delinsLysTerAlaValMetSerGly). OOPS!

**Comment by PeteCausey-Freeman** [comment]
Note, these
>p.(Met3_His4insGlyTer)
the predicted consequence at the protein level of an insertion at the DNA level (c.9_10insGGGTAG) is the insertion of GlyTer (alternatively Gly*)

are ins the example you provided is delins so I think p.(Asn47_Leu2442delinsSerSer) makes more sense

**Comment by PeteCausey-Freeman** [comment]
OK,

So for NC_000001.10:g.39549918_39549919insAGTGAGCGGTCATGTCGG
```json
        "hgvs_predicted_protein_consequence": {
            "slr": "NP_036222.3:p.(S10delinsK*)",
            "tlr": "NP_036222.3:p.(Ser10delinsLysTer)"
        },
```

**Comment by PeteCausey-Freeman** [comment]
NC_000012.11:g.110765502_110765503insCAGCTT

```json
        "hgvs_predicted_protein_consequence": {
            "slr": "NP_733765.1:p.(Q259delinsPA)",
            "tlr": "NP_733765.1:p.(Gln259delinsProAla)"
        },
```

**Comment by PeteCausey-Freeman** [comment]
Updating tests

**Comment by ifokkema** [comment]
Good morning!

I'm afraid we're having a little misunderstanding...

> So, to clarify, I think p.(Asn47_Leu2442delinsSerSer) is right and Mutayzer would agree. I see no reason to add the Ter necessarily but no objection. What do you think.

The HGVS nomenclature specifies that when a DNA delins or ins variant introduces a Ter, you should write the protein description as if the Ter was just another amino acid. It says *NOT* to describe a deletion of the entire protein, like the example above. Examples from the HGVS nomenclature sites (protein/insertion and protein/delins pages):
**p.(Met3_His4insGlyTer)
p.(Pro578_Lys579delinsLeuTer)**


> I'll sort out p.(Ser10delinsLysTerAlaValMetSerGly). OOPS!

Why? That is correct, it shouldn't change. That's why I wrote that it's the correct answer...


> Note, these
> 
> > p.(Met3_His4insGlyTer)
> > the predicted consequence at the protein level of an insertion at the DNA level (c.9_10insGGGTAG) is the insertion of GlyTer (alternatively Gly*)
> 
> are ins the example you provided is delins so I think p.(Asn47_Leu2442delinsSerSer) makes more sense

The delins page has a delins example; p.(Pro578_Lys579delinsLeuTer). So the above Mutalyzer description is *not* correct.


> So for NC_000001.10:g.39549918_39549919insAGTGAGCGGTCATGTCGG
> 
> ```json
>         "hgvs_predicted_protein_consequence": {
>             "slr": "NP_036222.3:p.(S10_R5430delinsK)",
>             "tlr": "NP_036222.3:p.(Ser10_Arg5430delinsLys)"
>         },
> ```

Please change that back :sweat_smile: 


> NC_000012.11:g.110765502_110765503insCAGCTT
> 
> ```json
>         "hgvs_predicted_protein_consequence": {
>             "slr": "NP_733765.1:p.(Q259_S1042delinsPA)",
>             "tlr": "NP_733765.1:p.(Gln259_Ser1042delinsProAla)"
>         },
> ```

This also; please change it back :sweat_smile:  It was the example of where VV was doing it *right*, not what needed to be changed...

**Comment by PeteCausey-Freeman** [comment]
Ah, my misubnderstanding. Haha. On it

**Comment by PeteCausey-Freeman** [comment]
Oh, I see whats happened, the renderin on ticks has gone wrong! Haha

**Comment by PeteCausey-Freeman** [comment]
So I'm gonna try for "p.(Asn47delinsSerSerTer)" from NC_000016.9:g.3900957delinsCAGCTCATGATGA

**Comment by PeteCausey-Freeman** [comment]
OK so currently the code is looking for the shortest description, so in terms of in-fame the logic is sound, but we can certainly change this format.

**Comment by PeteCausey-Freeman** [comment]
OK so we now have

1. NC_000016.9:g.3900957delinsCAGCTCATGATGA
```json
        "hgvs_predicted_protein_consequence": {
            "slr": "NP_004371.2:p.(N47delinsSS*)",
            "tlr": "NP_004371.2(LRG_1426p1):p.(Asn47delinsSerSerTer)"
        },
```

2. NC_000001.10:g.39549918_39549919insAGTGAGCGGTCATGTCGG
```json
        "hgvs_predicted_protein_consequence": {
            "slr": "NP_036222.3:p.(S10delinsK*)",
            "tlr": "NP_036222.3:p.(Ser10delinsLysTer)"
        },
```

3. NC_000012.11:g.110765502_110765503insCAGCTT
```json
        "hgvs_predicted_protein_consequence": {
            "slr": "NP_733765.1:p.(Q259delinsPA*)",
            "tlr": "NP_733765.1:p.(Gln259delinsProAlaTer)"
        },
```

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/6ee9f761599616e922f4c259988457c754d31865

**Comment by ifokkema** [comment]
> Oh, I see whats happened, the renderin on ticks has gone wrong! Haha

Oops :( What can I do next time to improve the clarity of the report?

> So I'm gonna try for "p.(Asn47delinsSerSerTer)" from NC_000016.9:g.3900957delinsCAGCTCATGATGA

I think that makes a lot of sense! The HGVS nomenclature doesn't state this explicitly, but I think indeed it doesn't make sense to include amino acids after the inserted Ter.


> OK so we now have
> (...)

Excellent, thanks a lot!!! :partying_face:
