### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by peq123** [openvar/variantValidator#215]
Hi @PeteCausey-Freeman , 
The following request causes an internal server error.
https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NG_005905.2%3Ag.61068_98138del/NM_007294.3

peq123

**Comment by ifokkema** [comment]
That's funny - any variant on that NG fails with GRCh38. When changing to GRCh37 it does work. I would suppose this NG would be based on GRCh38, however.

**Comment by PeteCausey-Freeman** [comment]
Most NG_ are really old, as are LRGs. This is why I worry about them because they are so far out of date it's comical!

**Comment by PeteCausey-Freeman** [comment]
They also lack annotations of up-to-date transcripts

**Comment by ifokkema** [comment]
Hmm...  this NG is actually very new. Maybe actually too new? Just 2 days old, apparently.

**Comment by PeteCausey-Freeman** [comment]
That is also possible, but it is also possible that the transcript versions used in the RefSeqGene are only annotated to GRCh37 and not GRCh38. Its a mess :)

**Comment by peq123** [comment]
Excluding from my dataset then....seems to much work to get this working before the end of my project

**Comment by peq123** [comment]
@PeteCausey-Freeman 
have another one for you NM_000059.3:c.7241_7242inv

**Comment by peq123** [comment]
Hi @PeteCausey-Freeman 
Following @ifokkema 's observation that NG works under GRCh37.. I have been doing some more testing with them and came across the following warning:

The warning says it was expected one of (, ?, or a digit but the submitted variant does indeed have these.

```
{
  "flag": "warning",
  "metadata": {
    "seqrepo_db": "2018-08-21",
    "uta_schema": "uta_20180821",
    "variantvalidator_hgvs_version": "1.2.5.vv1",
    "variantvalidator_version": "1.0.4.dev17+gd16b9ef.d20200422"
  },
  "validation_warning_1": {
    "alt_genomic_loci": [],
    "gene_ids": {},
    "gene_symbol": "",
    "genome_context_intronic_sequence": "",
    "hgvs_lrg_transcript_variant": "",
    "hgvs_lrg_variant": "",
    "hgvs_predicted_protein_consequence": {
      "slr": "",
      "tlr": ""
    },
    "hgvs_refseqgene_variant": "",
    "hgvs_transcript_variant": "",
    "primary_assembly_loci": {},
    "reference_sequence_records": "",
    "refseqgene_context_intronic_sequence": "",
    "submitted_variant": "NG_005905.2:g.(92500_92501)_(92714_93868)del",
    "transcript_description": "",
    "validation_warnings": [
      "NG_005905.2:g._del: char 14: expected one of (, ?, or a digit"
    ]
  }
}
```

**Comment by peq123** [comment]
Also happens with other description types
```
{'flag': 'warning',
 'metadata': {'seqrepo_db': '2018-08-21',
  'uta_schema': 'uta_20180821',
  'variantvalidator_hgvs_version': '1.2.5.vv1',
  'variantvalidator_version': '1.0.4.dev17+gd16b9ef.d20200422'},
 'validation_warning_1': {'alt_genomic_loci': [],
  'gene_ids': {},
  'gene_symbol': '',
  'genome_context_intronic_sequence': '',
  'hgvs_lrg_transcript_variant': '',
  'hgvs_lrg_variant': '',
  'hgvs_predicted_protein_consequence': {'slr': '', 'tlr': ''},
  'hgvs_refseqgene_variant': '',
  'hgvs_transcript_variant': '',
  'primary_assembly_loci': {},
  'reference_sequence_records': '',
  'refseqgene_context_intronic_sequence': '',
  'submitted_variant': 'NC_000017.11:g.(?_43070908)_(43076634_?)dup',
  'transcript_description': '',
  'validation_warnings': ['NC_000017.11:g._dup: char 15: expected one of (, ?, or a digit']}}

{'flag': 'warning',
 'metadata': {'seqrepo_db': '2018-08-21',
  'uta_schema': 'uta_20180821',
  'variantvalidator_hgvs_version': '1.2.5.vv1',
  'variantvalidator_version': '1.0.4.dev17+gd16b9ef.d20200422'},
 'validation_warning_1': {'alt_genomic_loci': [],
  'gene_ids': {},
  'gene_symbol': '',
  'genome_context_intronic_sequence': '',
  'hgvs_lrg_transcript_variant': '',
  'hgvs_lrg_variant': '',
  'hgvs_predicted_protein_consequence': {'slr': '', 'tlr': ''},
  'hgvs_refseqgene_variant': '',
  'hgvs_transcript_variant': '',
  'primary_assembly_loci': {},
  'reference_sequence_records': '',
  'refseqgene_context_intronic_sequence': '',
  'submitted_variant': 'NM_007294.3:c.(?_-233)_(134+1_135-1)del',
  'transcript_description': '',
  'validation_warnings': ['NM_007294.3:c._del: char 14: expected one of (, *, or a digit']}}
```

**Comment by ifokkema** [comment]
> NM_000059.3:c.7241_7242inv

This one seems to work for me!
https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_000059.3%3Ac.7241_7242inv/all?content-type=application%2Fjson


> The warning says it was expected one of (, ?, or a digit but the submitted variant does indeed have these.

These errors may actually be related to #92 rather than to the NG. Uncertain positions can not be supported because VV can not predict what variant needs to be validated.

**Comment by peq123** [comment]
@ifokkema Thanks for the update. I had noticed the inv variants had begun to work. 


the warning however is a different issue because it says it expects a character that it has removed in some preparation step of variant validation - if I can direct you to the submitted variant field and compare that against the warning. For clarity:
'submitted_variant': 'NC_000017.11:g.(?_43070908)_(43076634_?)dup',
 'validation_warnings': ['NC_000017.11:g._dup: char 15: expected one of (, ?, or a digit']

agreed it looks part of #92 so will post there also 

peq123

**Comment by ifokkema** [comment]
> the warning however is a different issue because it says it expects a character that it has removed in some preparation step of variant validation - if I can direct you to the submitted variant field and compare that against the warning. For clarity:
> 'submitted_variant': `NC_000017.11:g.(?_43070908)_(43076634_?)dup`,
> 'validation_warnings': ['NC_000017.11:g._dup: char 15: expected one of (, ?, or a digit']

I noticed that too; linking #168 here as well for completeness. Implementing #92 in the same way #168 was implemented, will fix that incorrect warning, but it won't let you use uncertain positions.

**Comment by peq123** [comment]
Hi @PeteCausey-Freeman 
I am still getting internal server errors for this inversion:

https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_000059.3%3Ac.7241_7242inv/NM_000059.3?content-type=application%2Fjson

**Comment by PeteCausey-Freeman** [comment]
Hi guys

Really sorry. I have been so slammed grant writing. I'll take a look this afternoon

**Comment by PeteCausey-Freeman** [comment]
Thanks to you both for all these annotations. So useful

**Comment by PeteCausey-Freeman** [comment]
I'm closing this because once I push the latest update to the server, NM_000059.3:c.7241_7242inv will work. Also, uncertain positions are covered in other issues. These will take time and some discussion with @ifokkema. To be continued
