### ISSUE TITLE
NC(NM) notation doesn't work for mismatches between NC and NM

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#218]
Hey! Not sure if this is an easy one to fix...

When using VV to check an NM-based description, like [`NM_025184.3:c.-60_-56=`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NM_025184.3%3Ac.-60_-56%3D/all?content-type=application%2Fjson) works nicely:

```json
{
  "NM_025184.3:c.-60_-56=": {
    "hgvs_transcript_variant": "NM_025184.3:c.-60_-56=",
    "primary_assembly_loci": {
      "grch37": {
        "hgvs_genomic_description": "NC_000023.10:g.44202891dup"
      },
      "grch38": {
        "hgvs_genomic_description": "NC_000023.11:g.44343645dup"
      }
    }
  }
}
```

However, since LOVD now always sends NM-based variants using the NC(NM) notation to prevent problems with intronic variants. So we send [`NC_000023.10(NM_025184.3):c.-60_-56=`](https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/NC_000023.10(NM_025184.3)%3Ac.-60_-56%3D/all?content-type=application%2Fjson) and get:

```json
{
  "flag": "warning",
  "validation_warning_1": {
    "submitted_variant": "NC_000023.10(NM_025184.3):c.-60_-56=",
    "validation_warnings": [
      "NC_000023.10:g.44202890_44202893GCCGC=: Variant reference (GCCGC) does not agree with reference sequence (GCGC)"
    ]
  }
}
```

I suppose when using NC(NM), VV checks if they match. When they don't, VV throws an error. This means I can't always use NC(NM) but I should now use NM-based description and only include the NC when introns are included. Would it be possible to still allow for NC(NM) notation in these cases?

**Comment by PeteCausey-Freeman** [comment]
Just finishing a grant including some dosh for you if we win :). I'll look on Wednesday :) . Cheers mate. Hope you are well

**Comment by PeteCausey-Freeman** [comment]
Hi @ifokkema 
I personally would discourage the use of NC_000023.10(NM_025184.3):c.-60_-56= for anything but introns. For bases contained in the intronic reference sequence the c. coordinates are implicit. The NC_000023.10 is completely redundant.

**Comment by ifokkema** [comment]
> I personally would discourage the use of NC_000023.10(NM_025184.3):c.-60_-56= for anything but introns. (...) The NC_000023.10 is completely redundant.

You're right, of course. Currently, LOVD just doesn't try to be smart about when and when not to send the NC. It now always does. Obviously, for intronic variants, it is required and I can detect if we're using them. However, I'm also thinking about positions beyond the UTRs. This is related to #173; see the last comment there. I'd like to support the curator's wishes to annotate variants just outside of transcripts, like with intronic variants. Perhaps I should have another look at the transcript fields to see if I can determine when to send the NC and when not to.

**Comment by ifokkema** [comment]
This one also applies but may be fixed on my side if I selectively send the NC instead of always.

**Comment by PeteCausey-Freeman** [comment]
This isn't really a bug but rather a nomenclature issue. The NC_000023.10 is entirely redundant and VV checks the relevant reference sequence. In Exonic sequence, priority is given to the transcript so an error will be returned. However, if the correct variant is submitted at the transcript level, the genomic variant should also be output correctly. 

I will close this for now but we can re-open if we decide to at a later date. I think the LOVD patch is the right way to go
