### ISSUE TITLE
rare response issues.

### ISSUE THREAD

**Issue by peq123** [openvar/variantValidator#221]
@PeteCausey-Freeman 

Hi Pete, I have noticed some weird behaviour with the API. It appears it is returning results from another query as the returned json is completely irrelevant to my query. 
the query:
`https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_007294.3%3Ac.98A%3EG%7CNM_007294.3%3Ac.5193%2B7A%3EC%7CNM_007294.3%3Ac.5193%2B6T%3EG%7CNM_007294.3%3Ac.5193%2B6T%3EA%7CNM_007294.3%3Ac.5193%2B5G%3ET%7CNM_007294.3%3Ac.5193%2B5G%3EC%7CNM_007294.3%3Ac.5193%2B5G%3EA%7CNM_007294.3%3Ac.5178A%3ET%7CNM_007294.3%3Ac.5178A%3EC%7CNM_007294.3%3Ac.5153-22G%3ET%7CNM_007294.3%3Ac.63C%3EG%7CNM_007294.3%3Ac.5153-9T%3EA%7CNM_007294.3%3Ac.5153-10A%3ET%7CNM_007294.3%3Ac.5153-10A%3EG%7CNM_007294.3%3Ac.5153-10A%3EC%7CNM_007294.3%3Ac.5153-11G%3EC%7CNM_007294.3%3Ac.64T%3EG%7CNM_007294.3%3Ac.64T%3EA%7CNM_007294.3%3Ac.63C%3EA%7CNM_007294.3%3Ac.73C%3EG%7CNM_007294.3%3Ac.62T%3EC%7CNM_007294.3%3Ac.5153-20C%3ET%7CNM_007294.3%3Ac.5153-20C%3EG%7CNM_007294.3%3Ac.5153-20C%3EA%7CNM_007294.3%3Ac.5153-21T%3EG%7CNM_007294.3%3Ac.5153-21T%3EC%7CNM_007294.3%3Ac.5153-21T%3EA%7CNM_007294.3%3Ac.5153-9T%3EC%7CNM_007294.3%3Ac.73C%3ET%7CNM_007294.3%3Ac.5177G%3EA%7CNM_007294.3%3Ac.81-23T%3EA%7CNM_007294.3%3Ac.81-15C%3ET%7CNM_007294.3%3Ac.81-15C%3EG%7CNM_007294.3%3Ac.5167A%3ET%7CNM_007294.3%3Ac.5167A%3EC%7CNM_007294.3%3Ac.5166T%3EG%7CNM_007294.3%3Ac.5166T%3EC%7CNM_007294.3%3Ac.5166T%3EA%7CNM_007294.3%3Ac.80%2B4A%3EG%7CNM_007294.3%3Ac.74C%3EG%7CNM_007294.3%3Ac.80%2B4A%3EC%7CNM_007294.3%3Ac.80%2B3A%3ET%7CNM_007294.3%3Ac.80%2B3A%3EG%7CNM_007294.3%3Ac.80%2B3A%3EC%7CNM_007294.3%3Ac.5154G%3EC%7CNM_007294.3%3Ac.76A%3EG%7CNM_007294.3%3Ac.76A%3EC%7CNM_007294.3%3Ac.994C%3EG%7CNM_007294.3%3Ac.5196T%3EA%7CNM_007294.3%3Ac.3315T%3EA%7CNM_007294.3%3Ac.16C%3ET%7CNM_007294.3%3Ac.400G%3EA%7CNM_007294.3%3Ac.2116C%3ET%7CNM_007294.3%3Ac.4484%2B5G%3EA%7CNM_007294.3%3Ac.733G%3EC%7CNM_007294.3%3Ac.2023G%3EA%7CNM_007294.3%3Ac.2288C%3EA%7CNM_007294.3%3Ac.2232T%3EA%7CNM_007294.3%3Ac.5272A%3EG%7CNM_007294.3%3Ac.3301A%3EG%7CNM_007294.3%3Ac.2981G%3ET%7CNM_007294.3%3Ac.5063T%3EC%7CNM_007294.3%3Ac.929A%3EC%7CNM_007294.3%3Ac.4057G%3EA%7CNM_007294.3%3Ac.2881A%3ET%7CNM_007294.3%3Ac.665A%3EC%7CNM_007294.3%3Ac.809A%3EG%7CNM_007294.3%3Ac.4096%2B4T%3EC%7CNM_007294.3%3Ac.1343A%3EC%7CNM_007294.3%3Ac.4671T%3EG%7CNM_007294.3%3Ac.1774A%3EC%7CNM_007294.3%3Ac.4304A%3ET%7CNM_007294.3%3Ac.2823T%3EG%7CNM_007294.3%3Ac.4549C%3ET%7CNM_007294.3%3Ac.1865C%3EG%7CNM_007294.3%3Ac.1423A%3EG%7CNM_007294.3%3Ac.2017G%3EC%7CNM_007294.3%3Ac.3199A%3ET%7CNM_007294.3%3Ac.212%2B4T%3EG%7CNM_007294.3%3Ac.1474A%3EG%7CNM_007294.3%3Ac.5407-7G%3EA%7CNM_007294.3%3Ac.2366G%3EA%7CNM_007294.3%3Ac.3139G%3EA%7CNM_007294.3%3Ac.3288A%3EG%7CNM_007294.3%3Ac.4673T%3EG%7CNM_007294.3%3Ac.835C%3ET%7CNM_007294.3%3Ac.2279C%3ET%7CNM_007294.3%3Ac.398G%3ET%7CNM_007294.3%3Ac.3886T%3EC%7CNM_007294.3%3Ac.1190A%3ET%7CNM_007294.3%3Ac.1933T%3EC%7CNM_007294.3%3Ac.5332%2B11G%3EA%7CNM_007294.3%3Ac.3737C%3ET%7CNM_007294.3%3Ac.4192G%3EA%7CNM_007294.3%3Ac.4234G%3EC%7CNM_007294.3%3Ac.3385A%3EG%7CNM_007294.3%3Ac.70T%3EG%7CNM_007294.3%3Ac.2851A%3EG%7CNM_007294.3%3Ac.4171A%3EG%7CNM_007294.3%3Ac.5285G%3EC%7CNM_007294.3%3Ac.4082T%3EC%7CNM_007294.3%3Ac.2993T%3EG%7CNM_007294.3%3Ac.485T%3EG%7CNM_007294.3%3Ac.5518G%3ET%7CNM_007294.3%3Ac.1760T%3EC%7CNM_007294.3%3Ac.132C%3EG%7CNM_007294.3%3Ac.945G%3EC%7CNM_007294.3%3Ac.2909A%3EG%7CNM_007294.3%3Ac.3159A%3EG%7CNM_007294.3%3Ac.34C%3EG%7CNM_007294.3%3Ac.4514A%3EG%7CNM_007294.3%3Ac.1204G%3EA%7CNM_007294.3%3Ac.1025T%3EA%7CNM_007294.3%3Ac.3510T%3EG%7CNM_007294.3%3Ac.4199T%3EA%7CNM_007294.3%3Ac.5050A%3ET%7CNM_007294.3%3Ac.1418A%3EC%7CNM_007294.3%3Ac.5195A%3EG%7CNM_007294.3%3Ac.1796A%3EG%7CNM_007294.3%3Ac.72T%3EG%7CNM_007294.3%3Ac.5156T%3EC%7CNM_007294.3%3Ac.3124A%3EC%7CNM_007294.3%3Ac.1193C%3ET%7CNM_007294.3%3Ac.139T%3EC%7CNM_007294.3%3Ac.5407G%3ET%7CNM_007294.3%3Ac.586T%3EC%7CNM_007294.3%3Ac.3521C%3EG%7CNM_007294.3%3Ac.3614G%3ET%7CNM_007294.3%3Ac.4900A%3EG%7CNM_007294.3%3Ac.3472G%3EA%7CNM_007294.3%3Ac.4942A%3ET%7CNM_007294.3%3Ac.4970T%3EC%7CNM_007294.3%3Ac.235T%3EG%7CNM_007294.3%3Ac.4810C%3EG%7CNM_007294.3%3Ac.301%2B13T%3EA%7CNM_007294.3%3Ac.1884T%3EC%7CNM_007294.3%3Ac.-20%2B13C%3EG%7CNM_007294.3%3Ac.5457T%3EC%7CNM_007294.3%3Ac.9A%3EG%7CNM_007294.3%3Ac.3867A%3EG%7CNM_007294.3%3Ac.2310A%3EG%7CNM_007294.3%3Ac.612G%3EA%7CNM_007294.3%3Ac.2064A%3ET%7CNM_007294.3%3Ac.2661C%3EG%7CNM_007294.3%3Ac.5152%2B13C%3ET%7CNM_007294.3%3Ac.4308T%3EA%7CNM_007294.3%3Ac.4358-20T%3EG%7CNM_007294.3%3Ac.4185%2B20G%3EA%7CNM_007294.3%3Ac.1284A%3EG%7CNM_007294.3%3Ac.4485-14A%3ET%7CNM_007294.3%3Ac.81-16C%3ET%7CNM_007294.3%3Ac.3714T%3EG%7CNM_007294.3%3Ac.1536T%3EC%7CNM_007294.3%3Ac.615A%3EG%7CNM_007294.3%3Ac.1759A%3EG%7CNM_007294.3%3Ac.3519T%3EC%7CNM_007294.3%3Ac.4134C%3ET%7CNM_007294.3%3Ac.2214T%3EC%7CNM_007294.3%3Ac.87G%3EA%7CNM_007294.3%3Ac.936C%3ET/NR_027676.1%7CNM_007298.3%7CNM_007300.3%7CNM_007294.3%7CNM_007297.3%7CNM_007299.3?content-type=application%2Fjson`
return 3 different responses (one of which appeared to be the actual result)

an example of one of the incorrect responses:
`{"NM_172107.3:c.875T>C":{"alt_genomic_loci":[],"gene_ids":{"ccds_ids":["CCDS13518","CCDS13519","CCDS13520","CCDS13521","CCDS46629"],"ensembl_gene_id":"ENSG00000075043","entrez_gene_id":"3785","hgnc_id":"HGNC:6296","omim_id":["602235"],"ucsc_id":"uc002yey.2"},"gene_symbol":"KCNQ2","genome_context_intronic_sequence":"","hgvs_lrg_transcript_variant":"","hgvs_lrg_variant":"","hgvs_predicted_protein_consequence":{"slr":"NP_742105.1:p.(L292P)","tlr":"NP_742105.1:p.(Leu292Pro)"},"hgvs_refseqgene_variant":"","hgvs_transcript_variant":"NM_172107.3:c.875T>C","primary_assembly_loci":{"grch37":{"hgvs_genomic_description":"NC_000020.10:g.62071003A>G","vcf":{"alt":"G","chr":"20","pos":"62071003","ref":"A"}},"grch38":{"hgvs_genomic_description":"NC_000020.11:g.63439650A>G","vcf":{"alt":"G","chr":"20","pos":"63439650","ref":"A"}},"hg19":{"hgvs_genomic_description":"NC_000020.10:g.62071003A>G","vcf":{"alt":"G","chr":"chr20","pos":"62071003","ref":"A"}},"hg38":{"hgvs_genomic_description":"NC_000020.11:g.63439650A>G","vcf":{"alt":"G","chr":"chr20","pos":"63439650","ref":"A"}}},"reference_sequence_records":{"protein":"https://www.ncbi.nlm.nih.gov/nuccore/NP_742105.1","transcript":"https://www.ncbi.nlm.nih.gov/nuccore/NM_172107.3"},"refseqgene_context_intronic_sequence":"","submitted_variant":"NM_172107.3:c.875T>C","transcript_description":"Homo sapiens potassium voltage-gated channel subfamily Q member 2 (KCNQ2), transcript variant 1, mRNA","validation_warnings":["RefSeqGene record not available"]},"flag":"gene_variant","metadata":{"seqrepo_db":"2018-08-21","uta_schema":"uta_20180821","variantvalidator_hgvs_version":"1.2.5.vv1","variantvalidator_version":"1.0.4.dev17+gd16b9ef.d20200422"}}`

**Comment by peq123** [comment]
I feel sorry for the person that gets the results for my query...

**Comment by PeteCausey-Freeman** [comment]
This has happened before. I think we need to push Andy to get some money to sort the front end. I'm not sure how to sort it.

**Comment by ifokkema** [comment]
I can imagine that smaller queries would mitigate the chances of this happening? @peq123 , how many variants at a time are you sending now? Would you want to try cutting up the queries in smaller chunks and see if that helps?

**Comment by peq123** [comment]
The amount of variants run in any one request depends on the complexity of the variant. I implemented some error checking after I noticed this issue that checks submitted_variant key in the returning data matches what I send. If it doesn't, it just re-sends the request up to a maximum of 5 repeats. 

Thanks again for the suggestions.

**Comment by ifokkema** [comment]
That's odd. It might require me to verify the VV output as well then. I haven't discovered this before (I'm doing single requests only), but I never check the `submitted_variant` key since I expect to return the correct variant :sweat_smile:
