### ISSUE TITLE
GRCh37 issues

### ISSUE THREAD

**Issue by peq123** [openvar/variantValidator#222]
@PeteCausey-Freeman 
Hi Pete, getting these errors when validating gnomAD  r2_1 variants

`
{"flag":"warning","metadata":{"seqrepo_db":"2018-08-21","uta_schema":"uta_20180821","variantvalidator_hgvs_version":"1.2.5.vv1","variantvalidator_version":"1.0.4.dev17+gd16b9ef.d20200422"},"validation_warning_1":{"alt_genomic_loci":[],"gene_ids":{},"gene_symbol":"","genome_context_intronic_sequence":"","hgvs_lrg_transcript_variant":"","hgvs_lrg_variant":"","hgvs_predicted_protein_consequence":{"slr":"","tlr":""},"hgvs_refseqgene_variant":"","hgvs_transcript_variant":"","primary_assembly_loci":{},"reference_sequence_records":"","refseqgene_context_intronic_sequence":"","submitted_variant":"GRCh37:17:41242976:G:A","transcript_description":"","validation_warnings":["Failed to fetch NC_000017.10 from SeqRepo (/local/seqrepo/2018-08-21) ([Errno 2] bNo such file or directory)"]}}
`

**Comment by ifokkema** [comment]
I've seen these errors returned sometimes when the positions I used were in the telomeric region. Can you provide an example variant?

**Comment by peq123** [comment]
The variant that caused the issue above was GRCh37:17:41242976:G:A

**Comment by ifokkema** [comment]
> The variant that caused the issue above was GRCh37:17:41242976:G:A

I can't reproduce this, I'm getting a correct output:
https://www35.lamp.le.ac.uk/VariantValidator/variantvalidator/GRCh37/17%3A41242976%3AG%3AA/all?content-type=application%2Fjson

Could this be a random error? I do sometimes notice random failures. When I get failures, I retry. After every failure, I extend the wait between retries with two additional seconds. After five retries, I give up. This reduces the number of failures a lot for me.

**Comment by PeteCausey-Freeman** [comment]
Yeah,

We do need some server end tweaks. Working on funding! :)
