### ISSUE TITLE
Gene to Transcripts failing to find any valid results

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#225]
The _H3-3A_ gene encodes the protein H3.3 histone A. Previous symbols for this gene include H3F3 and H3F3A. Searches using the Genes to Transcripts tool with any of these three symbols always produces the warning "Unable to retrieve data from the UTA, please contact admin".

RefSeq NM_002107.7 represents "Homo sapiens H3.3 histone A (H3-3A), transcript variant 1, mRNA". A search for NM_002107.7 returns no results, but that might be because NM_002107.7 is not currently in UTA. However, searching for each earlier version also turns up no results either. At least one earlier version must be in UTA, Not unexpectedly, NM_002107.7 returns "No transcript definition for (tx_ac=NM_002107.7)". However, NM_002107.4 returns "Unable to retrieve data from the UTA, please contact admin" Every other version returns "No transcript definition for (tx_ac=NM_002107.n).

**Comment by leicray** [comment]
Definitely something weird going on with this gene. When I validate NM_002107.4:c.1A>G it produces this output which lacks the chromosomal position of the gene. Every other aspect of the validation looks correct:
![image](https://user-images.githubusercontent.com/10340330/90480280-ecbced00-e127-11ea-8d2b-f7c30628d577.png)

**Comment by PeteCausey-Freeman** [comment]
Yeah, the location will be missing from UTA

**Comment by leicray** [comment]
I wonder how many other genes in UTA also have the chromosomal position missing.

**Comment by PeteCausey-Freeman** [comment]
OK update coming. 

Now you can use LRG, H3-3A, H3F3A, NM_002107.7, NM_002107

All work. Will update the servers this afternoon.

**Comment by leicray** [comment]
I suspect that you have had to tweak this manually. The problem is that HGNC have probably carried out a recent revision of all histone genes as they have a [specific page for histones](https://www.genenames.org/data/genegroup/#!/group/864).

**Comment by PeteCausey-Freeman** [comment]
Something strange has happened. I'm suddenly getting test fails. Hold on.

**Comment by PeteCausey-Freeman** [comment]
Ah, my mistake. Easy fix

**Comment by PeteCausey-Freeman** [comment]
I suspect there has been a mass roll out of new gene symbols to stop Excel breaking! Will cause a few headaches for a while until we adapt vv to search on gene ID which it should be doing anyway. Wasn't our decision

**Comment by leicray** [comment]
Did you update the servers yesterday afternoon?

Searching for H3-3A still fails, as before, and searching for NM_002107.4 now produces the error message "An internal server error occurred. Please try again later." after a very long wait.

**Comment by PeteCausey-Freeman** [comment]
No I'm expanding the database content to deal with additional issues highlighted here and on other places. Will take me a while. It will be very useful though

**Comment by PeteCausey-Freeman** [comment]
OK this is gonna be a significan update so will need me to roll out a new version of the website as well. The actual fix was simple, but we need to be forward thinking, so major edit on the way

**Comment by PeteCausey-Freeman** [comment]
Update now includes CCDS ID for each transcript, Whether the transcript is a MANE SELECT or REFSEQ SELECT Gene name

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/pull/233/commits/b5b22df7d5047808f81c62d43bdf46ee6718d34a
