### ISSUE TITLE
Create a PDF report in interactive mode

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#237]
It is becoming increasingly important to log and accurately cross reference stable information for genes etc. 

It would be useful if VV could output a pdf document that could be attached as metadata to clinical reports or be provided to journals as supplementary data

**Comment by ifokkema** [comment]
Great idea! :+1:

**Comment by PeteCausey-Freeman** [comment]
Thanks @ifokkema. Will be a bit of fun to figure out how to do it too. 

Linking this issue in VV_Web repo

**Comment by ifokkema** [comment]
I know I have my favorite libraries for PHP (two different ones, depending on my needs), but that won't help you for Python :sweat_smile: 
If it's as easy as TCPDF, you'll be fine :grin:

**Comment by PeteCausey-Freeman** [comment]
Probably a module somewhere (He hopes! Haha)

**Comment by leicray** [comment]
We need to ensure that the PDF files that are produced conform to the PDF/A standard for archiving.

Something like [https://pypi.org/project/python-pdf/](url) might be a good starting point.

**Comment by PeteCausey-Freeman** [comment]
We need to get it working first ;)

**Comment by PeteCausey-Freeman** [comment]
I'm not sure if this helps but the tutorial I'm following states 
```python
pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
```
I'm guessing ISO is the pdf standard???

**Comment by leicray** [comment]
ISO-8859-1 defines the "Latin alphabet No. 1" [https://en.wikipedia.org/wiki/ISO/IEC_8859-1](url)

ISO-32000-2 defines the PDF standard [https://en.wikipedia.org/wiki/PDF](url)

The reason for mentioning PDF/A in an earlier comment was to highlight the need to use a python PDF library that supports PDF/A from the outset.

**Comment by ifokkema** [comment]
Don't use ISO-8859-1, just don't. Not *-15 either. It'll bite you in the rear one day. UTF-8 or higher, always. I'm still solving problems now and then because in the past I made the poor choice for ISO-8859-1/Latin1.

**Comment by leicray** [comment]
I fully understand the sound advice to use UTF-8 or higher. However, a report generated by VV will never need a character set that goes beyond Latin1. In fact, we need to ensure that no stray non-Latin1 characters ever appear in such reports.

There is no plan to produce reports other than in English; or is there?

**Comment by PeteCausey-Freeman** [comment]
Thanks guys.

First job is mocking something up. Once it's working we can have a call to discuss the look of the output. It'll effectively be a conversion of a slimmed down HTML page

**Comment by ifokkema** [comment]
> (...) However, a report generated by VV will never need a character set that goes beyond Latin1. (...)

Never say never :wink: 

Besides the translation of the output into non-English that may indeed never happen, other things that may be included: User's names, locations, or comments; publication titles or author names; or re-use of the code in a future project that will include these. At this point, it'll likely cost merely a few seconds to choose UTF-8 over ISO-8859-1 (which for ISO-8859-1 characters doesn't cost any additional space anyway, so internally there's actually no change), but it might be very difficult to change it later.

> It'll effectively be a conversion of a slimmed down HTML page

That's the easiest method, indeed, and often works very well!

**Comment by leicray** [comment]
Okay, I can see the argument in favour of UTF-8. However, the report that will be generated will be, as was said previously, a slimmed-down HTML page. The goal is **not** to create a document that looks like a clinical testing lab report.

**Comment by leicray** [comment]
The PDF document that can now be created on lamp 525 ought to display the date and time at which the document was created. I'm thinking about the issue of users who might archive the PDF file to verify the results of a validation. With time, the output generated by VV will probably change in relation to reference sequences. This means that the results might be fully correct/complete only at the date/time at which the report is generated.

Related to this issue, it would be good to generate the PDF file in PDF-A format as I have mentioned above. It is not possible to edit a PDF-A file and retain the PDF-A assurance designation.
