### ISSUE TITLE
duplication checks - and Adding a warning e.g.  "Removing redundant reference bases from variant description"

### ISSUE THREAD

**Issue by jtdendunnen** [openvar/variantValidator#239]
Testing variant NM_006941.3:c.850_877dup28 gives error  "char 25: expected EOF", while NM_006941.3:c.850_877del28 is accepted (and corrected).

Testing variant NM_006941.3:c.1047dupT gives a correction to NM_006941.3:c.1047dup but the warning "Removing redundant reference bases from variant description" is missing.

**Comment by PeteCausey-Freeman** [comment]
Hi @jtdendunnen 
Thanks for the feedback.

Just for my working. The dup28 issue is something still on my to-do-list. Cross referencing this issue so I don't get lost
https://github.com/openvar/variantValidator/issues/216

I will use this issue to tackle adding an appropriate warning e.g. "Removing redundant reference bases from variant description".

Currently I have a huge teaching load, but I need to take some time to do apply some major updates over the first 3 weeks of November, so I will try tackle these too.

Thanks

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/029f439801ad707d37cd77c4452bdbccdb25b104 closes the issue

Note @jtdendunnen and Ivo, these changes will not show on the live servers yet. I will update after I have fixed a few more little bugs.

Cheers

Pete
