### ISSUE TITLE
Intergenic variants are not mapped to a chromosomal position

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#250]
The variant description NC_000017.11:g.50198002C>A (COL1A1) is shown to map to 17q21.33 when validated using the Validator interactive tool.

The variant description NC_000012.12:g.38316721G>A (intergenic) does not return a map location when validated in the same way, but otherwise validates correctly.

Is the map location determined from the known chromosomal location of individual genes, or from the absolute location of variant nucleotide? In principle, the chromosomal location of any nucleotide change can be determined using the NCBI data that map chromosomal bands to nucleotide positions.

Probably a low-priority issue.

**Comment by PeteCausey-Freeman** [comment]
The map location data is taken directly from RefSeq teanscript records so there will be no data for intergenic regions. Agreed its low priority but it has been on my radar. Perhaps one for an MSC project or similar
???

**Comment by leicray** [comment]
That would indeed make a nice self-contained MSc project.
