### ISSUE TITLE
gene2trans Server Error (500)

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#266]
Searching for the transcripts for ABCF2-H2BE1 and H2BE1 yields Server Error (500), but a search for ABCF2 completes as expected.

**Comment by PeteCausey-Freeman** [comment]
Adding the ALDH7A1 gene to this as well

**Comment by PeteCausey-Freeman** [comment]
The error for ALDH7A1 shows an issue with the way old transcripts used to be built by Reece.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pjf9/PycharmProjects/variantValidator/VariantValidator/modules/vvMixinCore.py", line 1247, in gene2transcripts
    tx_seq = self.sf.fetch_seq(tx)
  File "/Users/pjf9/anaconda3/envs/vvenv/lib/python3.6/site-packages/vvhgvs/dataproviders/seqfetcher.py", line 60, in fetch_seq
    ac=ac, ex=ex, self=self))
vvhgvs.exceptions.HGVSDataNotAvailableError: Failed to fetch NM_001202404.1/111..1620 from SeqRepo (/Users/Shared/seqrepo_dumps/VV_SR_2021_2/master) ('Alias NM_001202404.1/111..1620 (namespace: None)')
```

For now I will apply a bug fix patch but will speak to John about making sure these are purged from VVTA in the future

**Comment by PeteCausey-Freeman** [comment]
Note, this has been seen before [in the populate vv database scripts](https://github.com/openvar/populate_vvdb/blob/master/populate.py) line 55

```python
        if '..' in tx_id:
            continue
```

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/8cb0de9d996709c6694f237e22c3438a4c40caa4
