### ISSUE TITLE
LOVD Formatter endpoint not warning when genomic variants normalised

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#272]
Basing the examples on the input [NC_000017.11:g.50198002del](https://rest.variantvalidator.org/LOVD/lovd/GRCh38/NC_000017.11%3Ag.50198002del/refseq/all/False/True?content-type=application%2Fjson)
*Note: The variant is incorrect and needs to be normalised (as asked by Johan)*

**Comment by PeteCausey-Freeman** [comment]
The complete output is 
```json
{
  "NC_000017.11:g.50198002del": {
    "NC_000017.11:g.50198002del": {
      "g_hgvs": "NC_000017.11:g.50198003del",
      "genomic_variant_error": null,
      "hgvs_t_and_p": {
        "NM_000088.3": {
          "alt_genomic_loci": {
            "grch37": {},
            "grch38": {},
            "hg19": {},
            "hg38": {}
          },
          "gap_statement": null, # There really ought to be a warning here, opening an issue
          "gapped_alignment_warning": null,
          "p_hgvs_slc": "NP_000079.2:p.(G197Vfs*68)",
          "p_hgvs_tlc": "NP_000079.2:p.(Gly197ValfsTer68)",
          "primary_assembly_loci": {
            "grch37": {
              "NC_000017.11": {
                "hgvs_genomic_description": "NC_000017.11:g.50198003del",
                "vcf": {
                  "alt": "A",
                  "chr": "NC_000017.11",
                  "pos": "50198000",
                  "ref": "AC"
                }
              }
            },
            "grch38": {
              "NC_000017.11": {
                "hgvs_genomic_description": "NC_000017.11:g.50198003del",
                "vcf": {
                  "alt": "A",
                  "chr": "NC_000017.11",
                  "pos": "50198000",
                  "ref": "AC"
                }
              }
            },
            "hg19": {
              "NC_000017.11": {
                "hgvs_genomic_description": "NC_000017.11:g.50198003del",
                "vcf": {
                  "alt": "A",
                  "chr": "NC_000017.11",
                  "pos": "50198000",
                  "ref": "AC"
                }
              }
            },
            "hg38": {
              "NC_000017.11": {
                "hgvs_genomic_description": "NC_000017.11:g.50198003del",
                "vcf": {
                  "alt": "A",
                  "chr": "NC_000017.11",
                  "pos": "50198000",
                  "ref": "AC"
                }
              }
            }
          },
          "t_hgvs": "NM_000088.3:c.590del",
          "transcript_variant_error": null
        }
      },
      "p_vcf": "17:50198000:AC:A",
      "selected_build": "GRCh38"
    },
    "errors": [],
    "flag": null
  },
  "metadata": {
    "seqrepo_db": "/local/seqrepo/2018-08-21",
    "uta_schema": "uta_20180821",
    "variantformatter_version": "1.0.2.dev26+gcbd8fb1",
    "variantvalidator_hgvs_version": "1.2.5.vv1",
    "variantvalidator_version": "1.0.4.dev125+gd3e875e"
  }
}
```

**Comment by ifokkema** [comment]
What is this for? LOVD already picks this up and already warns the user.

**Comment by PeteCausey-Freeman** [comment]
The Endpoint really ought to be producing a warning too. However, Like LOVD I might handle this server-side since the key specifically states error rather than warning. Saves me a job if you are OK with it, will handle it in the design of https://github.com/openvar/variantValidator/issues/270

**Comment by ifokkema** [comment]
Hmmm... yeah, I believe we discussed this before. Currently, if the `flag` is set to `genomic_variant_warning` then the `genomic_variant_error` is interpreted as a fatal error so LOVD will trash the variant when that's filled in. I'm parsing that error message to [try and recognize what error it is](https://github.com/LOVDnl/LOVD3/blob/d8b20f877c52d0693d08dc61ebf2d007a4a5ca54/src/class/variant_validator.php#L422-L449), but if unrecognized, LOVD will just consider it incorrect and fail.

[I'm building warnings of myself now.](https://github.com/LOVDnl/LOVD3/blob/d8b20f877c52d0693d08dc61ebf2d007a4a5ca54/src/class/variant_validator.php#L506-L539)

**Comment by PeteCausey-Freeman** [comment]
Fantastic. Thanks very much for reminding me. I'm not going to close the issue for now if that's OK. I will close it when I close the VV lite issue so that I remember to discuss with you how you are handling this. Perhaps replicate your warnings in VV lite

**Comment by ifokkema** [comment]
Sure!
Whenever planning to make changes to the error/warning structure, it would really be good to add error/warning codes. That gives you more freedom to change error or warning strings because clients should primarily recognize the codes, not parse the strings.
Something like:
```json
{
    "errors": {
        "EINCONSISTENTLENGTH": "Length implied by coordinates must equal sequence deletion length"
    },
    "warnings": {}
}
```

**Comment by PeteCausey-Freeman** [comment]
Open a separate issue, we can look at this. plan it out. :)

**Comment by ifokkema** [comment]
Ah... I thought there wouldn't be a change on the VV side... well, OK, I'll need to update my code then. Or will this change not affect the endpoints that LOVD uses? (LOVD and VV endpoints, we don't use VF).

**Comment by PeteCausey-Freeman** [comment]
The LOVD endpoint uses VF so you do use it :P

**Comment by ifokkema** [comment]
Haha alright! I'll open an issue on our side then!
