### ISSUE TITLE
CAPTCHA does not work on LAMP 525

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#273]
I cannot create an account on LAMP 525 as CAPTCHA is not working. It's returning the error message "ERROR for site owner:
Invalid domain for site key"

**Comment by PeteCausey-Freeman** [comment]
Thanks. I'll look at it. I probably need to add the domain to the settings either at our end or theirs.

**Comment by leicray** [comment]
Sorting out CAPTCHA has solved part of the issue, but I have not received the confirmation email that is sent when a new user account is created.

**Comment by PeteCausey-Freeman** [comment]
Should be resolved now
