### ISSUE TITLE
Improve gap handling by improving overlapping variants with gaps

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#280]
**Describe the bug**
Sequence differences between the genome and the transcript aligned can contain gaps. The locations of these gaps are annotated by Variant Validator, and whenever a variant can overlap with these gaps, they are included in the variant description. However, the fact that the gap itself can also be described in different places, is currently overlooked.

**To Reproduce**
The problem is highlighted when submitting the following variant:
[`NC_000012.12:g.121626878del`](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NC_000012.12%3Ag.121626878del/NM_032790.3?content-type=application%2Fjson)
   returns
`NM_032790.3:c.131del`

However, looking at the actual sequences, this should be
`NM_032790.3:c.131_132insCCGC`

The relevant region can be displayed in the [UCSC genome browser](http://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&virtModeType=default&virtMode=0&position=chr12%3A121626863%2D121626895).

The relevant sequences:
```
CCGGGGGCCCCGCCCCGCCACCGCCG   (NC_000012.12:g.121626860_121626885)
CCGGGG-----GCCCCGCCACCGCCG   (NM_032790.3:c.118_138)
```

The gap can actually be shifted 3' to become:

```
CCGGGGGCCCCGCCCCGCCACCGCCG   (NC_000012.12:g.121626860_121626885)
CCGGGGGCCCCGCC-----ACCGCCG   (NM_032790.3:c.118_138)
```

Now, the gap fully overlaps with `NC_000012.12:g.121626878del` and applying this variant to the NC generates:

```
CCGGGGGCCCCGCCCCGC-ACCGCCG   (NC_000012.12:g.121626860_121626885)
CCGGGGGCCCCGCC-----ACCGCCG   (NM_032790.3:c.118_138)
```

Translating this into the NM then results into the insertion of CCGC between c.131 and c.132, resulting into `NM_032790.3:c.131_132insCCGC`.

**Expected behavior**
Variant Validator can't shift `NC_000012.12:g.121626878del` any further 5', but the gap can be shifted more 3' to solve the problem. Another solution would be to simply extend the area to look for gaps, but it's unclear how far away the gap can be, and what the effect is on the performance.

**Additional issues**
After this is solved, we should investigate whether the following variant still results in strange behaviour:

`NC_000012.12:g.121626869_121626878=`
    gives me
`NM_032790.3:c.126_127insA`
    and then, at the same page, shows,
`NC_000012.12:g.121626873_121626874insA`

Meaning, submitting a WT variant maps to an insertion on the same reference sequence as how we submitted the variant.

**Comment by PeteCausey-Freeman** [comment]
Hi @ifokkema 

I have made some preliminary tweaks to the code to address the main bug. Let's tackle additional issues when I have completed the main issue.

Here is a first-attempt at the json

```json
{
    "NM_032790.3:c.131_132insCCGC": {
        "alt_genomic_loci": [
            {
                "grch37": {
                    "hgvs_genomic_description": "NW_004504303.2:g.302877_302881delinsCCG",
                    "vcf": {
                        "alt": "CCG",
                        "chr": "HG1595_PATCH",
                        "pos": "302877",
                        "ref": "ACCGC"
                    }
                }
            },
            {
                "hg19": {
                    "hgvs_genomic_description": "NW_004504303.2:g.302877_302881delinsCCG",
                    "vcf": {
                        "alt": "CCG",
                        "chr": "NW_004504303.2",
                        "pos": "302877",
                        "ref": "ACCGC"
                    }
                }
            },
            {
                "grch38": {
                    "hgvs_genomic_description": "NW_018654719.1:g.32649_32650insCCGC",
                    "vcf": {
                        "alt": "CCCCG",
                        "chr": "HG2047_PATCH",
                        "pos": "32648",
                        "ref": "C"
                    }
                }
            },
            {
                "hg38": {
                    "hgvs_genomic_description": "NW_018654719.1:g.32649_32650insCCGC",
                    "vcf": {
                        "alt": "CCCCG",
                        "chr": "NW_018654719.1",
                        "pos": "32648",
                        "ref": "C"
                    }
                }
            }
        ],
        "annotations": {
            "chromosome": "12",
            "db_xref": {
                "CCDS": null,
                "ensemblgene": null,
                "hgnc": "HGNC:25896",
                "ncbigene": "84876",
                "select": "RefSeq"
            },
            "ensembl_select": false,
            "mane_plus_clinical": false,
            "mane_select": false,
            "map": "12q24.31",
            "note": "ORAI calcium release-activated calcium modulator 1",
            "refseq_select": true,
            "variant": "0"
        },
        "gene_ids": {
            "ccds_ids": [],
            "ensembl_gene_id": "ENSG00000276045",
            "entrez_gene_id": "84876",
            "hgnc_id": "HGNC:25896",
            "omim_id": [
                "610277"
            ],
            "ucsc_id": "uc031zps.1"
        },
        "gene_symbol": "ORAI1",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "LRG_93t1:c.131_132insCCGC",
        "hgvs_lrg_variant": "LRG_93:g.5304_5305insCCGC",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "LRG_93p1:p.(P45Rfs*44)",
            "lrg_tlr": "LRG_93p1:p.(Pro45ArgfsTer44)",
            "slr": "NP_116179.2:p.(P45Rfs*44)",
            "tlr": "NP_116179.2:p.(Pro45ArgfsTer44)"
        },
        "hgvs_refseqgene_variant": "NG_007500.1:g.5304_5305insCCGC",
        "hgvs_transcript_variant": "NM_032790.3:c.131_132insCCGC",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000012.11:g.122064779_122064783delinsCCG",
                "vcf": {
                    "alt": "CCG",
                    "chr": "12",
                    "pos": "122064779",
                    "ref": "ACCGC"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000012.12:g.121626878del",
                "vcf": {
                    "alt": "G",
                    "chr": "12",
                    "pos": "121626876",
                    "ref": "GC"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000012.11:g.122064779_122064783delinsCCG",
                "vcf": {
                    "alt": "CCG",
                    "chr": "chr12",
                    "pos": "122064779",
                    "ref": "ACCGC"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000012.12:g.121626878del",
                "vcf": {
                    "alt": "G",
                    "chr": "chr12",
                    "pos": "121626876",
                    "ref": "GC"
                }
            }
        },
        "reference_sequence_records": {
            "lrg": "http://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_93.xml",
            "protein": "https://www.ncbi.nlm.nih.gov/nuccore/NP_116179.2",
            "refseqgene": "https://www.ncbi.nlm.nih.gov/nuccore/NG_007500.1",
            "transcript": "https://www.ncbi.nlm.nih.gov/nuccore/NM_032790.3"
        },
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh38",
        "submitted_variant": "NC_000012.12:g.121626878del",
        "transcript_description": "Homo sapiens ORAI calcium release-activated calcium modulator 1 (ORAI1), mRNA",
        "validation_warnings": [
            "The displayed variants may be artefacts of aligning NM_032790.3 with genome build GRCh38",
            "Caution should be used when reporting the displayed variant descriptions: If you are unsure, please contact admin"
        ]
    },
    "flag": "gene_variant",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.1.dev1+gb3a18e0",
        "variantvalidator_version": "1.0.4.dev214+g9cf795f.d20210407",
        "vvdb_version": "vvdb_2021_4",
        "vvseqrepo_db": "VV_SR_2021_2/master",
        "vvta_version": "vvta_2021_2"
    }
}
```

Please check the GRCh38 and transcript outputs. I will check the GRCh37 outputs and feed-back if they look right.

A few tests are currently failing, but the new code may have caused changed in the output, not errors but updated processing so I will add any alterations to the tests here as well

**Comment by PeteCausey-Freeman** [comment]
Update. Code is now modified to normalise the variant that is being considered and the position of any gaps. The idea being that if the gap and the variant can be noemalized such that they are adjacent or overlapping, corrective action is taken, otherwise no action is taken and standard style mapping is applied

The first version always applied a hard cut-off of bases that had to be considered. The issue here is that sometimes because we are considering the transcript and genomic sequence simultaneously, we get an overly consuming delins generated rather.

Now that the normalisation approach is in place, the results are much cleaner.

Currently running unit tests to see how the outcomes are affected

**Comment by PeteCausey-Freeman** [comment]
For reference, here is the image from UCSC

![image](https://user-images.githubusercontent.com/26568889/115568220-fe0c5980-a2b3-11eb-81fd-432d60f913ca.png)

**Comment by PeteCausey-Freeman** [comment]
Here is an interesting variant. 
Just so you know, I'd deliberately using both c. and n. (illegally) to record both the HGVS and the absolute position

The variant is 
NC_000019.10:g.50378563_50378564insTAC 

It maps directly to
NM_007121.5:c.514_515insTAC == NM_007121.5:n.795_796insTAC

Gap is identified by crawling along the transcript (in this case 3') until gap is found (Not slow!!!)
Note: the gap is 3bp (AAC)
NM_007121.5:n.795_799del            AAACA ins ATACAACA
NC_000019.10:g.50378563_50378564del A---A ins ATACAACA

The code then minimised the gap and maps back to the original reference sequence
NM_007121.5:n.795_799del            AAACA ins A
NC_000019.10:g.50378563_50378564del A---A ins A

The code then sees if the gap can be normalized to the original variant
Note: gets to 799 and the gap is stuck at 797
NM_007121.5:n.800delA
NM_007121.5:n.799delA
NM_007121.5:n.795_797delAAAinsATACAA

So, applying strict HGVS rules, the variants are separated by more than 1 base so cannot be merged, so the variants are 
NM_007121.5:n.795_796insTAC and NM_007121.5:n.799delA
However, if we allow an additional base to be considered between the variants, a much simpler outcome for the variant is 
NM_007121.5:c.515A>T = n.796A>T

I'm a bit stuck now because it is not entirely clear how to continue. I think the merger should not really be made, even though we have previously

**Comment by ifokkema** [comment]
Sorry for the late reply!

> Here is a first-attempt at the json

Looks great, except for the hg19/GRCh37 mapping which is off (what I mentioned as well in my email):

> ```json
>     {
>         "primary_assembly_loci": {
>             "grch37": {
>                 "hgvs_genomic_description": "NC_000012.11:g.122064779_122064783delinsCCG"
>             },
>             "hg19": {
>                 "hgvs_genomic_description": "NC_000012.11:g.122064779_122064783delinsCCG"
>             }
>         }
>     }
> ```

Comparison of the VCF fields for hg19 vs hg38 and GRCh37 vs GRCh38 clearly shows a different sequence is being handled.


> Update. Code is now modified to normalise the variant that is being considered and the position of any gaps. The idea being that if the gap and the variant can be noemalized such that they are adjacent or overlapping, corrective action is taken, otherwise no action is taken and standard style mapping is applied

Sounds great!

**Comment by PeteCausey-Freeman** [comment]
> Comparison of the VCF fields for hg19 vs hg38 and GRCh37 vs GRCh38 clearly shows a different sequence is being handled

Correct, the alignment of GRCh37 to the transcript in question is different. The gap widens to 6bp rather than 5bp and the additional base is an A base I believe. I am just correcting the final tests based on the new code. Want to commit my changes then I will look at the sequences here

**Comment by ifokkema** [comment]
> Here is an interesting variant.

I'm completely lost here, sorry :/
Why c. to n. and then back to c., what's wrong with n. and what two variants are separated by one bp? :thinking:

**Comment by PeteCausey-Freeman** [comment]
> I'm completely lost here, sorry :/
Why c. to n. and then back to c., what's wrong with n. and what two variants are separated by one bp? 🤔

Likely easier to discuss on a call

**Comment by PeteCausey-Freeman** [comment]
> Looks great, except for the hg19/GRCh37 mapping which is off (what I mentioned as well in my email):
```json
    {
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000012.11:g.122064779_122064783delinsCCG"
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000012.11:g.122064779_122064783delinsCCG"
            }
        }
    }
```

I think this is just a quirk of the extra A base in the alignment gap. If I create both variants (refer to the image above for numbering if necessary) , then the outcomes are equal

```
		g.								GGGCCCCGCCACCGCCACCGCCG
		c.          					                 GGGCC------CCGCCACCGCCG

		c.31_132insCCGC					GGGCC--CCGCCccgcACCGCCG
		g.122064779_122064783delinsCCG	GGGCC--CCGCCccgCACCGCCG	
```
Note, I have shown how each variant resolves to fill the gap, not the absolute numbering. The lower-case bases are inserted bases

![image](https://user-images.githubusercontent.com/26568889/116091938-3f7a7b80-a69d-11eb-983f-f1b411a85987.png)
