### ISSUE TITLE
duplication, protein prediction incorrect

### ISSUE THREAD

**Issue by jtdendunnen** [openvar/variantValidator#281]
When I try variant NM_003136.3:c.-33_78dup VV reports as predicted consequene at protein level NP_003127.1:p.(Met1_Glu26dup)
![Screenshot 2021-05-05 at 16 02 42 ](https://user-images.githubusercontent.com/16531711/117154176-e5279c00-adbb-11eb-809d-576e9ba4da68.png)

This prediction can not be correct since when the exon is duplicated the reading frame contains a stop codon at position 4 (agt tct tcg TAA gta) of the duplicated exon.

**Comment by PeteCausey-Freeman** [comment]
Interesting. Thanks @jtdendunnen. I will take a look at this ASAP. Will try get it out in the next version

**Comment by PeteCausey-Freeman** [comment]
Update
```json
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "NP_003127.1:p.(V27delinsSSS*)",
            "tlr": "NP_003127.1:p.(Val27delinsSerSerSerTer)"
        },
```
