### ISSUE TITLE
vcf2hgvs broken on dev server

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#291]
submission of any VCF file to vcf2hgvs on the dev server causes an error:

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">EncodeError at /service/vcf2hgvs/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Object of type 'bytes' is not JSON serializable</pre>

Request Method: | POST
-- | --
http://www525.lamp.le.ac.uk/service/vcf2hgvs/
3.1.7
EncodeError
Object of type 'bytes' is not JSON serializable
/local/miniconda3/envs/vvweb/lib/python3.6/json/encoder.py, line 180, in default
/usr/bin/python3
3.6.0
['/',  '/local/VVweb',  '/local/miniconda3/envs/vvweb',  '/local/miniconda3/envs/vvweb/lib/python36.zip',  '/local/miniconda3/envs/vvweb/lib/python3.6',  '/local/miniconda3/envs/vvweb/lib/python3.6/lib-dynload',  '/local/miniconda3/envs/vvweb/lib/python3.6/site-packages',  '/local/py3Repos/variantValidator',  '/local/py3Repos/vv_hgvs']
Mon, 16 Aug 2021 10:17:20 +0000

</body>
</html>

**Comment by PeteCausey-Freeman** [comment]
Thanks. I'll see if there is a traceback in the Apache Error log.

**Comment by leicray** [comment]
If the Apache Error log does not yield the necessary detail, try submitting a vcf2hgvs job using the file that I have linked below. This will result in a much more comprehensive error message.

[1.vcf.txt](https://github.com/openvar/variantValidator/files/6991743/1.vcf.txt)

**Comment by PeteCausey-Freeman** [comment]
It's OK, I submitted the job and accessed the traceback.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/VVweb/commit/6aa88d5abda90ea4ed88a4fa9e1ca3bc67fc16c5
