### ISSUE TITLE
Start greater than end

### ISSUE THREAD

**Issue by TeriForey** [openvar/variantValidator#30]
During the alt_gen_var loop (starting at line 8175), variants 180, 206, 315 and 316 all try to process variants with a start position greater than the end:

NC_000011.9:g.70785649_70785648delinsT
NC_000011.9:g.70790718_70790717delinsT
NW_003315905.1:g.134773_134772del
NC_000011.9:g.70790718_70790717delinsT

Note - these aren't in order.

These are currently skipped but we might need further investigation at a later date.

**Comment by PeteCausey-Freeman** [comment]
Has been sorted
