### ISSUE TITLE
numbering intronic nucleotides

### ISSUE THREAD

**Issue by jtdendunnen** [openvar/variantValidator#300]
the description NC_000023.11(NM_004006.2):c.1149+412A>G is not correct, the user neglected to change numbering from + to - numbering in the centre of the intron. Correct is c.1150-239G>A. The error reported: "The entered coordinates do not agree with the intron/exon boundaries for the selected transcript". This is not very informative and I wonder whther it is correct, c.1149+ is a correct intron/exon border.

**Comment by PeteCausey-Freeman** [comment]
Hi @jtdendunnen . Thanks for this. It might be an edge case that I have been looking for. 

I'll check the alignments in the first instance and get back to you.

**Comment by PeteCausey-Freeman** [comment]
This looks like a bug. The description is failing to validate full-stop so ignore the warning. I will take a look under the hood and see why it is failing.

**Comment by PeteCausey-Freeman** [comment]
The default behaviour ought to be that VV would correct the description to c.1150-239G>A yet this seems to be broken.

**Comment by PeteCausey-Freeman** [comment]
Sorted. The "caution" level for this particular section had been set to "Error" rather than "Warning" Thanks for spotting this.

Fixes applied. I will upload to the dev server. I will let you know when live.

**Comment by PeteCausey-Freeman** [comment]
Corrected on the dev server https://www525.lamp.le.ac.uk/
The warnings are not perfect, but the restorative actions taken by VV are clear in my opinion. @jtdendunnen are you happy for me to close this with the applied fixes?

**Comment by jtdendunnen** [comment]
yes, seems fixed now. Thanks for the efforts.

**Comment by PeteCausey-Freeman** [comment]
Thanks. Will close now
