### ISSUE TITLE
VariantFormatter error

### ISSUE THREAD

**Issue by i3hsInnovation** [openvar/variantValidator#303]
**Describe the bug**
"genomic_variant_error":"Failed to fetch NC_000017.10 from SeqRepo (/local/seqrepo/2018-08-21) ([Errno 9] b'Bad file descriptor')"
 
error on some of the variantformatter endpoint queries. I wondered if you were aware of a problem? This may be coincidence, but having tried a few different queries, it appears chr1-9 & X work, but Chr10+ doesn’t. Not an exhaustive test, but might be helpful. Many thanks for your help!

**To Reproduce**
Works:
https://rest.variantvalidator.org/VariantFormatter/variantformatter/GRCh37/X:15841319:G:A/refseq/None/FALSE?content-type=application%2Fjson
 
Fails:
https://rest.variantvalidator.org/VariantFormatter/variantformatter/GRCh37/17:29548956:A:C/refseq/None/FALSE?content-type=application%2Fjson

**Comment by i3hsInnovation** [comment]
Cannot replicate the error on the dev system or dockerised version. Could be a database error within the current version of SeqRepo, but this is re-built. 

I think it is currently best to get the new servers up and running and then test again. Needs re-visiting.

**Comment by PeteCausey-Freeman** [comment]
These no longer return issues now that VVTA and VV SeqRepo are running
