### ISSUE TITLE
Confusing error message when submitting a malformed variant

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#322]
**Describe the bug**
The LOVD API endpoint as well as the Variants In Journals genomic endpoint gives a confusing error message when submitting this malformed variant: [NC_000017.10:g.48275363CG>A](https://www608.lamp.le.ac.uk/LOVD/lovd/hg19/NC_000017.10%3Ag.48275363CG%3EA/all/all/True/False?content-type=application%2Fjson).

The error message is "NC_000017.10:g.48275363CG>A: char 25: expected the character '='".

The parser obviously gets lost there.

**Expected behavior**
It would be good if VV would provide a valid error message there. Or, like the other endpoints do, process the variant as a `delins`.

**Comment by PeteCausey-Freeman** [comment]
Oi @ifokkema .I can't remember if I fixed this or not. OOPS lol

**Comment by ifokkema** [comment]
Apparently not :wink: But this is in line with issue #328. Although I see that NN>N is not included in that list. Bummer...

**Comment by i3hsInnovation** [comment]
Haha. It's OK @ifokkema , I realised and I'm currently fixing it and making it work a little more slickly.
On it 
From @PeteCausey-Freeman

**Comment by i3hsInnovation** [comment]
Feel free to add to https://github.com/openvar/variantValidator/issues/328

If you put a full variant description example here, I will sort the necessary code

**Comment by i3hsInnovation** [comment]
OK. This is ready to close. Just need to see if there are any more examples to add to the tests.

**Comment by PeteCausey-Freeman** [comment]
Closing for now, we can add to the tests if required

**Comment by ifokkema** [comment]
Adding this style of variant to my test list that I'll later send to you, so we can sort it.
