### ISSUE TITLE
Add gene to transcript searching with HGNC ID

### ISSUE THREAD

**Issue by i3hsInnovation** [openvar/variantValidator#323]
**Feature request**
Currently gene2transcripts only accepts transcript ID and gene symbol

**Describe the solution you'd like**
Add support for HGNC ID

**Describe alternatives you've considered**
Also do we need to make LRG transcript, LRG gene and Ensembl transcript work????????

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/cc97c7d42374f877602a4efe68cf1160c2ecbc1c

**Comment by PeteCausey-Freeman** [comment]
Now completed
