### ISSUE TITLE
Restrict gene2transcripts output for just a single transcript

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#325]
Sorry if this was reported before, I think we did discuss it, but I can't find it right now.

gene2transcripts is a great resource to discover transcripts and the related information. However, when I want to just get some info on one transcript, I get all this gene's transcripts. For large genes, this results in waiting time and a very large file to parse.

E.g. https://rest.variantvalidator.org/VariantValidator/tools/gene2transcripts/NM_004006.3?content-type=application%2Fjson

It would be great if gene2transcripts would just restrict the output if I pass a transcript ID. I can always use the fetched gene ID to query again if I want to see the other transcripts. If you want to be fully backward compatible, then it would be great if there would be some flag to turn on or off.

**Comment by PeteCausey-Freeman** [comment]
This is something that should be pretty easy to achieve. I'll add it to the next release of the VV app and the rest API

**Comment by PeteCausey-Freeman** [comment]
Needs to be updated in the REST API

**Comment by PeteCausey-Freeman** [comment]
Still don't have a working dev server so will make this live ASAP
