### ISSUE TITLE
Updating the end year in copyright year ranges

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#327]
VariantValidator web pages display a copyright statement at the foot of the page, _e.g._ "Copyright © 2016-2021 VariantValidator Contributors". The start date (2016) is fixed but the end date needs to update to the current year, currently 2022.

This could be automated using a simple inline script in the HTML markup, _viz._
```
<html>
<head>
</head>
<body>
<p>Copyright &copy; 2016-<script>document.write(new Date().getFullYear())</script> VariantValidator Contributors</p>
<p>Copyright &copy; 2016-<script>document.write(new Date().getUTCFullYear() );</script> VariantValidator Contributors</p>
</body>
</html>
```

**Comment by PeteCausey-Freeman** [comment]
Should now be completed and will show up on the next release
