### ISSUE TITLE
Speeding up batch jobs

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#337]
**The nature of the problem**
Jobs that require the validation of large numbers of variants are often slow, especially when the submitted variants are described in the context of a genomic reference sequence and where the variant might map onto several transcripts.

Increasing the amount of RAM on the LAMP servers has made some improvement, but can still leave large jobs taking a day, or more, to complete. The crux of the problem is that the current LAMP servers were never intended for compute-intensive tasks.

**A potential solution**
A potential solution might be to still have batch jobs submitted via the existing LAMP, but then being shuffled off to another processor that is intended for compute-intensive tasks (ALICE) for the real number crunching. The results would then be returned to the LAMP for return to the user.

**Comment by PeteCausey-Freeman** [comment]
What I have done is added 2 additional processors to the tool. We will monitor this. If we need more, I believe we can request up to 10 in total. Currently running on 6
