### ISSUE TITLE
No change/wildtype variant syntax incorrectly prefixed with reference sequence

### ISSUE THREAD

**Issue by loeswerkman** [openvar/variantValidator#339]
When sending the variant [NM_004006.2:c.123=](https://rest.variantvalidator.org/VariantValidator/variantvalidator/hg19/NM_004006.2%3Ac.123%3D/NM_004006.2?content-type=application%2Fjson) in for validation, its description is changed from c.123= to c.123C=. This seems to be in conflict with the [HGVS recommendations](http://varnomen.hgvs.org/recommendations/DNA/variant/other/) for wild types, (and thus also conflicts with the approach of LOVD).

**Comment by PeteCausey-Freeman** [comment]
Agreed, this was old thinking. Will fix for next release

**Comment by PeteCausey-Freeman** [comment]
This is now almost fixed. It took 5 minutes to adjust the code and a full day to modify the truth-set because we have so many tests for this type of variant :P

**Comment by ifokkema** [comment]
> This is now almost fixed. It took 5 minutes to adjust the code and a full day to modify the truth-set because we have so many tests for this type of variant :P

Ohhh terrible :(
Thanks for fixing it!

**Comment by PeteCausey-Freeman** [comment]
Haha. 
Always the way. Will; push this up in the next release
