### ISSUE TITLE
Supporting circular genomes

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#351]
**Describe the bug**
For circular genomes, like the mitochondrial genome, it is suggested that specifying ranges like `m.1000_100` is allowed. These ranges should then be interpreted as "1000 to end of reference sequence" and "start of reference sequence to 100", combined.

As often, the HGVS website is super vague about this.
One [source](http://varnomen.hgvs.org/recommendations/DNA/variant/deletion/) that describes that this is allowed; states;
> the “position(s)_deleted” should be listed from 5’ to 3’, e.g. 123_126 not 126_123.
> **exception**
> when a circular genomic reference sequnce is used (“o.” and “m.” prefix) nucleotide positions may be listed from 3’ to 5’ when the deletion includes both the last and first nucleotides of the reference sequence

Another [source](http://varnomen.hgvs.org/recommendations/open-issues/#circular) disputes this;
> July 19 (2016) - (...) How should one describe a variant involving the “first” and “last” nucleotides of the circular molecule? For now the suggestion is to describe the variant as m.[1del;16569del]. The question is whether m.16569_1del should be allowed (NOTE: includes an exception to the rule that in Y_Xdel X should be smaller then Y). Do you have a suggestion??

I tried in VV to submit `chrM:m.1000_100del`, but this failed;
> Unable to validate the submitted variant chrM:m.1000_100del against the GRCh37 assembly. The following warnings were returned:
> Interval end position 100 < interval start position 1000

**To Reproduce**
[Variant Validator REST API](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh37/chrM%3Am.1000_100del/all?content-type=application%2Fjson).

**Expected behavior**
If indeed `m.1000_100del` is HGVS, then VV should support this. If not, I will open an issue that the HGVS website should be fixed.

**Comment by leicray** [comment]
There are two issues here.

First, the HGVS web site information needs to be updated to clarify the guidance.

The second is that VV needs to be modified to accept m.1000_100del as being valid. In doing so, we have to rely on the submitter having typed the description correctly, and not having intended the description to be m.100_1000del.

**Comment by PeteCausey-Freeman** [comment]
@ifokkema , @leicray , I guess we need to allow this and assume that the user has correctly added the range. We can warn that start > end every time to prompt the user to look. 

I am not fully sure if VV can actually handle this or not, but if we reach a consensus I will certainly try

**Comment by PeteCausey-Freeman** [comment]
Couple of comments. chrM:m.1000_100del is not a valid HGVS. There are 2 mito genome builds and the GRCh37  mito build is NOT the same as the hg19 mito build. So chrM:m.1000_100del hg19 != chrM:m.1000_100del GRCh37. So we must warn that a valid reference sequence had not been provided. We can however find this because I have the relevant reference sequences. So, step 1 is to sort the reference sequence

**Comment by ifokkema** [comment]
> Couple of comments. chrM:m.1000_100del is not a valid HGVS. There are 2 mito genome builds (...) So we must warn that a valid reference sequence had not been provided.

This is true always. `chr1:g.1000del` is also not valid because hg19/GRCh37 != hg38/GRC38. So this is the same in all situations. However, since the user *must* choose a reference build, you know what reference sequence to use. The only thing special about chrM is that hg19 != GRCh37. So you can choose to warn users selecting hg19 that they have *not* selected the same chromosome as present in GRCh37, and vice versa. But honestly, I think that's optional. On our side, we decided to prevent issues by always requesting GRCh37 instead of hg19. But if somebody actually asks for hg19 and chrM, well, then they get NC_001807.4. Will they select GRCh37, then they get NC_012920.1.

**Comment by PeteCausey-Freeman** [comment]
Oh, sorry, this was just my working. Writing thoughts as I go. I am aware of this. Still need to check what variants like chr1:g.1000del do but needed to eat ;P

**Comment by PeteCausey-Freeman** [comment]
OK, so this will be corrected to NC_000001.10:g.1000del. So the same should apply to the mito variant. Job 1, find out why this has been missed and not converted

**Comment by PeteCausey-Freeman** [comment]
@ifokkema and @leicray 

We have a problem here

```json
{
    "flag": "warning",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
        "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
        "vvdb_version": "vvdb_2021_4",
        "vvseqrepo_db": "VV_SR_2021_2/master",
        "vvta_version": "vvta_2021_2"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "annotations": {},
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh37",
        "submitted_variant": "M:m.1000_100del",
        "transcript_description": "",
        "validation_warnings": [
            "This is not a valid HGVS variant description, because no reference sequence ID has been provided, instead use NC_012920.1:m.1000_100del",
            "The input positions are valid but we cannot currently normalize variants spanning the origin of circular reference sequences" # This is the problem!!!!
        ],
        "variant_exonic_positions": null
    }
}
```

**Comment by leicray** [comment]
I agree that it's not a simple fix.

What percentage of mitochondrial variants are likely to span the origin?

**Comment by ifokkema** [comment]
> Still need to check what variants like chr1:g.1000del do (...)

Ah, but that's a side issue that somehow popped up here, right? It's not related to the original issue, or is it?


> (...) but needed to eat ;P

Haha always food first, think later :yum: 


> OK, so this will be corrected to NC_000001.10:g.1000del.

That's good though, right?


> We have a problem here
> 
>             "The input positions are valid but we cannot currently normalize variants spanning the origin of circular reference sequences" # This is the problem!!!!
> 
> Really don't know what we can do to fix this in the short term. It's likely to be a major fix that will involve biocommons etc and will need funding

OK, no worries then. A warning like this is fine. We can implement the same then on our side, recognizing it but not allowing this type of variant for validation by VV.


> What percentage of mitochondrial variants are likely to span the origin?

That's a good question. We don't actually have one in the GV shared LOVD instance.

**Comment by PeteCausey-Freeman** [comment]
> That's good though, right?

Yes, but I thought it was not working for M:m., but it was. Just didn't look like it until I produced the warning

> OK, no worries then. A warning like this is fine. We can implement the same then on our side, recognizing it but not allowing this type of variant for validation by VV.

I will open a new issue for this because it is something we need to think about, but I'm not entirely clear how it might be done without some serious thought.

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/issues/366

**Comment by PeteCausey-Freeman** [comment]
Commits made. Will push shortly
