### ISSUE TITLE
Supporting o. prefix

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#352]
**Describe the bug**
According to the [HGVS varnomen website](http://varnomen.hgvs.org/recommendations/general/), `o.` is a valid prefix for a circular genome (like the mitochondria, even though that uses `m.` as an exception).
I assume this different prefix, meant to indicate the reference sequence is circular, makes other exceptions possible (see #351). However, VV does not recognize it.

**To Reproduce**
[The REST API](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh37/NC_012920.1%3Ao.100_1000del/all?content-type=application%2Fjson) returns:
> NC_012920.1:g.o.100_1000del: char 14: expected one of (, ?, or a digit

The API seems to prefix the variant with a g., and then get confused.

**Expected behavior**
VV should support the `o.` prefix (assuming it's valid), or at the very least recognize it. I'm not sure if circular DNA can be told apart from linear reference sequences. I am unaware of a list of circular reference sequences.

**Comment by leicray** [comment]
There are two syntax errors in NC_012920.1:g.o.100_1000del

There should only be one sequence-type prefix after the colon, but this description has two (g. and o.). In addition, the prefix should be m. because NC_012920.1 is the Revised Cambridge Reference Sequence for the human mitochondrial genome.

An attempt was made, some time ago, to retire the m. prefix and to recommend the use of g. instead, but the mitochondrial community objected so much that the change was never implemented.

The variant description NC_012920.1:m.100_1000del validates correctly and NC_012920.1:g.100_1000del auto-corrects to NC_012920.1:m.100_1000del.

When NC_012920.1:o.100_1000del is submitted, the auto-correct procedure changes the description , for some reason, to NC_012920.1:g.o.100_1000del prior to validation which then fails with an error message. This is clearly a bug that needs to be fixed.

I think that the purpose of the o. prefix is for use in non-human sequence variant descriptions for circular genome other than the mitochondrial genome. Those that come to mind include most bacterial genomes and chloroplast genomes.

**Comment by ifokkema** [comment]
> There should only be one sequence-type prefix after the colon, but this description has two (g. and o.). In addition, the prefix should be m. because NC_012920.1 is the Revised Cambridge Reference Sequence for the human mitochondrial genome.

Right, I should have mentioned that the `g.` was added by VV. I submitted only `NC_012920.1:o.100_1000del`.


> An attempt was made, some time ago, to retire the m. prefix and to recommend the use of g. instead, but the mitochondrial community objected so much that the change was never implemented.

I remember this, indeed. We had done some work on this as well, but then stopped when the plans were canceled.


> The variant description NC_012920.1:m.100_1000del validates correctly and NC_012920.1:g.100_1000del auto-corrects to NC_012920.1:m.100_1000del.

I suppose `o.100_1000del` should also correct to `m.100_1000del`. It's nice that VV realizes that `NC_012920.1` requires the `m` prefix, but then the `o` should be recognized to be autocorrected.

**Comment by PeteCausey-Freeman** [comment]
@ifokkema, just to make sure I am clear, if we see a mito chromosome, we update o. to m. right? Can easily do that.

I am not aware of any other circular genome sequences for human as yet, but we can allow o., convert it to g. for processing, then convert it back to o. post processing should it ever be needed

**Comment by PeteCausey-Freeman** [comment]
OK, here are my working corrections

```json
{
    "flag": "mitochondrial",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
        "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
        "vvdb_version": "vvdb_2021_4",
        "vvseqrepo_db": "VV_SR_2021_2/master",
        "vvta_version": "vvta_2021_2"
    },
    "mitochondrial_variant_1": {
        "alt_genomic_loci": [],
        "annotations": {},
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_012920.1:m.100_1000del",
                "vcf": {
                    "alt": "G",
                    "chr": "M",
                    "pos": "97",
                    "ref": "GCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTAATTAATTAATGCTTGTAGGACATAATAATAACAATTGAATGTCTGCACAGCCACTTTCCACACAGACATCATAACAAAAAATTTCCACCAAACCCCCCCTCCCCCGCTTCTGGCCACAGCACTTAAACACATCTCTGCCAAACCCCAAAAACAAAGAACCCTAACACCAGCCTAACCAGATTTCAAATTTTATCTTTTGGCGGTATGCACTTTTAACAGTCACCCCCCAACTAACACATTATTTTCCCCTCCCACTCCCATACTACTAATCTCATCAATACAACCCCCGCCCATCCTACCCAGCACACACACACCGCTGCTAACCCCATACCCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTACACATGCAAGCATCCCCGTTCCAGTGAGTTCACCCTCTAAATCACCACGATCAAAAGGAACAAGCATCAAGCACGCAGCAATGCAGCTCAAAACGCTTAGCCTAGCCACACCCCCACGGGAAACAGCAGTGATTAACCTTTAGCAATAAACGAAAGTTTAACTAAGCTATACTAACCCCAGGGTTGGTCAATTTCGTGCCAGCCACCGCGGTCACACGATTAACCCAAGTCAATAGAAGCCGGCGTAAAGAGTGTTTTAGATCACCCCCTCCCCAATAAAGCTAAAACTCACCTGAGTTGTAAAAAA"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_012920.1:m.100_1000del",
                "vcf": {
                    "alt": "G",
                    "chr": "M",
                    "pos": "97",
                    "ref": "GCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTAATTAATTAATGCTTGTAGGACATAATAATAACAATTGAATGTCTGCACAGCCACTTTCCACACAGACATCATAACAAAAAATTTCCACCAAACCCCCCCTCCCCCGCTTCTGGCCACAGCACTTAAACACATCTCTGCCAAACCCCAAAAACAAAGAACCCTAACACCAGCCTAACCAGATTTCAAATTTTATCTTTTGGCGGTATGCACTTTTAACAGTCACCCCCCAACTAACACATTATTTTCCCCTCCCACTCCCATACTACTAATCTCATCAATACAACCCCCGCCCATCCTACCCAGCACACACACACCGCTGCTAACCCCATACCCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTACACATGCAAGCATCCCCGTTCCAGTGAGTTCACCCTCTAAATCACCACGATCAAAAGGAACAAGCATCAAGCACGCAGCAATGCAGCTCAAAACGCTTAGCCTAGCCACACCCCCACGGGAAACAGCAGTGATTAACCTTTAGCAATAAACGAAAGTTTAACTAAGCTATACTAACCCCAGGGTTGGTCAATTTCGTGCCAGCCACCGCGGTCACACGATTAACCCAAGTCAATAGAAGCCGGCGTAAAGAGTGTTTTAGATCACCCCCTCCCCAATAAAGCTAAAACTCACCTGAGTTGTAAAAAA"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_012920.1:m.100_1000del",
                "vcf": {
                    "alt": "G",
                    "chr": "chrM",
                    "pos": "97",
                    "ref": "GCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTAATTAATTAATGCTTGTAGGACATAATAATAACAATTGAATGTCTGCACAGCCACTTTCCACACAGACATCATAACAAAAAATTTCCACCAAACCCCCCCTCCCCCGCTTCTGGCCACAGCACTTAAACACATCTCTGCCAAACCCCAAAAACAAAGAACCCTAACACCAGCCTAACCAGATTTCAAATTTTATCTTTTGGCGGTATGCACTTTTAACAGTCACCCCCCAACTAACACATTATTTTCCCCTCCCACTCCCATACTACTAATCTCATCAATACAACCCCCGCCCATCCTACCCAGCACACACACACCGCTGCTAACCCCATACCCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTACACATGCAAGCATCCCCGTTCCAGTGAGTTCACCCTCTAAATCACCACGATCAAAAGGAACAAGCATCAAGCACGCAGCAATGCAGCTCAAAACGCTTAGCCTAGCCACACCCCCACGGGAAACAGCAGTGATTAACCTTTAGCAATAAACGAAAGTTTAACTAAGCTATACTAACCCCAGGGTTGGTCAATTTCGTGCCAGCCACCGCGGTCACACGATTAACCCAAGTCAATAGAAGCCGGCGTAAAGAGTGTTTTAGATCACCCCCTCCCCAATAAAGCTAAAACTCACCTGAGTTGTAAAAAA"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_012920.1:m.100_1000del",
                "vcf": {
                    "alt": "G",
                    "chr": "chrM",
                    "pos": "97",
                    "ref": "GCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTAATTAATTAATGCTTGTAGGACATAATAATAACAATTGAATGTCTGCACAGCCACTTTCCACACAGACATCATAACAAAAAATTTCCACCAAACCCCCCCTCCCCCGCTTCTGGCCACAGCACTTAAACACATCTCTGCCAAACCCCAAAAACAAAGAACCCTAACACCAGCCTAACCAGATTTCAAATTTTATCTTTTGGCGGTATGCACTTTTAACAGTCACCCCCCAACTAACACATTATTTTCCCCTCCCACTCCCATACTACTAATCTCATCAATACAACCCCCGCCCATCCTACCCAGCACACACACACCGCTGCTAACCCCATACCCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTACACATGCAAGCATCCCCGTTCCAGTGAGTTCACCCTCTAAATCACCACGATCAAAAGGAACAAGCATCAAGCACGCAGCAATGCAGCTCAAAACGCTTAGCCTAGCCACACCCCCACGGGAAACAGCAGTGATTAACCTTTAGCAATAAACGAAAGTTTAACTAAGCTATACTAACCCCAGGGTTGGTCAATTTCGTGCCAGCCACCGCGGTCACACGATTAACCCAAGTCAATAGAAGCCGGCGTAAAGAGTGTTTTAGATCACCCCCTCCCCAATAAAGCTAAAACTCACCTGAGTTGTAAAAAA"
                }
            }
        },
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh37",
        "submitted_variant": "NC_012920.1:o.100_1000del",
        "transcript_description": "Homo sapiens mitochondrion, complete genome",
        "validation_warnings": [
            "Reference sequence type o. should only be used for circular reference sequences that are not mitochondrial. Instead use m."
        ],
        "variant_exonic_positions": null
    }
}
```

**Comment by PeteCausey-Freeman** [comment]
For non mito sequences 

```json
{
    "flag": "warning",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
        "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
        "vvdb_version": "vvdb_2021_4",
        "vvseqrepo_db": "VV_SR_2021_2/master",
        "vvta_version": "vvta_2021_2"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "annotations": {},
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh37",
        "submitted_variant": "NC_000001.10:o.100_1000del",
        "transcript_description": "",
        "validation_warnings": [
            "Reference sequence type o. should only be used for circular reference sequences"
        ],
        "variant_exonic_positions": null
    }
}
```

Why am I not auto correcting, because it requires a lot of additional code to check, transcript, protein or LRG or Gene sequence, if transcript is it coding or non-coding etc. In this instance prediction is definately possible, but should ideally be sorted by the user

**Comment by PeteCausey-Freeman** [comment]
@ifokkema at @leicray . Are we happy with these. If so I will add tests and close this

**Comment by leicray** [comment]
There is only so much hand-holding that we can provide for users. Go ahead and add the tests and the close it.

**Comment by ifokkema** [comment]
> @ifokkema, just to make sure I am clear, if we see a mito chromosome, we update o. to m. right? Can easily do that.

Yes, exactly. That would be for `NC_001807.*` and `NC_012920.*`.


> I am not aware of any other circular genome sequences for human as yet, but we can allow o., convert it to g. for processing, then convert it back to o. post processing should it ever be needed

Great!

> OK, here are my working corrections
> (...)
> For non mito sequences
> (...)

That makes great sense, looks good!


> Why am I not auto correcting, because it requires a lot of additional code to check, transcript, protein or LRG or Gene sequence, if transcript is it coding or non-coding etc. In this instance prediction is definately possible, but should ideally be sorted by the user

Yeah, I agree. We don't auto-correct here, either. You anyway just can't know where the error is - in the prefix or the refseq.
