### ISSUE TITLE
Upper- and lowercase characters error message

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#357]
**Describe the bug**
Attempts to validate variant descriptions such as chr17:50198002C>A result in the error message "This not a valid HGVS description, due to characters being in the wrong case. Please check the use of upper- and lowercase characters." This behaviour is seen in the interactive and batch validators

**Expected behaviour**
Strictly speaking, this is not a valid HGVS description because "chr17" is not a valid reference sequence, but VV should handle it gracefully if the correct genome build (GRCh38) is specified. This does not look like it relates to use of upper- and lower-case characters.

**Comment by PeteCausey-Freeman** [comment]
chr17:50198002C>A is an invalid HGVS description and contains characters in the wrong case since no reference sequence IDs have lower case letters
 
So
This not a valid HGVS description = TRUE
 
due to characters being in the wrong case = TRUE

**Comment by PeteCausey-Freeman** [comment]
This is fair enough but the number of different warnings and errors being proposed is getting out of control. Sure, the variant is being handled gracefully, but VV is correct to warn that this is not correct. 

This warning was designed to capture cases of lrg_1 which of course should be LRG_1 and was designed by Ivo and co. 

I could perhaps update the warning to look for chr(case-insensitive) and warn, 

"This is not a valid HGVS variant description as a reference sequence ID has not been specified"

**Comment by leicray** [comment]
I would agree with the suggested revised warning.

**Comment by PeteCausey-Freeman** [comment]
fixed. Just testing
