### ISSUE TITLE
Strange slowness when handling incorrectly formatted descriptions (substitution to delins) when REF matches

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#372]
FYI: This has no priority whatsoever.

**Describe the bug**
During our comparison tests for invalid syntax recognition, one of the types of incorrect variant descriptions that we're testing is "VCF-style" substitutions, like AA>C that should be delins descriptions.

I ran into a weird situation where suddenly, VV slows down and takes 26 seconds to respond.

Submitting [NC_000017.10:g.1000000_1000001AA>C](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000_1000001AA%3EC/all/all/True/False?content-type=application%2Fjson) is fast and responds quickly. Simplified JSON:

```json
{
  "NC_000017.10:g.1000000_1000001AA>C": {
    "NC_000017.10:g.1000000_1000001AA>C": {
      "g_hgvs": null,
      "genomic_variant_error": "NC_000017.10:g.1000000_1000001AA>C automapped to NC_000017.10:g.1000000_1000001delAAinsC, Removing redundant reference bases from variant description, NC_000017.10:g.1000000_1000001delAAinsC: Variant reference (AA) does not agree with reference sequence (GA)",
    }
  }
}
```

When correcting the REF (to [NC_000017.10:g.1000000_1000001GA>C](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000_1000001GA%3EC/all/all/True/False?content-type=application%2Fjson), suddenly it takes 26 seconds for a reply:

```json
{
  "NC_000017.10:g.1000000_1000001GA>C": {
    "NC_000017.10:g.1000000_1000001GA>C": {
      "g_hgvs": "NC_000017.10:g.1000000_1000001delinsC",
      "genomic_variant_error": "NC_000017.10:g.1000000_1000001GA>C automapped to NC_000017.10:g.1000000_1000001delGAinsC",
    }
  }
}
```

But it's not the processing of the delins itself, since submitting [NC_000017.10:g.1000000_1000001delGAinsC](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000_1000001delGAinsC/all/all/True/False?content-type=application%2Fjson) results in a fast reply:

```json
{
  "NC_000017.10:g.1000000_1000001delGAinsC": {
    "NC_000017.10:g.1000000_1000001delGAinsC": {
      "g_hgvs": "NC_000017.10:g.1000000_1000001delinsC",
    }
  }
}
```

Any ideas?

**Comment by PeteCausey-Freeman** [comment]
I think it'll be, amongst other things, a parsing issue. I have done some profiling and parsing descriptions into HGVS can become slow for some reason. Especially if variants end up going down pathways that require multiple parses, which is more likely for [NC_000017.10:g.1000000_1000001AA>C](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000_1000001AA%3EC/all/all/True/False?content-type=application%2Fjson) than [NC_000017.10:g.1000000_1000001delGAinsC](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000_1000001delGAinsC/all/all/True/False?content-type=application%2Fjson). 

I don't expect that this is the only answer,  but can only root out issues one at a time. 

I really want to commit time to removing the native parser and creating variant objects directly as required (i.e. in many cases I know what the variant will look like and it will always be a delins, so can bypass much of the parse logic) but no idea when I'll get the time.

Other things, could be our servers sometimes get a little stressed out. Does this replicate???

**Comment by ifokkema** [comment]
Hmmm.... not sure, since both those examples are fast (0.2 sec) and I don't think `NC_000017.10:g.1000000_1000001GA>C` parses any differently than `NC_000017.10:g.1000000_1000001AA>C`? The format is the same, just one base difference. Yet, consistently, the former takes much longer.

That said, calls to `NC_000017.10:g.1000000_1000001GA>C` now take 2.5 seconds instead of the 26 seconds from earlier, even though those 26 seconds were repeatedly measured. So, it's still definitely slower (~12x) but not as bad as earlier this week.

**Comment by PeteCausey-Freeman** [comment]
Ah, well late last week I tried a new server configuration which takes more advantage of multiprocessing and threading. Perhaps I've helped by accident :)

**Comment by PeteCausey-Freeman** [comment]
@ifokkema , what's the verdict with this? Still being slow or has it levelled to a flat 2.5 sec???

**Comment by ifokkema** [comment]
Consistently fast:
[`NC_000017.10:g.1000000_1000001delGAinsC`](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000_1000001delGAinsC/all/all/True/False?content-type=application%2Fjson):
```
real	0m0.500s
real	0m0.319s
real	0m0.443s
real	0m0.256s
real	0m0.380s
real	0m0.313s
real	0m0.264s
real	0m0.267s
real	0m0.308s
real	0m0.225s
real	0m0.227s
```

Consistently slow:
[`NC_000017.10:g.1000000GA>C`](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000GA%3EC/all/all/True/False?content-type=application%2Fjson)
```
real	0m2.764s
real	0m2.747s
real	0m2.607s
real	0m2.620s
real	0m2.484s
real	0m2.668s
real	0m2.648s
real	0m2.662s
real	0m3.784s
real	0m2.664s
real	0m2.685s
```

as well as:
[`NC_000017.10:g.1000000_1000001GA>C`](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.1000000_1000001GA%3EC/all/all/True/False?content-type=application%2Fjson)
```
real	0m2.680s
real	0m2.613s
real	0m2.591s
real	0m2.714s
real	0m2.791s
real	0m2.593s
real	0m2.729s
real	0m2.635s
real	0m2.712s
real	0m2.528s
real	0m2.667s
```

Results in the same order; cleaned except for differences and `g_hgvs` which is the same:
```json
{
    "NC_000017.10:g.1000000_1000001delGAinsC": {
      "g_hgvs": "NC_000017.10:g.1000000_1000001delinsC",
      "genomic_variant_error": null,
    },
    "flag": null
}
```
```json
{
    "NC_000017.10:g.1000000GA>C": {
      "g_hgvs": "NC_000017.10:g.1000000_1000001delinsC",
      "genomic_variant_error": "NC_000017.10:g.1000000GA>C automapped to NC_000017.10:g.1000000_1000001delGAinsC",
    },
    "flag": "genomic_variant_warning"
}
```
```json
{
    "NC_000017.10:g.1000000_1000001GA>C": {
      "g_hgvs": "NC_000017.10:g.1000000_1000001delinsC",
      "genomic_variant_error": "NC_000017.10:g.1000000_1000001GA>C automapped to NC_000017.10:g.1000000_1000001delGAinsC",
    },
    "flag": "genomic_variant_warning"
}
```

**Comment by PeteCausey-Freeman** [comment]
Hi @ifokkema. Looks like a significant improvement to me?? I didn't realise a little server optimisation might be so beneficial

**Comment by ifokkema** [comment]
> Hi @ifokkema. Looks like a significant improvement to me?? I didn't realise a little server optimisation might be so beneficial

It seems indeed that your change made the ~26 seconds down to ~2.6!
The rest could be an internal VV issue? If, perhaps, debugging the remaining slowness takes too much time, perhaps `XX>Y` variants could be routed to `delXXinsY`? Again, not that it matters a lot; this is of course syntax which is rarely used. There is no difference between `delXinsY` and `X>Y` syntax, so it's all border cases.

**Comment by PeteCausey-Freeman** [comment]
> perhaps XX>Y variants could be routed to delXXinsY? Again, not that it matters a lot; this is of course syntax which is rarely used. There is no difference between delXinsY and X>Y syntax, so it's all border cases.

This is already the pathway. There must be something slowing things. I want to do profiling but will not get time for a while. I know the repeated unnecessary parsing can be removed, what I find after that will be interesting. Fingers crossed for a RSE soon
