### ISSUE TITLE
Trial gitter as a variant chat portal which can be linked to specific issues

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#378]
**We have low web presence**
We want to increase this

**A chat forum**
Perhaps via gitter. Advantage, can be linked directly to issues for project management

**Describe alternatives you've considered**
Please provide alternatives of you think of any

**Comment by PeteCausey-Freeman** [comment]
@ifokkema 
https://gitter.im/variantValidatorDiscuss/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link
Can't seem to add you.

**Comment by ifokkema** [comment]
I think I managed to add myself :wink:
I didn't have a Gitter account yet, I'm completely new to it!

**Comment by PeteCausey-Freeman** [comment]
Nice

I used my github login . Seems quite a nice forum
