### ISSUE TITLE
Add URLs to ensembl records

### ISSUE THREAD

**Issue by sbenny1230** [openvar/variantValidator#393]
**Is your feature request related to a problem? Please describe.**
Currently the code adds links the the refseq records but when the transcript set is 'ensembl', this is currently blank. 

**Describe the solution you'd like**
The code could be adapted so that it:

Option 1: Gets the links to the ensembl records
Option 2: Continues to get the refseq records even when the transcript set is ensembl.

**Comment by Peter-J-Freeman** [comment]
Go for option 1 @sbenny1230. Ideally we want a direct link to the Ensembl web page

**Comment by leicray** [comment]
For example, the MANE Select transcript for the _COL1A1_ gene is described at:

[http://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000108821;r=17:50184101-50201632;t=ENST00000225964](http://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000108821;r=17:50184101-50201632;t=ENST00000225964)

This can be shortened to:

[https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;t=ENST00000225964](https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;t=ENST00000225964)

However, Ensembl always knows best and redirects to the longer form of the URL. For your purposes, stick with the shorter form of the URL and allow Ensembl to do whatever it wants.

**Comment by sbenny1230** [comment]
Thank you @Peter-J-Freeman and @leicray ! I'll see what I can do and let you know

**Comment by Peter-J-Freeman** [comment]
@sbenny1230 . Also be aware that for the GRCh37 transcripts, the base URL is https://grch37.ensembl.org/. Unlike RefSeq, Ensembl treats its GRCh37 data and GRCh38 data as entirely separate entities.

Thanks @leicray for the shortened URLs

**Comment by leicray** [comment]
It's worth noting that Ensembl does no appear to be very much bothered with supporting transcript versions. What's new? The MANE Select transcript for _COL1A1_ is ENST00000225964.10 so you would suppose that there are nine other previous versions.

If you try adding a version number, valid or otherwise, the browser always takes you to version 10. This suggests that it will not be possible to provide links to old versions of Ensembl transcripts within a single genome assembly.

**Comment by sbenny1230** [comment]
@leicray Yeah I noticed that, might see if there's any way to get previous versions.

Also for GRCh37 the version is usually lower.  So for _COL1A1_ and GRCh37, the latest version is 5 and for GRCH38 it's version 10. I am thinking it might be better to have the links without the version numbers as that seems to speed up the time to load up the page e.g. [https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;t=ENST00000225964](https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;t=ENST00000225964) instead of [https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;t=ENST00000225964.10](https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;t=ENST00000225964.10)

**Comment by leicray** [comment]
Omitting the version number is probably a good idea if it speeds up page loading.

I will try to find the time to take a look at how previous versions might be displayed.

**Comment by Peter-J-Freeman** [comment]
> It's worth noting that Ensembl does no appear to be very much bothered with supporting transcript versions. What's new? The MANE Select transcript for COL1A1 is ENST00000225964.10 so you would suppose that there are nine other previous versions.

Hi both. This is not quite true. Ensembl does identify the version number in the API outputs but not the inputs. To get the correct version number you need send the API query to the correct version of the API, i.e. GRCh37 or GRCh38. If you get no response, then remove the version number and send to the correct API. I do not want the version number removing and GRCh38 ensembl hit each time because the annotations will be incorrect.

Make sense?

**Comment by leicray** [comment]
I did find the time to take a look at how to view previous transcript versions in the browser interface. As far as I can see, it's simply not possible. There is a link in the left-hand panel of navigation links that is supposed to lead to the transcript history, but it only results in the current version being displayed.

I hope that access via the API works better.

**Comment by leicray** [comment]
Presumably, this means that it's only possible to view the most recent supported version of a transcript for a given genome build, and no other versions at all. How short-sighted. We should be thankful that RefSeq provides good support for viewing previous versions and allowing pairwise comparisons of particular versions that allow the user to see what has changed in the sequence and in the metadata.

Perhaps the "transcript history" link in Ensembl only works for transcripts and genomes of other species. This would be akin to human transcripts only being downloadable from Ensembl in fasta format, whereas transcripts from other species may be downloaded in EMBL format which includes all of the metadata in a format that is broadly similar to NCBI format.

**Comment by Peter-J-Freeman** [comment]
> Presumably, this means that it's only possible to view the most recent supported version of a transcript for a given genome build, and no other versions at all. 

Correct, and actually this does break the HGVS SVN reference sequence rules that all "used" versions must be permanently available.

 > Perhaps the "transcript history" link in Ensembl only works for transcripts and genomes of other species.

I have never really figured out what it is for

**Comment by Peter-J-Freeman** [comment]
How are we doing with this issue @sbenny1230 . Can we close?

**Comment by sbenny1230** [comment]
Hi, so I've kept the version number in the URL and it should hopefully be going to the correct API too. If there is a case where VariantValidator gets a previous version (not the latest version of the transcript) the Ensembl URL does automatically redirect to the latest but I think there isn't anything to be done about that for the moment

I'm happy to close this!
