### ISSUE TITLE
Django running in debug mode

### ISSUE THREAD

**Issue by jethror1** [openvar/variantValidator#397]
I followed the link to verify my email address and had an error page returned (although my email address was actually verified) and it looks like you're running Django in production with `debug=True` set as this is the page I got:

![image](https://user-images.githubusercontent.com/45037268/179779487-2344a009-3058-44bb-8637-22241a65cf11.png)

I'm assuming this isn't intentional on the main production instance of variant validator?

**Comment by Peter-J-Freeman** [comment]
No, Django should not be running in debug mode. Thanks for the spot. 

Can I confirm, you tried to re-verify your email address even though it is already verified? Can you describe how you did this so I can replicate and see what's happening please?

**Comment by Peter-J-Freeman** [comment]
That's really odd. Not sure how to debug it. 

Perhaps the best way is to create some "fake" users on my dev version and see if I can replicate it. I'll keep this open. 

Can't get to it for the next couple of weeks, but will take a look in august

**Comment by Peter-J-Freeman** [comment]
OK, this ought to be solved. Debug mode switched off. Thanks
