### ISSUE TITLE
REST API returns a warning using 'hg38' as genome build

### ISSUE THREAD

**Issue by beboche** [openvar/variantValidator#41]
The REST API returns the following warning:

"Invalid genome build has been specified. Automap has selected the default build (GRCh38)"
When using 'hg38' as genome build like in:
https://rest.variantvalidator.org:443/variantvalidator/hg38/chr14%3Ag.88839501A%3EG/all

**Comment by PeteCausey-Freeman** [comment]
Hi @beboche beboche
Agreed. The same is not apparent for the hg19 equivalent so this is a bug
https://rest.variantvalidator.org:443/variantvalidator/hg19/chr14:g.89305845A>G/all

For now please use GRCh38 instead of hg38 while this is sorted.

**Comment by PeteCausey-Freeman** [comment]
Closed by fix #45
