### ISSUE TITLE
Liftover currently broken in the LOVD endpoint

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#430]
**Describe the bug**
Liftover is currently broken in the LOVD endpoint.

**To Reproduce**
[Checking the variant without liftover, works.](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.48275363C%3EA/refseq/all/tx/False?content-type=application%2Fjson)
[Turning liftover on, breaks the service and returns an HTTP500.](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000017.10%3Ag.48275363C%3EA/refseq/all/tx/primary?content-type=application%2Fjson)

**Comment by Peter-J-Freeman** [comment]
Sorry @ifokkema . I'll take a look on Thursday. Mad busy till then

**Comment by Peter-J-Freeman** [comment]
Can you please check this on https://restv2.variantvalidator.org/

I don't have the capacity to maintain the old build and the new build.

**Comment by Peter-J-Freeman** [comment]
My bad. Sorry. VF module had missed an update on the server. Now sorted

**Comment by ifokkema** [comment]
Excellent, thank you!
I still have a few hundred emails to go through since my trip, I hope to catch up somewhere this week!
