### ISSUE TITLE
gene2trans Server Error (500) for STAG2

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#434]
**Describe the bug**
The Genes to Transcripts tool displays a list of transcripts for a gene if the submitted gene symbol is valid. Submission of an invalid gene symbol, _e.g._ ABC123, produces the error message "Unable to recognise gene symbol ABC123"

Submission of the valid gene symbol [STAG2](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11355) produces "Server Error (500)" and results in a error warning being emailed to the system Admins. The error does not crash the server.

**To Reproduce**
1. Open the [Genes to Transcripts](https://variantvalidator.org/service/gene2trans/) tool
2. Enter the gene symbol STAG2
3. Click the Submit button

**Comment by Peter-J-Freeman** [comment]
This is weird because the code is designed to look for updated symbols etc. Will look into it

**Comment by beboche** [comment]
I can produce a list of gene symbols that trigger those Internal Server errors, if that can help:
IFNL4
KIR2DL2
KIR2DS1
KIRREL2
LYST
STAG2
SURF2
TAF10
TET2
TIMM17B
TMBIM1
TREX1

**Comment by Peter-J-Freeman** [comment]
thanks @beboche . Thats very useful. I have time for this today

**Comment by Peter-J-Freeman** [comment]
> Submission of the valid gene symbol [STAG2](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:11355) produces "Server Error (500)" and results in a error warning being emailed to the system Admins. The error does not crash the server.


There was a strange Transcript ID in the database NM_001042749.2_NG_033796.2 which was of course not being handled correctly. Possibly a UTA hangover???

**Comment by beboche** [comment]
Hi,

just found that the gene KDR also triggers an Internal Server Error while it was not the case on October, 24 (I was able to download the Genes2transcript json file at this date).

**Comment by Peter-J-Freeman** [comment]
Thanks. This is also fixed in the dev version. I will update soon

**Comment by beboche** [comment]
The same for ATF5
Thx
