### ISSUE TITLE
chr17-7578427-T-C variant format is unsupported

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#435]
**Describe the bug**
The interactive Validator tool supports various variant input formats. However it does not support chr17-7578427-T-C which results in a server error. However, if "chr" is stripped from the start of the variant description, the variant is processed correctly.

**Expected behaviour**
Support needs to be added for variant descriptions of the format chr17-7578427-T-C which some users do submit.

**Comment by Peter-J-Freeman** [comment]
Strange. It used to.

Let me check. This is likely a quick fix

**Comment by Peter-J-Freeman** [comment]
Works fine on the dev system

Try selecting a transcript. Might be a time-out. We need to improve the guidance around selecting transcripts

**Comment by Peter-J-Freeman** [comment]
When I get my new laptop I will try find time to spend improving VVweb interface bugs. Leave this open

**Comment by leicray** [comment]
The problem does appear to be a time-out. I resubmitted chr17-7578427-T-C and chose mane_select as the transcripts option. The result came back almost instantaneously.

BTW, the gene in question for this variant is TP53. No surprise then.
