### ISSUE TITLE
Validating the variant description NM_000518.5:c.89+25del generates the error message

### ISSUE THREAD

**Issue by Peter-J-Freeman** [openvar/variantValidator#441]
**Describe the bug**
Referring to https://github.com/openvar/variantValidator/issues/437

Validating the variant description NM_000518.5:c.89+25del generates the error message The entered coordinates do not agree with the intron/exon boundaries for the selected transcript which is correct, but not sufficiently informative. A clearer error message would be c.89 does not lie at an exon boundary. In addition, VV should not attempt to correct the description to NM_000518.5:c.92+22del as that might not reflect what was intended.

**Expected behavior**
The variant description NM_000518.5:c.92+80del is appropriately corrected to NM_000518.5:c.93-51del but the error message that is displayed is also The entered coordinates do not agree with the intron/exon boundaries for the selected transcript. This is misleading as c.92 does lie at an exon boundary. The problem in this instance is that intron position +80 is invalid as that position would lie beyond the centre point of the intron. A clearer error message would be The intron position is invalid.

**Comment by ifokkema** [comment]
Note that currently, you're describing two issues here;
- Intronic offset given to a base that does not lie on an exon/intron border.
- Intronic offset given that goes beyond the intron's center, so should be "swapped" to the other side.
I.e., the header "Expected behavior" actually highlights a second issue.

LOVD's VV library [has been modified](https://github.com/LOVDnl/LOVD3/pull/616/commits/897754c2c131115e3e11f042747068a6d3ee3c73) because VV doesn't currently set `flag` to `warning` for this (anymore?), but to `gene_variant` instead, suggesting the variant has just been corrected (like with the removal of a redundant suffix or simple 3' shifting). So LOVD thought this was a simple correction. Now, our library parses the given warning, recognizes the issue, and throws your "hidden" warning as an error. So when the text of that warning changes, we need to adjust our code as well.

**Comment by Peter-J-Freeman** [comment]
Thanks @ifokkema

**Comment by leicray** [comment]
Would it be too much work to display a more specific message such as `c.89 does not lie at an exon boundary`?

If it is too much work, then I agree with the suggested message.

**Comment by ifokkema** [comment]
I'm fine with either, as long as it has a common substring in the warning message that's unique to this type of issue, so I can search for it and recognize it.

**Comment by Peter-J-Freeman** [comment]
I can do something like this
"Position c.89+25 does not correspond with an exon boundary for transcript NM_000518.5. Did you mean c.92+22?"

@ifokkema . Give me a substring to put in please.

**Comment by leicray** [comment]
I would omit the "Did you mean c.92+22?" bit. It is more likely that the position of the last (or first) nucleotide of an exon has been mistyped than there being an error in the offset (+ or -) value.

**Comment by Peter-J-Freeman** [comment]
```json
{
    "flag": "warning",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.1.dev3+g6ecbf8e.d20220915",
        "variantvalidator_version": "1.0.5.dev295+g795e091.d20221025",
        "vvdb_version": "vvdb_2022_04",
        "vvseqrepo_db": "VV_SR_2022_02/master",
        "vvta_version": "vvta_2022_02"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "annotations": {},
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "rna_variant_descriptions": null,
        "selected_assembly": "GRCh38",
        "submitted_variant": "NM_000518.5:c.89+25del",
        "transcript_description": "Homo sapiens hemoglobin subunit beta (HBB), mRNA",
        "validation_warnings": [
            "ExonBoundaryError: Position c.89+25 does not correspond with an exon boundary for transcript NM_000518.5"
        ],
        "variant_exonic_positions": null
    }
}
```

??? @ifokkema

**Comment by Peter-J-Freeman** [comment]
Closing this for now. All seem happy

**Comment by ifokkema** [comment]
> @ifokkema . Give me a substring to put in please.

Anything will work - I currently have "coordinates do not agree with the intron/exon boundaries" but I see I now need to update that.


> ```json
> {
>     "validation_warning_1": {
>         "validation_warnings": [
>             "ExonBoundaryError: Position c.89+25 does not correspond with an exon boundary for transcript NM_000518.5"
>         ]
>     }
> }
> ```
> 
> ??? @ifokkema

I'll take "ExonBoundaryError" now, as it's more likely to not change in the future :wink:

**Comment by Peter-J-Freeman** [comment]
Yep, I'm trying to follow your example and include these substrings. Will take a while to work through all errors but on it

**Comment by ifokkema** [comment]
No rush! It will make things a lot easier in the future as long as those are stable, so when implemented, I'll update my library to use them. But really, there's no rush at all, as currently, I'm just using part of the actual warning strings.
