### ISSUE TITLE
Handling concatenated variant descriptions

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#442]
**Describe the bug**
Some users submit "concatenated" variant descriptions such as `NM_025135.2:c.673G>A|NC_000018.10|GRCh38|NC_000018.10:g.36594853G>A|chr18-36594853-G-A`

This generates an error message that is sent to Admin, and is presumably an error generated by the batch server.

Curiously, when that same concatenated string is submitted to the Validator web interface it does work and it appears that just the `NM_025135.2:c.673G>A` is validated. However, the error message `NM_025135.2:c.673G>A cannot be mapped directly to genome build GRCh38` is generated.

There needs to be a mechanism to trap concatenated inputs for all services.

**Comment by ifokkema** [comment]
That's basically the submission of one variant with a lot of annotation, right?
I thought the pipe was used by VV to separate multiple inputs, but this would just be additional annotation that should actually be tossed or rejected? Taking also into account that the HGVS nomenclature currently uses the pipe for valid syntax, I wouldn't try to "support" the input above, but reject it instead.

That said, the variant [`NM_025135.2:c.673G>A`](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_025135.2%3Ac.673G%3EA/all?content-type=application%2Fjson) indeed provides the warning "NM_025135.2:c.673G>A cannot be mapped directly to genome build GRCh38" although a mapping on GRCh38 is actually provided (matching the reported variant above, `NC_000018.10:g.36594853G>A`).

**Comment by Peter-J-Freeman** [comment]
This is not a bug. The description 
`NM_025135.2:c.673G>A|NC_000018.10|GRCh38|NC_000018.10:g.36594853G>A|chr18-36594853-G-A` 
is the output of clicking the ucsc web browser link. The reason this keeps coming up is that intergenic positions are not currently supported on the live server, but they will be once we roll out an update. 

This is not a VV bug, it is a VVweb bug
