### ISSUE TITLE
IUPAC X for unknown aa causing errors

### ISSUE THREAD

**Issue by Peter-J-Freeman** [openvar/variantValidator#46]
Variant descriptions like are causing errors.
NP_001119590.1:p.R175_H178delinsX
Also the warning needs to be improved for NP_001119584.1:p.K320fs*26
i.e. Non HGVS compliant variant description NP_001119584.1:p.K320fs*26 automapped to NP_001119584.1:p.Lys320fsTer.

This warning is not entirely accurate since HGVS does allow the use of the single-letter amino acid code

**Comment by leicray** [comment]
I do not think that it is correct to say that "_...HGVS does allow the use of the single-letter amino acid code..._". The general advice is to not use single-letter codes, but that's as far as it goes I think.

**Comment by Peter-J-Freeman** [comment]
Sure, but HGVS therefore does, by elimination, allow the use. This was originally from COSMIC who may be a bigger customer soon once we get ENS up and running. We can perhaps change the message to .... but recommends the use of the 3 letter aa code???

**Comment by Peter-J-Freeman** [comment]
Yes, but the single letter code is still acceptable. Please can you write an appropriate error message. Then I can update
