### ISSUE TITLE
Docker file requires update

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#481]
**Describe the bug**
The docker version of VariantValidator requires the user to specify whether it is being installed on a computer with an ARM processor, such as an APPLE M1, or a computer with the more-common Intel processor.

The setting is made in `vdb_docker.df`

Currently, this file says:

`# For Arm chips e.g. Apple M1`
`# FROM biarms/mysql:5.7`

`# For Intel chips`
`FROM mysql:5.7`

but needs to be changed to

`# For Arm chips e.g. Apple M1`
`# FROM biarms/mysql:5.7`

`# For Intel chips`
`FROM mysql:5.7-debian`

The reason for this change can be found at:
[https://stackoverflow.com/questions/72946649/dockerfile-running-from-mysql-cannot-access-apt-get](https://stackoverflow.com/questions/72946649/dockerfile-running-from-mysql-cannot-access-apt-get)

**Comment by Peter-J-Freeman** [comment]
Done. Will push up soon
