### ISSUE TITLE
A genome build is not a reference sequence

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#502]
**Describe the bug**
VariantValidator parses variant descriptions to ensure that a reference sequence is specified and that the reference sequence syntax is valid.

However, an anonymous user has attempted (twice) to submit the variant description `GRCh38:27983407:C:T`. There was no attempt to specify a chromosome number and the submissions triggered an ERROR message to sysadmin.

Errors such as this also need to be handled gracefully, with feedback to the user.

**Comment by Peter-J-Freeman** [comment]
Again, banging my head!
