### ISSUE TITLE
Submitted variant description cannot be validated as it is located in a region of the reference sequence represented by base N and not GATC

### ISSUE THREAD

**Issue by juliejurgens** [openvar/variantValidator#512]
Describe the bug
Hello, I'm attempting to validate the following deletion:  chr10(GRCh38):g.125976998_133427130del. I receive this error upon submission:
"Submitted variant description cannot be validated as it is located in a region of the reference sequence represented by base N and not GATC"

Are there any additional steps I can take to validate this variant? Or will validation not be possible? Thank you!

Screenshots
![Screen Shot 2023-06-29 at 10 04 34 AM](https://github.com/openvar/variantValidator/assets/41243189/7ad540e2-f883-4d86-a093-d9e6b9fcd2fc)

Desktop:
 - OS: Mac
 - Browser safari
 - Version 15.6.1

**Comment by Peter-J-Freeman** [comment]
This is an interesting topic. @leicray, I would have assumed this error would only come up if the break-points provided fall within NNNN sequence and not GATC sequence, however, in this case are the breakpoints in GATC sequence with NNNN sequence in the range? 

This will be an interesting edge case. N is a valid character in reference sequences, but we rarely come across instances where they need to be handled. Thanks for the report @juliejurgens. Right now I cannot advise on additional steps until I look at the code. I have limited development time for the next few weeks, but will look at this when I find some time and keep you posted

**Comment by juliejurgens** [comment]
Hi @leicray and @Peter-J-Freeman, thank you very much for looking into this. This chr10q26-qter deletion was called with the identical breakpoints denoted above in 2 unrelated individuals by genome sequencing. However, prior SNP arrays denoted slightly different deletion breakpoints in these same 2 individuals. We are including this deletion as one of a few findings identified in our genome sequencing cohort and plan to publish in Genetics in Medicine, which requires confirmation of variant annotation with VariantValidator. If there is no good way of validating this variant and no reasonable workaround, I can annotate with the nomenclature above and let the editorial team know. Just let me know what makes most sense for your team. Thank you for developing such a useful tool!

**Comment by Peter-J-Freeman** [comment]
Hi @leicray and @juliejurgens 
I have switched this validation on. 
The warning will read

```json
        "validation_warnings": [
            "This is not a valid HGVS variant description, because no reference sequence ID has been provided",
            "Submitted variant description cannot be fully validated because it spans a region of the reference sequence represented by base N and not bases GATC",
            "No transcripts found that fully overlap the described variation in the genomic sequence"
        ],
```
