### ISSUE TITLE
Incorrect reference sequence prefix case causes error

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#514]
**Describe the bug**
A user submitted a genomic variant description containing a prefix with an upper case G instead of a lower case g. This caused a server error.

The submitted variant was `chr13:G.52532513G>C` (GRCh37) and the error message was `Unable to validate the submitted variant chr13:G.52532513G>C against the GRCh37 assembly.` The corrected variant description `chr13:G.52532513G>C` validated without error.

It ought to be possible for the case of the prefix to corrected automatically.

**Comment by Peter-J-Freeman** [comment]
seriously? chr13:G.52532513G>C. I'm going to hit my head against a wall then fix it

**Comment by Peter-J-Freeman** [comment]
Done
