### ISSUE TITLE
Genes to Transcripts filtering

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#532]
**Is your feature request related to a problem? Please describe.**
The Genes to Transcripts tool is useful for identify transcripts for any given gene. It's possible to filter the transcripts returned by the tool by specifying `mane_select`, `mane`, or `select`. However, it's not possible to apply a filter that returns just the current version of each transcript.

**Describe the solution you'd like**
The list of filters ought to be extended to include a `current` option.

**Comment by Peter-J-Freeman** [comment]
The filter "all" used to do this, but we removed it to prevent server overload. It is still available as a function if admin are contacted and the workflow is described to the user :). email me @leicray
