### ISSUE TITLE
Stop codons not reported

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#535]
**Describe the bug**
Sequence variants that are predicted to create a new stop codon are not being reported correctly.

**To Reproduce**
Validate any of the the following variants
- `NC_000001.10:g.26131710C>T`
- `NC_000001.10:g.26135098C>T`
- `NC_000001.10:g.26139211C>T`

**Expected behavior**
In the case of the first variant, the expected predicted protein-level descriptions should be `NP_065184.2:p.(Arg439Ter)` and `NP_065184.2:p.(R439*)`, but are being reported as `NP_065184.2:p.(Arg439)` and `NP_065184.2:p.(R439)`.

Interestingly, variant `NC_000001.10:g.26131710C>T` maps to `NM_020451.3:c.1315C>T` and when that transcript-level variant is validated, the expected stop codons are not reported.

**Counter examples**
The variant description `NM_000088.4:c.2233A>T` does validate correctly and display the expected stop codons. Similarly with the variant description `NM_000088.4:c.2644C>T`.

**Comment by ifokkema** [comment]
Cleaning up my email, I found this bug report. I can't reproduce it, though. Could it have been fixed already? It may have been related to the work on the selenoproteins.

**Comment by Peter-J-Freeman** [comment]
Yes this is now resolved
