### ISSUE TITLE
Improve warnings for transcripts absent from UTA

### ISSUE THREAD

**Issue by Peter-J-Freeman** [openvar/variantValidator#55]
NM_001199917.2:c.871+3A>G is missing from UTA.

https://rest.variantvalidator.org/variantvalidator/GRCh38/NM_001199917.2:c.871+3A%3EG/all

{
"validation_warning_1": {
"hgvs_lrg_transcript_variant": "",
"validation_warnings": [
"Required information for NM_001199917.2 is missing from the Universal Transcript Archive, please select an alternative version of NM_001199917.2 by submitting NM_001199917.2 to  https://variantvalidator.org/ref_finder/, or select an alternative genome build"
],
"refseqgene_context_intronic_sequence": "",
"alt_genomic_loci": [],
"transcript_description": "",
"gene_symbol": "",
"hgvs_predicted_protein_consequence": {
"tlr": "",
"slr": ""
},
"submitted_variant": "NM_001199917.2:c.871+3A>G",
"genome_context_intronic_sequence": "",
"hgvs_lrg_variant": "",
"hgvs_transcript_variant": "",
"hgvs_refseqgene_variant": "",
"primary_assembly_loci": {},
"reference_sequence_records": ""
},
"flag": "warning",
"metadata": {
"variantvalidator_hgvs_version": "1.1.3",
"uta_schema": "uta_20180821",
"seqrepo_db": "2018-08-21",
"variantvalidator_version": "v0.2.4"
}
}

**Comment by PeteCausey-Freeman** [comment]
The warning is not entirely clear
"validation_warnings": [
"Required information for NM_001199917.2 is missing from the Universal Transcript Archive, please select an alternative version of NM_001199917.2 by submitting NM_001199917.2 to https://variantvalidator.org/ref_finder/, or select an alternative genome build"
],

Perhaps change to "validation_warnings": [
"Required information for NM_001199917.2 is missing from the Universal Transcript Archive, please select an alternative version of NM_001199917.2 by submitting NM_001199917.2 to https://variantvalidator.org/ref_finder/, or select an alternative genome build. Alternatively, please submit the HGNC gene symbol for transcript NM_001199917.2 to https://variantvalidator.org/ref_finder/"
],

**Comment by pnrobinson** [comment]
Hi Peter,
thank you, this warning is clearer. In practice, decrementing the version by one almost always works, and so perhaps one could check if NM_001199917.{submitter's_version minus 1} is available for the chosen genome build and suggest that. New users might not think to try another version number.

**Comment by PeteCausey-Freeman** [comment]
Agreed,

I will also add a comment to try decrementing the version number. The warning will end up being long, but in my mind, at least it will be clear so there is no problem

Thanks

Pete

**Comment by PeteCausey-Freeman** [comment]
I have chosen to simplify the warning. The new output will read

        "validation_warnings": [
            "Required information for NM_001199917.2 is missing from the Universal Transcript Archive",
            " Click https://rest.variantvalidator.org/tools/gene2transcripts/NM_001199917 for available transcripts"
        ]

This link will become active on the next release cycle

**Comment by PeteCausey-Freeman** [comment]
Bug fixed with commit
https://github.com/openvar/variantValidator/commit/1b367e5d2fc6559a3594551ac7db63947ff106b8

**Comment by PeteCausey-Freeman** [comment]
May need to look at BASE URL to direct to the correct end-point when embedded in docker or a re-written interactive web-site, so issue will remain open for now

**Comment by leicray** [comment]
I think that we need a similarly more informative warning for the interactive service.

https://variantvalidator.org/variantvalidation/?variant=NM_001198799.3%3Ac.710%2B1G%3EA&alignment=splign

This produces the warning:

"VariantValidator cannot recover the required information because it is not available in the Universal Transcript Archive"

plus the somewhat garbled advice:

"Please click the Gene to Transcripts link above insert NM_001198799.3 rather than a gene symbol, or select an alternative genome build"

The initial warning should say something like:

"VariantValidator cannot recover the required reference sequence because it is not available in the Universal Transcript Archive"

The follow-up advice should probably then say something like:

"Please click the Gene to Transcripts link above and enter the symbol for your gene of interest. This will display the available transcripts for the gene. Alternatively, select an alternative genome build or decrease the version number of the transcript reference sequence."

**Comment by Peter-J-Freeman** [comment]
@leicray . I am revisiting old issues. Looks like you reopened this one quite some time ago. Can you check whether recent naturally occuring evolution of warnings has tackled this????

**Comment by leicray** [comment]
Nearly three years have elapsed and the current version of VV now works in a different fashion. The URL that illustrates the issue has had to be modified to:

[https://variantvalidator.org/service/validate/?variant=NM_001198799.4%3Ac.710%2B1G%3EA&alignment=splign](https://variantvalidator.org/service/validate/?variant=NM_001198799.4%3Ac.710%2B1G%3EA&alignment=splign)

In addition, the contents of UTA have been updated and I have had to increment the version number to 4 which is not in the current UTA.

Validating the variant now produces two error messages which are much clearer:

- Required information for NM_001198799.4 is missing from the Universal Transcript Archive
- Query gene2transcripts with search term NM_001198799 for available transcripts

**Comment by Peter-J-Freeman** [comment]
OK, Thanks for the update. Of you are happy with the outputs, please close issue

**Comment by Peter-J-Freeman** [comment]
Ah, perhaps you cannot currently close. We need to buy a new seat on the Repo.. I'll close. We can have a chat to discuss
