### ISSUE TITLE
Incorrect warning for a deletion not conforming to the 3' rule

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#585]
**Describe the bug**
Validation of a variant description describing a deletion that does not conform to the 3' rule generates an incorrect warning.

**To Reproduce**
Validate the variant description `NM_005445.3:c.717_719del`

**Expected behaviour**
The warning that is displayed is `NM_005445.3:c.717_719del automapped to NM_005445.3:c.720_722delTGA` but should be `NM_005445.3:c.717_719del automapped to NM_005445.3:c.720_722del`.

This behaviour is observed with the interactive tool and the batch tool.

**Comment by ifokkema** [comment]
Note that https://github.com/openvar/variantValidator/issues/584 suggests the idea of tossing these "automapping" messages altogether, as they are meant for internal use only.

**Comment by leicray** [comment]
I'm not sure what you mean by "...they are meant for internal use only."

They are certainly of use to users of the interactive validator who might otherwise not understand that the validated output does not correspond to the submitted variant because of the 3' rule being applied. I would argue that the same is also true for the batch tool. The only place where it is perhaps not needed is tools whose output is intended to be solely machine-readable.

**Comment by ifokkema** [comment]
I agree that some form of warning should be shown, indicating the original input wasn't correct.

**Comment by Peter-J-Freeman** [comment]
OK, I see now why we included these warnings. I need to trim them. The thing is though that not all may be perfect.

**Comment by Peter-J-Freeman** [comment]
Fixed. Needs server update to take effect. Be patient please @leicray :)
