### ISSUE TITLE
Internal server errors

### ISSUE THREAD

**Issue by andyb3** [openvar/variantValidator#59]
Hi,

I'm getting internal server errors for the following two URLs and just wondering why:

https://rest.variantvalidator.org:443/variantvalidator/GRCh38/14-106538007-T-G/all
https://rest.variantvalidator.org:443/variantvalidator/GRCh38/14-106538008-T-C/all

Thanks!
Andy

**Comment by PeteCausey-Freeman** [comment]
Thanks Andy, I'll take a look at this now

**Comment by PeteCausey-Freeman** [comment]
Hi Andy,

VariantValidator employs some strict criteria for lifting-over between genome builds at intergenic positions. In this instance, the lift-over from GRCh37 and GRCh38 failed the quality checks, creating an un-handled exception.

This is now fixed and will be rolled out on the next release. I have fixed several minor bugs, so the new release should be along in the near future.

FYI
variant = 14-106538007-T-G
>>> print json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': '))
{
    "flag": "intergenic",
    "intergenic_variant_1": {
        "alt_genomic_loci": [],
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {
            "grch38": {
                "hgvs_genomic_description": "NC_000014.9:g.106538007T>G",
                "vcf": {
                    "alt": "G",
                    "chr": "14",
                    "pos": "106538007",
                    "ref": "T"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000014.9:g.106538007T>G",
                "vcf": {
                    "alt": "G",
                    "chr": "chr14",
                    "pos": "106538007",
                    "ref": "T"
                }
            }
        },
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "submitted_variant": "14-106538007-T-G",
        "transcript_description": "",
        "validation_warnings": [
            "No transcripts found that fully overlap the described variation in the genomic sequence"
        ]
    },
    "metadata": {
        "seqrepo_db": "2018-08-21",
        "uta_schema": "uta_20180821",
        "variantvalidator_hgvs_version": "1.1.3",
        "variantvalidator_version": "v0.2.4_post5"
    }
}

variant = 14-106538008-T-C
>>> print json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': '))
{
    "flag": "intergenic",
    "intergenic_variant_1": {
        "alt_genomic_loci": [],
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {
            "grch38": {
                "hgvs_genomic_description": "NC_000014.9:g.106538008T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "14",
                    "pos": "106538008",
                    "ref": "T"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000014.9:g.106538008T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "chr14",
                    "pos": "106538008",
                    "ref": "T"
                }
            }
        },
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "submitted_variant": "14-106538008-T-C",
        "transcript_description": "",
        "validation_warnings": [
            "No transcripts found that fully overlap the described variation in the genomic sequence"
        ]
    },
    "metadata": {
        "seqrepo_db": "2018-08-21",
        "uta_schema": "uta_20180821",
        "variantvalidator_hgvs_version": "1.1.3",
        "variantvalidator_version": "v0.2.4_post5"
    }
}

I just need to run PyTest then I will commit the changes

**Comment by andyb3** [comment]
That's great! Thanks very much for the quick response! Please feel free to close this issue

**Comment by PeteCausey-Freeman** [comment]
Resolved here
https://github.com/openvar/variantValidator/pull/60/commits/70c23cd74d677b85f527d76e351b26c4bab53292
