### ISSUE TITLE
Add a method to link to a validation result in the web interface

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#596]
**Is your feature request related to a problem? Please describe.**
I would like to send a link to a colleague that shows a validation result of a variant. I could send a link to the REST API, but that is just useful for bioinformaticians. I would like to have a link to the result on the web interface.

**Describe the solution you'd like**
There are two possible options that I see:
- Change the URL when a variant has been submitted so I can copy that, and let VV process the variant in the URL when the link is pasted into the browser address bar.
- Have the current interface generate a link and allow the user to copy it, e.g., "Copy link to this result page", or "Share this validation result", and add a simple interface that will accept that link, take the input from the URL, and submit the normal web interface form.

**Describe alternatives you've considered**
The API is the only current option that I know, that I can link to. The output, however, is only useful for bioinformaticians.

**Comment by leicray** [comment]
You have my full support for this feature request. I have often had exactly the same thoughts.

**Comment by ifokkema** [comment]
@leicray Mutalyzer has this option, and it's been really useful in the past. It would actually help promote VV, as we can just link to validation results as examples of specific issues.

**Comment by Peter-J-Freeman** [comment]
@leicray we have this no? It's what Alamut visual uses. Need to look it up?

**Comment by Peter-J-Freeman** [comment]
> You have my full support for this feature request. I have often had exactly the same thoughts.
Can you look at the URL Alamut visual puts together @leicray . Thats the method!!!!

**Comment by leicray** [comment]
It's not that simple. Alamut Visual Plus simply pops a VV window with the variant in question pre-loaded into the variant description box. It's then up to the user to scroll down to the submit button and click it. It does not generate a copyable URL AFAICS.

***@***.***

**Comment by Peter-J-Freeman** [comment]
but the URL they used is what we need

I will see if I can dig it out in my email trails

**Comment by Peter-J-Freeman** [comment]
The best we can do is a URL like

https://variantvalidator.org/service/validate/?variant=NM_000088.3:c.589G%3ET&transcripts=mane

The user then needs to select the genome build and hit submit.

It was not my design decision and I do not fully understand it, but it has somethign to do with running on AJAX

**Comment by Peter-J-Freeman** [comment]
Correction we can do

https://variantvalidator.org/service/validate/?variant=NM_000088.3:c.589G%3ET&transcripts=mane&genomebuild=GRCh37

Then the user just needs to hit Submit.

I'm seeing if there is an autosubmit option

**Comment by Peter-J-Freeman** [comment]
So, it looks like I could build in an autosubmit feature into the website. Don;t have time right now, but @ifokkema and @leicray , the URL above completes this request for now and I will update here once I get (if I can get) the autosubmit to work

**Comment by Peter-J-Freeman** [comment]
So, I managed to make it work

The format will be

http://127.0.0.1:8000/service/validate/?variant=NM_000088.3:c.589G%3ET&transcripts=mane&genomebuild=GRCh37&autosubmit=true

You will need to wait till I have time to update the servers, but we have completed the request. 

Phase 1 can be used now
https://variantvalidator.org/service/validate/?variant=NM_000088.3:c.589G%3ET&transcripts=mane&genomebuild=GRCh37

Phase 2 will be rolled out ASAP
https://variantvalidator.org/service/validate/?variant=NM_000088.3:c.589G%3ET&transcripts=mane&genomebuild=GRCh37&autosubmit=true

**Comment by Peter-J-Freeman** [comment]
is this what is requested @ifokkema and @leicray

**Comment by ifokkema** [comment]
Nice! If it auto-submits, that would be great, indeed!
Then, we need to get that link from the page somehow, e.g., by a "share this result" button or something similar. Otherwise, it would be up to the user to know the URL to use to share that specific result.

**Comment by Peter-J-Freeman** [comment]
@ifokkema. The auto submit works, I just need to complete a fiull release cycle and sadly the VV interface is the bottom of the list to make the flow correct. Hope by end of May.

**Comment by ifokkema** [comment]
No worries! It would be great to have this working, but there is no rush! I am finishing off some stuff that has been occupying my brain for too long and will continue working on the LOVD/VV interaction end of this month or May.

**Comment by Peter-J-Freeman** [comment]
Great. @John-F-Wagstaff. We need to open an issue to keep track of the things we need to do for @ifokkema. Can you please open the issue and log progress. 

I think there are a couple open e.g. https://github.com/openvar/variantValidator/issues/582

**Comment by Peter-J-Freeman** [comment]
@ifokkema you can include links like https://variantvalidator.org/service/validate/?variant=NM_000088.3:c.589G%3ET&transcripts=mane&genomebuild=GRCh37&autosubmit=true straight away, but the auto submit will just not work until the update, but it will save you needing to re-code

**Comment by ifokkema** [comment]
> @ifokkema you can include links like https://variantvalidator.org/service/validate/?variant=NM_000088.3:c.589G%3ET&transcripts=mane&genomebuild=GRCh37&autosubmit=true straight away, but the auto submit will just not work until the update, but it will save you needing to re-code

Beautiful, thanks a lot!


> also @ifokkema would you like me to build the call into the REST API ouptut?

That's actually a very nice idea - that way, whenever the URL changes on your side, you'd just have to update the API and my code does not need to contain a hardcoded URL but instead can just use whatever the API returns. I will then also be able to link to the VV results from my HGVS syntax checker interface!

**Comment by Peter-J-Freeman** [comment]
@leicray @ifokkema Is this now working. Can I close?

**Comment by leicray** [comment]
Yes, this does work for me.
