### ISSUE TITLE
LOVD Endpoint Internal Server Error

### ISSUE THREAD

**Issue by nathandloria** [openvar/variantValidator#597]
When utilizing the LOVD endpoint of the API, the following variant entry produces an internal server error (HTTP code 500):

chr7-55248999-TGGCCAGCGTGGAC-TGGCCAGCGTGGCCAGCGTGGAT

To reproduce, the following command can be run:

> curl -X 'GET' \
>   'https://rest.variantvalidator.org/LOVD/lovd/hg19/chr7-55248999-TGGCCAGCGTGGAC-TGGCCAGCGTGGCCAGCGTGGAT/all/all/False/False?content-type=application%2Fjson' \
>   -H 'accept: application/json'

I am unsure of the expected behavior but this seems to be the only variant that I have tested to cause this issue.

![Capture](https://github.com/openvar/variantValidator/assets/42869173/f2ba658c-749f-4adf-a5f1-11954bb83e38)

This could be an expected error and I am just unaware, just wanted to check and see. Thanks!

**Comment by Peter-J-Freeman** [comment]
good timing @nathandloria. We are just working on these resources. Let me get back you

**Comment by Peter-J-Freeman** [comment]
This is now corrected. Will submit a PR and will update on the next release.

**Comment by Peter-J-Freeman** [comment]
p.s. @nathandloria hope to push new changes to servers in the next couple of weeks. Going through dev at the moment. This variant is creating a bug so will error out at the moment

**Comment by nathandloria** [comment]
@Peter-J-Freeman awesome, thank you for looking into it! I appreciate the quick response. Also, this is an awesome project so thank you for the hard work.

**Comment by Peter-J-Freeman** [comment]
no problem @nathandloria. Hey, drop us a line on the https://variantvalidator.org/help/contact/ page if you fancy. Always great to hear how the tool is being used. Helps us understand our user base so we can unlock funding. 

Thanks
