### ISSUE TITLE
Add support for RefSeqFE and intergenic mappings to RefSeqGenes

### ISSUE THREAD

**Issue by Peter-J-Freeman** [openvar/variantValidator#600]
**Is your feature request related to a problem? Please describe.**
RefSeqFEs are now available

**Describe the solution you'd like**
We need to be able to map to RefSeqGenes in intergenic (between transcript regions) to make these mappings

**Comment by Peter-J-Freeman** [comment]
The code does exist and works at least for RefSeqGenes in the currend DB build. I am making a build with RefSeqFE alignments now

**Comment by Peter-J-Freeman** [comment]
```python
import json
import VariantValidator
vval = VariantValidator.Validator()
variant = 'NC_000017.11:g.50201640='
genome_build = 'GRCh38'
select_transcripts = 'all'
validate = vval.validate(variant, genome_build, select_transcripts)
validation = validate.format_as_dict(with_meta=True)
print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
```

```json
{
    "flag": "intergenic",
    "intergenic_variant_1": {
        "alt_genomic_loci": [],
        "annotations": {},
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "LRG_1:g.5000=",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "NG_007400.1:g.5000=",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000017.10:g.48279001=",
                "vcf": {
                    "alt": "C",
                    "chr": "17",
                    "pos": "48279001",
                    "ref": "C"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000017.11:g.50201640=",
                "vcf": {
                    "alt": "C",
                    "chr": "17",
                    "pos": "50201640",
                    "ref": "C"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000017.10:g.48279001=",
                "vcf": {
                    "alt": "C",
                    "chr": "chr17",
                    "pos": "48279001",
                    "ref": "C"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000017.11:g.50201640=",
                "vcf": {
                    "alt": "C",
                    "chr": "chr17",
                    "pos": "50201640",
                    "ref": "C"
                }
            }
        },
        "reference_sequence_records": {
            "lrg": "http://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_1.xml",
            "refseqgene": "https://www.ncbi.nlm.nih.gov/nuccore/NG_007400.1"
        },
        "refseqgene_context_intronic_sequence": "",
        "rna_variant_descriptions": null,
        "selected_assembly": "GRCh38",
        "submitted_variant": "NC_000017.11:g.50201640=",
        "transcript_description": "",
        "validation_warnings": [
            "No transcripts found that fully overlap the described variation in the genomic sequence"
        ],
        "variant_exonic_positions": null
    },
    "metadata": {
        "variantvalidator_hgvs_version": "2.2.0",
        "variantvalidator_version": "2.2.1.dev539+g8a3b4db.d20240412",
        "vvdb_version": "vvdb_2024_4",
        "vvseqrepo_db": "VV_SR_2024_01/master",
        "vvta_version": "vvta_2024_01"
    }
}
```

Note, the position is mapped to the RefSeqGene NG_ as hoped :)

**Comment by Peter-J-Freeman** [comment]
We can also add additional annotation of the RefSeqGene. Foe example we couls populate the
```json
        "gene_ids": {},
        "gene_symbol": "",
```

method. Look up mane transcript from Gene Symbol and pull back the stable gene id info.

If not a Gene record (i.e. is a functional element)

Pull back the information we have gathered from the FE record

Example for COL1A1 is

```json
        "gene_ids": {
            "ccds_ids": [
                "CCDS11561"
            ],
            "ensembl_gene_id": "ENSG00000108821",
            "entrez_gene_id": "1277",
            "hgnc_id": "HGNC:2197",
            "omim_id": [
                "120150"
            ],
            "ucsc_id": "uc002iqm.4"
        },
        "gene_symbol": "COL1A1",
```

For a functional element it will be something like

```json
        "gene_ids": {
            "ccds_ids": [
                ""
            ],
            "ensembl_gene_id": "",
            "entrez_gene_id": "127270644",
            "hgnc_id": "",
            "omim_id": [
                ""
            ],
            "ucsc_id": ""
        },
        "gene_symbol": "H3K27ac hESC enhancer chr1:161101327-161102150 (GRCh37/hg19 assembly coordinates)",
```

**Comment by Peter-J-Freeman** [comment]
@John-F-Wagstaff @leicray @ifokkema . Any comments please?

**Comment by Peter-J-Freeman** [comment]
We could pull in the gene symbol i.e. For NG_162137 it is LOC129929080, but this will take more code changes and does it matter enough???

**Comment by Peter-J-Freeman** [comment]
I think for consistancy we need the gene symbols. GAH. Killing the DB update code once again!!!!

**Comment by ifokkema** [comment]
I'm still catching up with my emails. I'm not fully following what this is for; is there an issue or discussion page or feature request or something else to help me understand what this is related to?

**Comment by Peter-J-Freeman** [comment]
It expands the discussion in the HGVS nomenclatue committee. 

Why would we use c. descriptions that go beyond the transcript boundary?

Because they hit promoters / enhancers etc.

This is bad practice because promoters and enhancers are not part of transcript records and have clearly defined and annotated reference sequences of their own. Sure of there is a RefSeqGene record, this can be used but for the intergenic promoters and enhancers there are now FE records, as I stated yesterday

It just so happens that VV can support these with very few code changes, so we can put together very easily outputs that provide you with the 

NG_ description for the functional element (e.g. a promoter)
A gene ID
A gene symbol / description

As you know, I like to do things correctly and sensibly (conservatively) so want to model this before the next committee meeting and show you the error of your ways ;P

**Comment by leicray** [comment]
Everything that you might need to know about accessing the RefSeqFE data in various formats can be found in:

[34876495_Supplemental_Table_S1.xlsx](https://github.com/openvar/variantValidator/files/15008246/34876495_Supplemental_Table_S1.xlsx)

**Comment by leicray** [comment]
To add to the reasons why RefSeqFE records need to be supported, consider what happens when a genomic variant is not found to be spanned by a transcript. At present, VV simply reports that that is the case and the user might suppose that the variant is not significant in the context of their disease of interest.

However, the variant might lie within a Functional Element and a significant sequence alteration (such as a large deletion) within the element might have a detrimental effect on the expression of one or more genes.

**Comment by Peter-J-Freeman** [comment]
Once the database is built I will add some examples. Getting there now. Just takes ages to spot errors since ther are >140,000 records to handle. But the code seems to be in place, so once built I think supporting these may be pretty simple. Fingers crossed.

**Comment by ifokkema** [comment]
Please correct my thinking, guys; as far as I understand it:
- RefSeqFE records use NGs;
- There are no annotated transcripts overlapping the promoters in these NGs;
- Therefore, we would not be getting any `NG(NM):c.` positions;
- Therefore, we would still not have gene-based (`c.`) descriptions of variants within a promotor;
- Therefore, this only gives us additional `NG:g.` positions besides already known `NC:g.` positions;
- Therefore, the problem that LOVD has still stands - we don't have a gene-based variant description (using `c.`) of a variant outside of the transcript. And, for us, `NC(NM):c.-1000A>T` is easier to use than `NG(NM):c.-1000A>T` since we already have the NCs in the database. But neither description is allowed by the HGVS nomenclature right now. I personally just want `c.`-based HGVS descriptions; whether the location of the promotor is indicated in the reference sequence is unknown to me, although, obviously, it would be very cool if VV understood this and could indicate this through the APIs. LOVD may then choose to adjust the RNA or protein description based on this information.

**Comment by Peter-J-Freeman** [comment]
Always worth meetign half way :)

**Comment by ifokkema** [comment]
> @ifokkema Open a feature request.

It's already there :grin:
And added to the roadmap! Another thought is to open a GitHub project for this... :thinking: Oh, never mind me messing around interfering with your way of organizing things 😂

> What we can do is add the functionality and provide warnings saying that the descriptions are not (and in my opinion should not be) HGVS compliant, but can be useful as annotative descriptions.

That also makes sense! But I'm totally fine building my own non-HGVS from it, by simply taking data from the API endpoint.

> Always worth meetign half way :)

:smile:

**Comment by Peter-J-Freeman** [comment]
@John-F-Wagstaff. The code for VV is now in place, but there are a lot of RefSeqGene records now missing from SeqRepo, so getting errors like

[{'hgvs_refseqgene': 'NG_032957.1:g.4T=', 'gene': 'LOC101056699', 'valid': "Failed to fetch NG_032957.1 from SeqRepo (/Users/user/variantvalidator_data/seqdata/VV_SR_2024_01/master) ('Alias NG_032957.1 (namespace: None)')"}]

We need to add all records from 

https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/latest_assembly_versions/GCF_000001405.40_GRCh38.p14/

Not sure where the RefSeqGene FASTA sequences are sourced from which go into SeqRepo

**Comment by Peter-J-Freeman** [comment]
It's the RefSeq FE dataset that seems to be absent in SeqRepo. This might well be them

https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/biological_region/

The prefix is NG_

**Comment by John-F-Wagstaff** [comment]
OK, that looks more like it, I have deleted the old version and started a re-build with this, but it won't solve everything.

I just went to check if NG_032957.1 got loaded into the (fatter base RSG) dataset and found it had not, so I searched RefSeq for it and got https://www.ncbi.nlm.nih.gov/nuccore/407892488 
which is not a genomic sequence or a biological region but a psudo-gene transcript, an inferred i.e. predicted  psudo-gene even, it is not in the standard Ref seq inputs and  does not exist in https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/biological_region/
either, at least if grep on the unpacked form of human.biological_region.fna.gz is to be believed. 

I think this might not be something we want to load, at all, I guess it ends up in the full alignment set we have to load now as the RSG only one got discontinued? If so we may need extra filtering on that input which is unpleasant, do you have any thoughts?

**Comment by Peter-J-Freeman** [comment]
NG_032957.1 seems to be a Pseudogene and not a Pseudogene transcript, so we should be able to load it, but agreed, I do not see why we would want to load pseudogenes. Also, as you said, it is not in the functional elements fna file, so where would it be??? So, I guess we just load the biological regions data and filter out those that have NG_ prefixes but are not in SeqRepo.

**Comment by Peter-J-Freeman** [comment]
I don;t think VVTA needs to be addrwssed since there is no alignment data required that relates to transcripts. All alignment data are used from validator db

**Comment by John-F-Wagstaff** [comment]
Well that (filtering out those that have NG_ prefixes but are not in SeqRepo) would work, and simplifies things, for now, so long as we know what we want to add to SeqRepo at least. 

Do you want the full RSG dataset i.e. including those that don't have transcripts loaded into VVTA? 

Either way on the RSG front, do you otherwise just want the contests of 
https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/biological_region/human.biological_region.fna.gz ?

If you are OK with the human.biological_region.fna (+/- the full RSG extras) then I the update is still processing but, if you give the OK, I should be able to upload it tonight, assuming it does not take too long to load, or tomorrow before lunch at the latest.

**Comment by Peter-J-Freeman** [comment]
This is now completed
