### ISSUE TITLE
VV text entry at the top of each page

### ISSUE THREAD

**Issue by Peter-J-Freeman** [openvar/variantValidator#605]
Dear Pete,

I wonder what the status is of an old request I send regarding the 
[https://urldefense.com/v3/__https://variantvalidator.org/service/validate/__;!!PDiH4ENfjr2_Jw!F1BGORuYEmJUiLJMiHce0jg4u15li-37QOOL1IxqmIgYaF4AgzaDp75izYw43uO9G0KkphRTMvH-TW5nngAvNENCc7yBkg$](https://urldefense.com/v3/__https:/variantvalidator.org/service/validate/__;!!PDiH4ENfjr2_Jw!F1BGORuYEmJUiLJMiHce0jg4u15li-37QOOL1IxqmIgYaF4AgzaDp75izYw43uO9G0KkphRTMvH-TW5nngAvNENCc7yBkg$) [variantvalidator[.]org] page.

I use this page a lot and asked whether it would be possible to put on 
the results page the option to query with a new "Variant Description:" 
not at the bottom but at the top of the page. You replied to my request, 
have to dive into the archive to find it, but nothing changed.

When you use the page to check several descriptions it is rather 
annoying that every time you have to scroll down to the bottom of the 
page to start a next query. Please ad the query box to the top of the 
page (and you do not need to repeat all suggestions, the section from 
Input Variant Description... to ...chr17(GRCh38):g.50198002C>A).

Best regards,

        Johan

**Comment by leicray** [comment]
This issue appears to be resolved. However, the drop-down menu for selecting transcripts does not correspond with the text list further down the page of possible transcript options.

The drop-down menu offers the four options:
- mane
- select
- mane_select
- current

The text-based list of transcript options offers the five options:
- raw
- mane_select
- mane
- select
- refseq_select

It's not clear what "current" means and there is no way to select "raw" or "refseq_select". This should be fixed to prevent user confusion.

**Comment by leicray** [comment]
My mistake, or do I mean _mea culpa_?

When I click within the Select Transcripts box I am shown a list of possible entries that are probably cached in my browser.

However, a proper drop-down menu would be better.

**Comment by Peter-J-Freeman** [comment]
Can't do a drop-down though because users van add in transcript IDs or | concatenated lists of IDs so we need free text. There may be a jsvascript form that could be used to populate the web form. As in, you can select from a dropdown and add in free text when required. Will take a look at possible options

**Comment by Peter-J-Freeman** [comment]
how about something like this?

![image](https://github.com/openvar/variantValidator/assets/26568889/72eb9204-09a6-4a63-a4a2-9f9d28d04bf5)

Seems to also cache some of your recent entries

**Comment by leicray** [comment]
That looks good.

Is it possible to have explanatory "tool-tips" appear when the mouse cursor is over an option. If so, the explanations of each selection option could be removed from below the variant description examples.

**Comment by Peter-J-Freeman** [comment]
I'll ask dr GTP :)

**Comment by leicray** [comment]
Looks good, but I would change the first "Select" to "Choose" to avoid having "Select" appear twice in the pop-up which, perhaps, would be confusing for some users. I would also change "transcript" to "transcripts".

And finally, can the pop-up me made less stark, but still legible, by having a mid-grey background rather than black?

**Comment by Peter-J-Freeman** [comment]
Changes pushed to server for review. Thanks @leicray . Will close this after acceptance
