### ISSUE TITLE
No warning that transcript version is not the most recent

### ISSUE THREAD

**Issue by leicray** [openvar/variantValidator#624]
**Describe the bug**
When a transcript-based variant description is submitted that is based on an old transcript version, there ought to be a warning that the transcript version is not the most recent. This feature not longer works.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Validator
2. Select the top-most example variant description: `NM_000088.3:c.589G>T`
3. Select `GRCh38 (hg38)`
4. Click the Submit button
5. Notice that there is warning

**Expected behavior**
There should be a warning that `NM_000088.3` is not the most recent version of that transcript.

**Comment by Peter-J-Freeman** [comment]
This is fixed. Just waitint to be rolled out
