### ISSUE TITLE
Update SimpleVariantFormatter to handle hybrid descriptions

### ISSUE THREAD

**Issue by John-F-Wagstaff** [openvar/variantValidator#639]
**Current Limitation**
SimpleVariantFormatter has issues with hybrid psudo-vcf type descriptions due to it's origin as a simpler formatting tool, but sometimes it would be useful to be able to submit at least a few more types of non standard description.

**Suggested addition**
Handling psudo-vcf type descriptions like chr17:50198002C>A as well a 17:50198002C>A through this endpoint.

**Alternative solutions**
We could otherwise submit to the core VariantValidatior, but this is overkill for our current needs and adds significant, undesirable,  overhead to the validation.

**Comment by Peter-J-Freeman** [comment]
Now completed. 

https://rest.variantvalidator.org/LOVD/lovd/GRCh38/chr9%3A133449833T%3EC/all/all/False/True?content-type=application%2Fjson

Should now handle any genomic variant that VV can handle
