### ISSUE TITLE
Alignment issue with NM_017680.6

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#651]
**Describe the bug**
Originally reported by @mihailefter.
VariantValidator doesn't handle the mapping well from transcript to genome around a gap in `NM_017680.6`.

Bases `NC_000009.12:g.92474743_92474745` are not present in `NM_017680.6`.
[`NC_000009.12:g.92474743_92474745del` => `NM_017680.6:c.151_153=`](https://rest.variantvalidator.org/LOVD/lovd/GRCh38/NC_000009.12%3Ag.92474743_92474745del/all/NM_017680.6/tx/False?content-type=application%2Fjson).
Therefore, submitting `NC_000009.12:g.92474742C>A` returns `NM_017680.6:c.153delinsTGAT` on both the [LOVD endpoint](https://rest.variantvalidator.org/LOVD/lovd/GRCh38/NC_000009.12%3Ag.92474742C%3EA/all/NM_017680.6/tx/False?content-type=application%2Fjson) and the [VV endpoint](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NC_000009.12%3Ag.92474742C%3EA/NM_017680.6?content-type=application%2Fjson). This is as I expect.
However, when we submit `NM_017680.6:c.153G>T` (the "dumb" version of the genomic C>A) to the [VV endpoint](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_017680.6%3Ac.153G%3ET/NM_017680.6?content-type=application%2Fjson), the genomic mapping is `NC_000009.12:g.92474742C>A`, which is incorrect.

**To Reproduce**
See above.

**Expected behavior**
I expect to see `NC_000009.12:g.92474742delinsATCA`. However, when I submit that variant to the [LOVD endpoint](https://rest.variantvalidator.org/LOVD/lovd/GRCh38/NC_000009.12%3Ag.92474742delinsATCA/all/NM_017680.6/tx/False?content-type=application%2Fjson), I get `NM_017680.6:c.153delinsTGAT` back, the mapping earlier linked to the input `NC_000009.12:g.92474742C>A`. I had expected to see `NM_017680.6:c.153G>T`, instead.

**Additional context**
Notes: this gene is on the reverse strand, and the gap is within a repeat region. I suspect the gap isn't fully justified in both directions while applying the variant.

**Comment by ifokkema** [comment]
> (...)
> variant = "NC_000009.12:g.92474743_92474745del"
> (...)
> 
> Gives
> 
> ```json
> {
>     "NM_017680.6:c.151_153=": {
>         "primary_assembly_loci": {
>             "grch37": {
>                 "hgvs_genomic_description": "NC_000009.11:g.95237066_95237068del"
>             },
>             "grch38": {
>                 "hgvs_genomic_description": "NC_000009.12:g.92474784_92474786del"
>             }
>         }
>     }
> }
> ```
> 
> Which is correct

I suddenly realize that `NM_017680.6:c.151_153=` is kind of arbitrary to indicate that a three-nucleotide deletion on the genome has no effect on the transcript. I mean, why indicate on the transcript that _three_ nucleotides haven't changed? 

If repeat `(...)GATGATGATGAG` is unchanged on the transcript (the genome has one `GAT` extra), why would VV indicate that the `GAG` is unchanged? That is what `c.151_153` is. Why not indicate that the last `AG` is unchanged (the flanking bases of where the insertion would have otherwise occurred) or indicate that the entire `GAT`-repeat is unchanged, possibly with flanking bases?

When testing, I submitted a slightly longer variant, which [incorrectly also returned `NM_017680.6:c.151_153=`](https://rest.variantvalidator.org/LOVD/lovd/GRCh38/NC_000009.12%3Ag.92474743_92474748del/refseq/NM_017680.6/tx/False?content-type=application%2Fjson).
So, something is fishy there, too.


> ```json
>         "hgvs_transcript_variant": "NM_017680.6:c.153G>T",
>         "primary_assembly_loci": {
>             "grch37": {
>                 "hgvs_genomic_description": "NC_000009.11:g.95237024C>A"
>             },
>             "grch38": {
>                 "hgvs_genomic_description": "NC_000009.12:g.92474742C>A"
>             }
>         }
> ```
> Which is not correct. Should be a genomic delins of `NC_000009.12:g.92474742delinsATCA`
> 
> @ifokkema please confirm this is the first issue.

Yes, I confirm, the result should not be `NC_000009.12:g.92474742delinsATCA`.

**Comment by Peter-J-Freeman** [comment]
> I suddenly realize that NM_017680.6:c.151_153= is kind of arbitrary to indicate that a three-nucleotide deletion on the genome has no effect on the transcript. I mean, why indicate on the transcript that three nucleotides haven't changed?

This is internal and. preference. We state the "tested" bases. We try not to return c.= because this may falsely report that the entire c. is unaffected. We are only talking about specific bases. It is HGVS compliant as I understand it so will not change. 

> Yes, I confirm, the result should not be NC_000009.12:g.92474742delinsATCA. 

fixed this so far. Workinng on getting NC_000009.12:g.92474742delinsATCA back to NM_017680.6:c.153G>T at the moment

Will then look at [incorrectly also returned NM_017680.6:c.151_153=](https://rest.variantvalidator.org/LOVD/lovd/GRCh38/NC_000009.12%3Ag.92474743_92474748del/refseq/NM_017680.6/tx/False?content-type=application%2Fjson)..

Will be fixed in stages and reported back ready for testing by you @ifokkema . Please add additiional comments as required here

**Comment by Peter-J-Freeman** [comment]
> Oh, I agree that c.= is bad, but my point is that these are not the tested bases... These are three (why three?) bases after the repeat sequence. Shouldn't the repeat sequence be considered as tested, perhaps with two flanking nucleotides?

It covers the span of the region tested. In this case, the variant is on the flank, so call it position 1. The inserted/deleted bases are between the next 2 bases. So overall these are the c. bases tested to make the variant, i.e. compared to the genomic. We use it internally for testing as well, so very reluctant to re-write ~1000 tests :)

**Comment by Peter-J-Freeman** [comment]
```python
import json
import VariantValidator
vval = VariantValidator.Validator()
variant = "NC_000009.12:g.92474742delinsATCA"
genome_build = 'GRCh38'
select_transcripts = 'NM_017680.6'
transcript_set = 'refseq'
validate = vval.validate(variant, genome_build, select_transcripts, transcript_set)
validation = validate.format_as_dict(with_meta=True)
print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
```

```json
{
    "NM_017680.6:c.153G>T": {
        "alt_genomic_loci": [
            {
                "grch38": {
                    "hgvs_genomic_description": "NW_025791788.1:g.309472C>A",
                    "vcf": {
                        "alt": "A",
                        "chr": "HG1012_PATCH",
                        "pos": "309472",
                        "ref": "C"
                    }
                }
            },
            {
                "hg38": {
                    "hgvs_genomic_description": "NW_025791788.1:g.309472C>A",
                    "vcf": {
                        "alt": "A",
                        "chr": "NW_025791788.1",
                        "pos": "309472",
                        "ref": "C"
                    }
                }
            }
        ],
        "annotations": {
            "chromosome": "9",
            "db_xref": {
                "CCDS": null,
                "ensemblgene": null,
                "hgnc": "HGNC:14872",
                "ncbigene": "54829",
                "select": "MANE"
            },
            "ensembl_select": false,
            "mane_plus_clinical": false,
            "mane_select": true,
            "map": "9q22.31",
            "note": "asporin",
            "refseq_select": true,
            "variant": "1"
        },
        "gene_ids": {
            "ccds_ids": [],
            "ensembl_gene_id": "ENSG00000106819",
            "entrez_gene_id": "54829",
            "hgnc_id": "HGNC:14872",
            "omim_id": [
                "608135"
            ],
            "ucsc_id": "uc004ase.3"
        },
        "gene_symbol": "ASPN",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "NP_060150.4:p.(E51D)",
            "tlr": "NP_060150.4:p.(Glu51Asp)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "NM_017680.6:c.153G>T",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000009.11:g.95237024delinsATCA",
                "vcf": {
                    "alt": "ATCA",
                    "chr": "9",
                    "pos": "95237024",
                    "ref": "C"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000009.12:g.92474742delinsATCA",
                "vcf": {
                    "alt": "ATCA",
                    "chr": "9",
                    "pos": "92474742",
                    "ref": "C"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000009.11:g.95237024delinsATCA",
                "vcf": {
                    "alt": "ATCA",
                    "chr": "chr9",
                    "pos": "95237024",
                    "ref": "C"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000009.12:g.92474742delinsATCA",
                "vcf": {
                    "alt": "ATCA",
                    "chr": "chr9",
                    "pos": "92474742",
                    "ref": "C"
                }
            }
        },
        "reference_sequence_records": {
            "protein": "https://www.ncbi.nlm.nih.gov/nuccore/NP_060150.4",
            "transcript": "https://www.ncbi.nlm.nih.gov/nuccore/NM_017680.6"
        },
        "refseqgene_context_intronic_sequence": "",
        "rna_variant_descriptions": null,
        "selected_assembly": "GRCh38",
        "submitted_variant": "NC_000009.12:g.92474742delinsATCA",
        "transcript_description": "Homo sapiens asporin (ASPN), transcript variant 1, mRNA",
        "validation_warnings": [
            "Submitted description does not represent a true variant because it is an artefact of aligning NM_017680.6 with NC_000009.12 (genome build GRCh38)",
            "NM_017680.6 contains 3 fewer bases between c.152_153 than NC_000009.12"
        ],
        "variant_exonic_positions": {
            "NC_000009.12": {
                "end_exon": "2",
                "start_exon": "2"
            }
        }
    },
    "flag": "gene_variant",
    "metadata": {
        "variantvalidator_hgvs_version": "2.2.0",
        "variantvalidator_version": "2.2.1.dev709+g6340024",
        "vvdb_version": "vvdb_2024_8",
        "vvseqrepo_db": "VV_SR_2024_09/master",
        "vvta_version": "vvta_2024_09"
    }
}
```

Will look at that c.= position. Not sure if it is fixable if wrong

**Comment by Peter-J-Freeman** [comment]
Quickly recording this before I go to lunch. 

If we map the direct position of the c. sub we get
NC_000009.12:g.92474742C>A
NM_017680.6:c.153G>T

Will help to check the c.= positioning

**Comment by ifokkema** [comment]
> Ah, I see why now. It is because the additionl bases are absent from the transcript, so the c. = position is the bases taken into consideration when making the mappings I believe. It is not particularly easy to generate to an exact position. Perhaps we can gather a few ecamples and tweak the code, but I'm gonna be upset at fixing the tests :)

I can imagine :worried: 
I don't think I can compensate for it from my side, as I can't tell what the full range is for the repeat... Well, if, somehow, it's easier to provide more information in VV's output about the mismatch between the genome and the transcript, in theory, LOVD could recalculate the "correct" `c.?=` notation from that. But, obviously, it would be better if VV could handle that natively.

**Comment by Peter-J-Freeman** [comment]
This can be worked on. Want to get the variants workig first, then look at some of the tests we have and see if I can tweak.

**Comment by Peter-J-Freeman** [comment]
@ifokkema 

Does this look right?

```python
import json
import VariantValidator
vval = VariantValidator.Validator()
variant = "NC_000009.12:g.92474743_92474748del"
genome_build = 'GRCh38'
select_transcripts = 'NM_017680.6'
transcript_set = 'refseq'
validate = vval.validate(variant, genome_build, select_transcripts, transcript_set)
validation = validate.format_as_dict(with_meta=True)
print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
```

```json
{
    "NM_017680.6:c.150_152del": {
        "alt_genomic_loci": [
            {
                "grch38": {
                    "hgvs_genomic_description": "NW_025791788.1:g.309511_309513del",
                    "vcf": {
                        "alt": "C",
                        "chr": "HG1012_PATCH",
                        "pos": "309472",
                        "ref": "CTCA"
                    }
                }
            },
            {
                "hg38": {
                    "hgvs_genomic_description": "NW_025791788.1:g.309511_309513del",
                    "vcf": {
                        "alt": "C",
                        "chr": "NW_025791788.1",
                        "pos": "309472",
                        "ref": "CTCA"
                    }
                }
            }
        ],
        "annotations": {
            "chromosome": "9",
            "db_xref": {
                "CCDS": null,
                "ensemblgene": null,
                "hgnc": "HGNC:14872",
                "ncbigene": "54829",
                "select": "MANE"
            },
            "ensembl_select": false,
            "mane_plus_clinical": false,
            "mane_select": true,
            "map": "9q22.31",
            "note": "asporin",
            "refseq_select": true,
            "variant": "1"
        },
        "gene_ids": {
            "ccds_ids": [],
            "ensembl_gene_id": "ENSG00000106819",
            "entrez_gene_id": "54829",
            "hgnc_id": "HGNC:14872",
            "omim_id": [
                "608135"
            ],
            "ucsc_id": "uc004ase.3"
        },
        "gene_symbol": "ASPN",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "NP_060150.4:p.(D50del)",
            "tlr": "NP_060150.4:p.(Asp50del)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "NM_017680.6:c.150_152del",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000009.11:g.95237063_95237068del",
                "vcf": {
                    "alt": "C",
                    "chr": "9",
                    "pos": "95237024",
                    "ref": "CTCATCA"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000009.12:g.92474781_92474786del",
                "vcf": {
                    "alt": "C",
                    "chr": "9",
                    "pos": "92474742",
                    "ref": "CTCATCA"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000009.11:g.95237063_95237068del",
                "vcf": {
                    "alt": "C",
                    "chr": "chr9",
                    "pos": "95237024",
                    "ref": "CTCATCA"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000009.12:g.92474781_92474786del",
                "vcf": {
                    "alt": "C",
                    "chr": "chr9",
                    "pos": "92474742",
                    "ref": "CTCATCA"
                }
            }
        },
        "reference_sequence_records": {
            "protein": "https://www.ncbi.nlm.nih.gov/nuccore/NP_060150.4",
            "transcript": "https://www.ncbi.nlm.nih.gov/nuccore/NM_017680.6"
        },
        "refseqgene_context_intronic_sequence": "",
        "rna_variant_descriptions": null,
        "selected_assembly": "GRCh38",
        "submitted_variant": "NC_000009.12:g.92474743_92474748del",
        "transcript_description": "Homo sapiens asporin (ASPN), transcript variant 1, mRNA",
        "validation_warnings": [
            "Submitted description does not represent a true variant because it is an artefact of aligning NM_017680.6 with NC_000009.12 (genome build GRCh38)",
            "NM_017680.6 contains 3 fewer bases between c.152_153 than NC_000009.12"
        ],
        "variant_exonic_positions": {
            "NC_000009.12": {
                "end_exon": "2",
                "start_exon": "2"
            }
        }
    },
    "flag": "gene_variant",
    "metadata": {
        "variantvalidator_hgvs_version": "2.2.0",
        "variantvalidator_version": "2.2.1.dev709+g6340024",
        "vvdb_version": "vvdb_2024_8",
        "vvseqrepo_db": "VV_SR_2024_09/master",
        "vvta_version": "vvta_2024_09"
    }
}
```

So, the deletion g. normalises 3 prime. Spans the gap. The deletion in the g. is 6 bases. There are 3 bases less in the transcript. we seem to get from the g. to the c. and back to the g.

**Comment by Peter-J-Freeman** [comment]
@ifokkema A patch is pushed up ready for testing

**Comment by Peter-J-Freeman** [comment]
@ifokkema , can you test when you get chance and close :)

**Comment by Peter-J-Freeman** [comment]
I'll restart the server
