### ISSUE TITLE
Met1? being displayed when a variant maintains the start codon

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#86]
NC_000002.11:g.220462640G>T is a discrepancy between genome and gene apparently

see [https://github.com/biocommons/hgvs/issues/566](https://github.com/biocommons/hgvs/issues/566)

VV currently outputs Met1? which is not necessarily incorrect i we take into account that the start codon might not necessarily be Met. Met ought to be a simple case as there is no redundancy, but what about the other start codons? https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi?chapter=tgencodes#SG1.

Can we be sure that variation does not create a splice site or something.

Suggestion.
Get the sequence of the CDS c.1_3 from the reference. 
if the variant DOES NOT change the sequence then assert (aa=) otherwise assert (aa?) even if the aa remains the same!

**Comment by leicray** [comment]
The link that you provided contains a link that mentions that the "mammalian" NAT1 gene uses a GUG (GAG) start codon but probably not in the case of the human gene. I have only looked at NM_001291962.1 and that has a normal ATG initiation codon as annotated by RefSeq.

However, there is a recent paper (https://www.ncbi.nlm.nih.gov/pubmed/28981728) which says that the NAT1 gene ALWAYS initiates at a GTG codon, but I have not had the time to read the paper.

The UniProt entry for NAT1 shows just ONE protein isoform which may well be correct in spite of there being multiple transcripts: https://www.uniprot.org/uniprot/P18440#sequences

This needs more investigation. However, the solution that needs to be implemented requires a table of human genes and/or transcripts where there is good evidence of use of a non-ATG start codon and use that table of data to determine how VV reports the consequences of start-codon sequence variants.

**Comment by PeteCausey-Freeman** [comment]
Good spot. This is an interesting case.

So, the VV code does NOT assume Met is the first aa in a sequence, so if you see the description (Met?) It is validated against the protein reference sequence.  This is our code, not hgvs.py!

It is overkill to do anything more than this because variation is described in the context of reference sequences. In my opinion, if the Met is not correct in the reference sequence, it is not our job to change it, just describe the variation against the reference sequence.

My simple solution is that if a variant changes neither the first aa in the protein nor the sequence of the first codon, it is safe to assume e.g. (aa1=) if not, it is probably safer to return (aa1?).

**Comment by PeteCausey-Freeman** [comment]
According to NCBI, alternate Mitochondrial Human start codons are

AUA giving Met
AUU

[https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG1](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG1)

I figure that if the variant has not affected the sequence of the initiation aa, we should probably predict aa=. Alterations causing defections in splicing or consensus start regions are beyond the scope of VV. These are annotation problems

**Comment by leicray** [comment]
Is this an actual issue at present, or is it theoretical?

I thought that there are are no RefSeq reference sequences for mitochondrial transcripts or proteins. Please correct me if I'm wrong. In the absence of such reference sequences, VV would not be able to project a mitochondrial genomic variant at a start codon to a transcript or a protein.

However, I think that the principle is sound that variant descriptions at the protein level should be generated from changes in the protein sequence, irrespective of whether we are thinking of mitochondrial or nuclear genes.

**Comment by PeteCausey-Freeman** [comment]
Agreed, this is theoretical for now. I have commented on the hgvs.py

https://github.com/biocommons/hgvs/issues/567

There are a fair few mito genes that have moved into the primary assembly, so have NM_ entries. Also, RefSeq are in the process of creating NM_ (Many thanks for Terence for the information). 

I'm currently of the opinion that any variant which changes in any way the Start codon should safely be referred to as Met1 (or other) ?. I'm on the fence regarding base substitutions in seemingly erroneous genomic sequence compared to a transcript reference sequence because we cannot be sure which is correct, the genome or the transcript. Even Protein sequencing would unlikely tell us since the initiating aa is usually cleaved off. Therefore, I'm more comfortable with Met1? which should prompt additional investigation by the clinicians.

**Comment by PeteCausey-Freeman** [comment]
Closing because discussion with Reece and co has concluded that variants that affect the translation initiation region may cause loss of translation even if the change in sequence does not suggest it may. Additional annotations and predictions outside of the scope of this tool will be required!
