### ISSUE TITLE
Create informative message for uncertain positions

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#92]
The current is not great

**Comment by PeteCausey-Freeman** [comment]
By uncertain positions I mean c.(?)_(?)

**Comment by PeteCausey-Freeman** [comment]
We need plenty of examples and a clear regex that will pick these up

**Comment by ifokkema** [comment]
Some LOVD BRCA1 examples that currently fail:
`NC_000017.10:g.(41234593_41242960)_(41277500_?)dup`
`NC_000017.10:g.(?_41196312)_(41277500_?)del`
`NC_000017.10:g.(?_41196312)_(41209153_41215349)del`

Example of what could possibly be supported:
`NC_000017.10:g.(41197820_41199659)_(41199721_41201137)del`

**Comment by PeteCausey-Freeman** [comment]
Thanks Ivo.

**Comment by ifokkema** [comment]
Adding a message like added for handling #168 would be fine for me!
> Uncertain positions are not currently supported

**Comment by peq123** [comment]
`-
{'flag': 'warning',
 'metadata': {'seqrepo_db': '2018-08-21',
  'uta_schema': 'uta_20180821',
  'variantvalidator_hgvs_version': '1.2.5.vv1',
  'variantvalidator_version': '1.0.4.dev17+gd16b9ef.d20200422'},
 'validation_warning_1': {'alt_genomic_loci': [],
  'gene_ids': {},
  'gene_symbol': '',
  'genome_context_intronic_sequence': '',
  'hgvs_lrg_transcript_variant': '',
  'hgvs_lrg_variant': '',
  'hgvs_predicted_protein_consequence': {'slr': '', 'tlr': ''},
  'hgvs_refseqgene_variant': '',
  'hgvs_transcript_variant': '',
  'primary_assembly_loci': {},
  'reference_sequence_records': '',
  'refseqgene_context_intronic_sequence': '',
  'submitted_variant': 'NC_000017.11:g.(?_43070908)_(43076634_?)dup',
  'transcript_description': '',
  'validation_warnings': ['NC_000017.11:g._dup: char 15: expected one of (, ?, or a digit']}}

`
xpost:

For clarity:
'submitted_variant': 'NC_000017.11:g.(?_43070908)_(43076634_?)dup',
 'validation_warnings': ['NC_000017.11:g._dup: char 15: expected one of (, ?, or a digit']

is there an issue with the preparation steps in variant validator?

peq123

**Comment by peq123** [comment]
on this note. if a range is present, what is the best course to take? My first thought would take the inner range as this is known?
`NC_000017.11:g.(?_43070908)_(43076634_?)dup` 
would be validated for 43070908 to 43076634 for instance? Is this correct?

**Comment by ifokkema** [comment]
> For clarity:
> 
> ```
> 'submitted_variant': 'NC_000017.11:g.(?_43070908)_(43076634_?)dup',
>  'validation_warnings': ['NC_000017.11:g._dup: char 15: expected one of (, ?, or a digit']
> ```

The same happened in #168, it's what currently happens when uncertain positions are encountered.


> on this note. if a range is present, what is the best course to take? My first thought would take the inner range as this is known?
> `NC_000017.11:g.(?_43070908)_(43076634_?)dup`
> would be validated for 43070908 to 43076634 for instance? Is this correct?

In principle, that variant _could_ be supported _partially_ by taking the known positions, mapping it to transcripts or to the other genome build(s), and re-introducing the uncertainties in the output, but I'm not sure if Pete wants to go in that direction. You can work around this of course, by sending in `NC_000017.11:g.43070908_43076634dup` and then taking the positions of the resulting mappings.

I personally handle variants like this by storing their known positions with a maximum of two, indeed preferring the inner positions.

**Comment by ifokkema** [comment]
This one is also very creative; [`NC_000023.10:g.(?_153357667)dup`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000023.10%3Ag.(%3F_153357667)dup/all/all/True/False?content-type=application%2Fjson) returns:

```json
{
  "NC_000023.10:g.(?_153357667)dup": {
    "NC_000023.10:g.(?_153357667)dup": {
      "genomic_variant_error": "'<' not supported between instances of 'NoneType' and 'int'",
    },
    "flag": "genomic_variant_warning"
  }
}
```

I suppose there's a bit of code there that tries `"?" < 153357667` :sweat_smile:

**Comment by PeteCausey-Freeman** [comment]
Passed over to issue https://github.com/openvar/variantValidator/issues/328
